import type { GuideContent } from "../../../lib/guides/types.ts";
import { blackwingLair } from "../../../lib/guides/registry.ts";
import { icy, list, p, section, wowhead } from "../helpers.ts";

export const blackwingLairContent: GuideContent = {
  summary: "Prepare for eight Classic Era progression encounters in Nefarian's 40-player raid: attunement, coordinated trash pulls, threat control and role assignments.",
  tags: ["Raid", "Preparation", "40 players"],
  sources: [
    wowhead("Blackwing Lair overview — Classic", "blackwing-lair-raid-overview-classic-wow"),
    wowhead("Blackhand's Command attunement", "blackwing-lair-attunement-blackhands-command-classic-wow"),
    wowhead("Broodlord and the Suppression Room — Classic", "broodlord-lashlayer-blackwing-lair-strategy"),
    icy("Blackwing Lair — standard Classic entry and trash sections only", "blackwing-lair-raid-guides"),
    icy("Chromaggus — standard Classic preparation only", "chromaggus-guide-strategy-abilities-loot"),
  ].map(source => ({ ...source, accessedAt: "2026-09-22" })),
  sections: [
    section("overview", "Overview", p("Blackwing Lair is a level-60, 40-player raid in Blackrock Mountain. Its eight progression encounters build toward Nefarian. This overview covers standard Classic Era; seasonal trials and Season of Mastery encounter changes do not apply."), p("Use this page to plan the run and assign responsibilities. Individual boss walkthroughs are not published yet; the ordered reference below identifies the encounters without linking to unfinished articles.")),
    section("entry", "Entry and attunement", p("For the convenient entrance, kill the Scarshield Quartermaster in the hallway to the right of the Blackrock Spire entrance. Loot and accept Blackhand's Command, then complete Upper Blackrock Spire and touch the Orb of Ascension behind General Drakkisath. Completing the quest unlocks the Orb of Command shortcut outside the dungeon."), p("Without that shortcut, the raid entrance can be reached through Upper Blackrock Spire after Rend's area. Arrange attunement before raid night so the group does not spend its scheduled time transporting players through the dungeon.")),
    section("preparation", "Raid preparation", list("Repair, clear bag space and bring food, water, class reagents, ammunition where needed, and enough recovery consumables for repeated attempts.", "Confirm tank backups, healer coverage and target marks before entering. Assign an orb controller and add teams for the opening encounter rather than improvising after the pull.", "Check Onyxia Scale Cloaks before the drakes and Nefarian. Equipping the cloak prevents Shadow Flame's dangerous lingering effect; it does not make the initial breath harmless.")),
    section("mechanics", "Raid-wide habits and mechanics", list("Keep dragon frontal attacks away from the raid and follow the assigned position. Repositioning a boss can expose players who were previously safe.", "Threat reductions and tank transitions make a strong opening threat lead temporary. Follow stop-damage calls and give the next tank room to establish control.", "Learn the designated line-of-sight corners before combat. Breath handling is encounter-specific: do not assume that hiding from every cast is always correct, particularly when Chromaggus has Time Lapse.", "Treat dispels as assigned work. Chromaggus requires coverage for curses, magic, poison and disease; hiding from a breath does not prevent his afflictions.")),
    section("roles", "Role preparation", list("Tanks: agree add ownership, backup pickups and threat order. Healers must know which tank will take damage next, including off-tanks away from the main group.", "Healers: confirm range and movement routes before a pull. Protect mana during the gauntlet, and coordinate dispels so tank healing does not disappear while everyone cleanses.", "DPS: respect marks and tank transitions. Hunters with Tranquilizing Shot should arrange a Frenzy-removal rotation and a backup for misses.", "Rogues: have Disarm Trap ready for suppression devices and coordinate the route with the pull leader. Utility assignments take priority over a damage meter.")),
    section("consumables", "Consumables and resistance considerations", p("Bring the healing or mana potions and role consumables your group expects, with a plan for protection potions on dangerous fire damage. Resistance choices should support the assigned job; do not replace a functional tank or healing set with a blanket resistance set for every encounter."), p("Fire protection is not a substitute for an Onyxia Scale Cloak or correct positioning. Check equipment before the pull rather than discovering a missing cloak during Shadow Flame."), p("Collect Hourglass Sand from raid trash and distribute it deliberately before Chromaggus, prioritizing critical tank and healer duties. It removes the Bronze affliction, which ordinary dispels cannot clear. Restorative Potions and appropriate anti-venom can supplement assigned dispellers, but do not replace coverage.")),
    section("trash", "Suppression and trash considerations", list("Pull the tightly packed groups after Vaelastrasz into a cleared area where possible. Watch patrols before committing; an extra pack can overwhelm otherwise adequate healing.", "Move through the Suppression Room as a coordinated group. Rogues clear devices along the route while tanks gather incoming enemies. Keep damage controlled until pickups are secure, and avoid leaving healers behind.", "Plan the gauntlet pace around healer mana. Repeated spawns make an improvised long rest unreliable; call problems early rather than letting the group stretch out.", "Assign control of Blackwing Technicians and their bombs before pulling. Separate dangerous large trash targets and keep their tank positions predictable instead of collapsing everything onto the raid.")),
    section("mistakes", "Common mistakes", list("Arriving without attunement, repairs or the required cloak and delaying the whole raid.", "Chasing damage through a threat drop or ignoring an assigned dispel, trap or Tranquilizing Shot.", "Moving through suppression devices alone and pulling additional enemies onto an unprepared group.", "Spending the group's Hourglass Sand casually or assuming a protection potion solves every damage type.")),
    section("boss-order", "Boss quick-reference", p("Eight progression encounters, in raid order. Ebonroc and Flamegor are separate encounters in standard Classic Era. Boss detail guides will appear here when published."), { kind: "bosses", raidId: blackwingLair.id }),
  ],
};
