import type { GuideContent } from "../../../lib/guides/types.ts";
import { icy, list, p, section, wowhead } from "../helpers.ts";

export const combat: GuideContent = {
  summary: "Prepare a level-60 Combat Rogue for Classic Era raids: maintain Slice and Dice, match your weapons to your build, and spend energy with a plan.",
  tags: ["Melee", "Rogue", "Preparation"],
  sources: [
    icy("Classic Rogue overview and professions", "rogue-dps-pve-guide"),
    icy("Classic Rogue talents and weapon builds", "rogue-dps-pve-spec-builds-talents"),
    wowhead("Classic Rogue build allocations", "classic-rogue-pve-dps"),
    wowhead("Classic Rogue stats and glancing blows", "classes/rogue/dps-stat-priority-attributes-pve"),
    wowhead("Classic melee hit thresholds at 300 and 305 skill", "classes/warrior/fury/dps-stat-priority-attributes-pve"),
    icy("Classic Rogue priority and energy use", "rogue-dps-pve-rotation-cooldowns-abilities"),
    wowhead("Classic Rogue Slice and Dice and cooldowns", "classes/rogue/dps-rotation-cooldowns-abilities-pve"),
    wowhead("Classic Rogue poisons and Windfury", "wow-classic-best-rogue-poisons"),
    icy("Classic Rogue consumables", "rogue-dps-pve-enchants-consumables"),
    wowhead("Classic world buffs", "classic-world-buff-consumables"),
  ].map(source => ({ ...source, accessedAt: "2026-09-21" })),
  sections: [
    section("overview", "Overview", p("Combat rewards sustained melee contact and strong weapons. Auto attacks are a large part of your damage; energy and combo points support them through Slice and Dice and direct attacks. This is a level-60 Classic Era raid guide, with swords as the main example and a separate explanation of Combat daggers. Guide builds do not replace your imported Armory talents.")),
    section("strengths", "Strengths and limitations", list("Strong sustained single-target damage and a useful two-target burst window with Blade Flurry. Kick, Sprint and Vanish help you meet assignments and manage dangerous situations.", "Forced movement costs melee uptime. Target changes disrupt combo-point planning, and your own survival still matters when cooldowns are available. Combat has no unrestricted area-damage rotation; controlled targets and positioning limit cleave.")),
    section("talents", "Talents", list("Combat swords commonly uses 19 Assassination / 32 Combat / 0 Subtlety. Build around Precision, Dual Wield Specialization, Sword Specialization, Weapon Expertise, Blade Flurry and Adrenaline Rush; Improved Sinister Strike supports your builder.", "Assassination supplies Improved Slice and Dice and useful finisher support such as Ruthlessness and Relentless Strikes. Agree any Improved Expose Armor assignment before changing those points.", "Combat daggers commonly uses 15 / 31 / 5, taking dagger and Backstab support plus Opportunity. It requires a main-hand dagger and access to the target's back; do not copy a sword builder priority unchanged.", "These are build outlines. Use the reviewed allocation sources for all 51 points and optional swaps; choose talents for the weapon types you actually equip.")),
    section("stats", "Stats", p("Agility supplies attack power and critical strike; Strength supplies attack power. Weapon damage, useful hit and critical strike interact with the whole loadout, so compare complete items rather than following an unconditional stat ranking. A hard-hitting main hand supports weapon-based builders, while off-hand speed affects poison opportunities. Match weapon specialization and skill bonuses to the actual weapon type."), p("Stamina gives room to survive unavoidable damage. Critical strike value also depends on the available auto-attack hit table, especially with world buffs; there is no single crit cap for every loadout. The gear reference is curated, not a simulated DPS score.")),
    section("weapon-skill", "Weapon skill and hit", p("Train equipped weapon skills to 300 before raiding. Against a level-63 boss, special attacks require 9% total hit at 300 weapon skill, or 6% at 305 skill. With 5/5 Precision providing 5%, those examples leave 4% or 1% from gear respectively. Check each weapon's effective skill; these are special-attack miss thresholds, not a guarantee against dodges."), p("Weapon Expertise adds skill to swords, daggers and fist weapons; Human sword skill applies only when using swords, not daggers. Skill also reduces the damage penalty of glancing auto attacks, with that benefit reaching its soft cap around 308. Weapon Expertise is a weapon-skill talent, not the later expertise-rating stat."), p("Dual-wield auto attacks have a higher miss chance than specials. Additional hit can therefore remain valuable beyond the special threshold. Attack from behind to avoid parries and blocks; do not sacrifice encounter positioning to chase a number.")),
    section("rotation", "Rotation / priority", list("Let the tank establish control, start auto attacks from behind, and build combo points with Sinister Strike for swords. Keep Slice and Dice running before spending surplus points on damage finishers.", "Use Eviscerate when there is enough Slice and Dice time left to rebuild safely, normally at five points; a dying target may justify fewer. Do not spend into an imminent buff gap.", "Combat daggers uses Backstab from behind. Its higher energy cost leaves fewer spare points, making Slice and Dice maintenance especially important. Reposition safely if the target turns.", "Avoid capping energy or building beyond five combo points. Save energy for an assigned Kick. Coordinate Expose Armor with the raid because it does not stack with Sunder Armor; do not apply it without an assignment.")),
    section("slice-and-dice", "Slice and Dice usage", p("Get the buff active early, often with one or two initial combo points, rather than waiting through an unbuffed five-point opener. More points extend duration, not the attack-speed bonus. Longer refreshes are efficient when the target will live long enough, but preventing downtime takes priority over reaching five."), p("Watch its remaining duration alongside energy and combo points. Refresh before it falls off, without repeatedly throwing away a large amount of remaining time. Before a planned cooldown window, arrange enough duration to spend that window attacking. Short trash pulls may end before a perfect setup pays off.")),
    section("cooldowns", "Cooldowns", list("Blade Flurry supplies attack speed even on one target and copies attacks to a nearby second target. Use the cleave only when that target is meant to take damage; check nearby crowd control.", "Adrenaline Rush increases energy regeneration. Combine it with useful melee uptime and avoid wasting energy at the cap. Pair damage cooldowns when the encounter allows, but do not save them so long that you lose an entire use.", "Use Sprint to recover safe uptime and Vanish to drop threat before pulling the boss. Carry Flash Powder and remember incoming damage can break stealth. Evasion helps against dodgeable attacks; it is not immunity or a plan for tanking raid mechanics.")),
    section("poisons", "Poisons", p("Train your poison skill and carry enough reagents and charges for the raid. Instant Poison VI is the usual raid damage choice. Reapply between pulls and check the weapon after swapping it. For Horde receiving Windfury Totem, leave the main hand free of poison and use poison on the off hand; without Windfury, Instant Poison on both weapons is a straightforward baseline."), p("Some targets are poison immune. Deadly Poison occupies a debuff slot and can interfere with later crowd control, so agree its use rather than applying it by default. Crippling, Mind-numbing and Wound Poison are assignment-dependent utility options, not automatic boss damage upgrades. There is no Envenom cycle in this Era priority.")),
    section("consumables", "Consumables", p("Choose a sustainable budget. Healing and protection potions share a potion cooldown, so plan around the encounter. Thistle Tea restores energy: use it with room to benefit, rather than near the energy cap."), { kind: "wowhead", entries: [
      { type: "item", id: 7676, name: "Thistle Tea", note: "Energy recovery for a useful damage window." },
      { type: "item", id: 13452, name: "Elixir of the Mongoose", note: "Agility and critical strike." },
      { type: "item", id: 13928, name: "Grilled Squid", note: "Agility food; check your budget and availability." },
      { type: "item", id: 12451, name: "Juju Power", note: "Strength option." },
      { type: "item", id: 13446, name: "Major Healing Potion", note: "Emergency health reserve." },
      { type: "item", id: 13457, name: "Greater Fire Protection Potion", note: "Situational fire absorption for Molten Core." },
      { type: "item", id: 14530, name: "Heavy Runecloth Bandage", note: "Recovery in a safe break; requires First Aid." },
    ] }),
    section("world-buffs", "World buffs", p("Rallying Cry of the Dragonslayer, Songflower Serenade and Dire Maul's Fengus' Ferocity improve physical damage. Mol'dar's Moxie adds Stamina. Horde Warchief's Blessing supplies melee haste; Spirit of Zandalar improves primary stats. Coordinate collection if your group uses buffs, but losing them does not excuse ignoring mechanics. These are mature-Era options, not a promise that every buff belongs to Phase 1 or a new readiness requirement.")),
    section("professions", "Professions", p("Engineering provides explosives and utility, with threat, crowd-control and self-damage risks to consider. Leatherworking can supply crafted leather gear, while Alchemy or gathering can support your consumable budget. Check whether a reference item requires a profession to equip before changing professions. Cooking supports Thistle Tea and food preparation; First Aid is a useful secondary skill for downtime.")),
    section("gear", "Gear — Pre-Raid and Phase 1", p("These sets read the accepted Combat Rogue registry shared with Advice. Pre-Raid uses its mature-Era non-raid pool; Phase 1 applies its phase and source rules. Expand slots for targets and alternatives. Check weapon type, faction and acquisition notes before farming; this is a reference, not a personalized upgrade calculation or a separate dagger gear list."), { kind: "gear", specKey: "era-rogue-combat", phases: [0, 1] }),
    section("raid-preparation", "Raid preparation", list("Repair, train ability ranks and weapon skill, restock poisons and Flash Powder, and bring agreed consumables.", "Confirm Kick rotations, target order, any Expose Armor assignment and Windfury coverage. Choose a position behind the target with a clear route out.", "On Garr, protect controlled adds from Blade Flurry. On Geddon, leave immediately with Living Bomb. For Ragnaros, plan your retreat and return after tank control."), { kind: "links", guideIds: ["era-molten-core", "era-boss-50666", "era-boss-50668", "era-boss-50672"] }),
    section("mistakes", "Common mistakes", list("Letting Slice and Dice expire while saving for a damage finisher, or refreshing it far too early every cycle.", "Treating the special hit threshold as the dual-wield auto-attack cap, or counting a skill bonus for the wrong weapon.", "Poisoning a Windfury main hand, forgetting to refresh charges, or cleaving a controlled add.", "Capping energy during Adrenaline Rush, spending the energy needed for Kick, or delaying movement for one more attack.")),
  ],
};
