import type { GuideContent } from "../../../lib/guides/types.ts";
import { icy, list, p, section, source, wowhead } from "../helpers.ts";

export const frost: GuideContent = {
  summary: "Prepare a level-60 Frost Mage for Classic Era raids: reliable Frostbolts, deliberate mana use, and useful raid support.",
  tags: ["Ranged", "Mage", "Preparation"],
  sources: [
    source("Classic Mage talent metadata", "WoWSims Classic", "https://github.com/wowsims/classic/blob/c925c1184dcd0c5eaff2d128af899be639235b63/ui/core/talents/trees/mage.json"),
    icy("Classic Mage overview and professions", "mage-dps-pve-guide"),
    icy("Classic Mage talents: Arcane Power and Winter's Chill", "mage-dps-pve-spec-builds-talents"),
    icy("Classic Mage spell priority and cooldowns", "mage-dps-pve-rotation-cooldowns-abilities"),
    wowhead("Classic Mage abilities and mana tools", "classes/mage/dps-rotation-cooldowns-abilities-pve"),
    icy("Classic Mage spell hit and stats", "mage-dps-pve-stat-priority"),
    icy("Classic Mage world buffs and consumables", "mage-dps-pve-enchants-consumables"),
    wowhead("Classic Mage consumables and raid buffs", "classes/mage/dps-consumables-raid-buffs-pve"),
  ].map(source => ({ ...source, accessedAt: "2026-09-21" })),
  sections: [
    section("overview", "Overview", p("This guide covers level-60 Classic Era Frost DPS, especially preparation for Molten Core. Frostbolt supplies sustained damage while your utility keeps the group moving. Use your actual specialization and assigned raid role when choosing a build. These suggestions do not replace your saved Armory talents.")),
    section("strengths", "Strengths and limitations", list("Frost damage works well against the fire-resistant or fire-immune enemies encountered in early raids. Polymorph, Counterspell, Remove Lesser Curse, conjured supplies and portals give Mages jobs beyond damage.", "Movement interrupts hard casts, and careless spending can exhaust mana before a fight ends. Many bosses cannot be frozen: do not expect a Shatter setup to work on every raid target. Frost is not automatically the strongest Mage build for every later Era encounter.")),
    section("talents", "Talents", { kind: "talent-build", buildId: "era-frost-arcane-power", alternativeBuildIds: ["era-frost-winters-chill"] }, list("Arcane Power Frost commonly uses 31 Arcane / 0 Fire / 20 Frost. It combines Arcane Power and Presence of Mind with Improved Frostbolt, Elemental Precision, Ice Shards, Piercing Ice and Frost Channeling. It cannot also take deep-Frost defensive talents.", "The reviewed Winter's Chill support variant shown here uses 16 Arcane / 0 Fire / 35 Frost. It takes Permafrost and Improved Blizzard for control, alongside Ice Block and Ice Barrier. Other common 19/0/32 variants move utility points toward Arcane mana support; those are not the allocation displayed here. Coordinate one Mage to maintain its five stacks, increasing the raid's Frost spell critical strike chance. Deep Frost also permits Ice Block and Ice Barrier; spare utility points depend on your assignments.", "Both builds value efficient Frostbolt casting. Choose support coverage before chasing personal damage. The Arcane Power example spends four points in Magic Absorption and one in Arctic Reach; these utility choices can vary with assignments. The selector shows two complete guide builds, not your saved character talents or an editable calculator.")),
    section("stats", "Stats and spell hit", p("Against a level-63 raid boss, spells need 16% added hit to reach the unavoidable 1% miss floor. Three points in Elemental Precision supply 6% for Frost and Fire, leaving 10% from gear for Frostbolt. This does not cap Arcane spells or remove school immunity. Lower-level enemies require less hit."), p("Spell damage, useful hit and critical strike all matter; Ice Shards improves Frost critical damage. Intellect supplies mana and some spell crit. Compare whole items rather than discarding substantial spell damage for any small hit gain. Stamina helps you survive; mana regeneration matters when fight length demands it. The gear reference below is curated, not a universal stat-weight simulation.")),
    section("rotation", "Spell priority / rotation", list("Single target: let the tank establish control, then keep your highest appropriate trained Frostbolt rank casting. If assigned Winter's Chill, establish and maintain stacks. Stop for required decurses, interrupts and mechanics.", "Move early and resume casting from a safe position. An instant Fire Blast can finish a target or fill movement when the target is not fire immune; do not force it into stationary Frostbolt casting.", "Multiple targets: wait for tank control and protect Polymorph targets. Blizzard offers ranged area damage; Cone of Cold and Arcane Explosion require safe proximity. Mana and threat can make controlled single-target damage the better choice.")),
    section("cooldowns", "Cooldowns and mana", list("If talented, use Arcane Power with a safe casting window and enough mana for its increased cost. Presence of Mind supplies an instant cast; coordinate trinkets with useful uptime.", "Prepare mana gems before combat. Use a gem or mana potion before emptying your pool, allowing room for its return. Channel Evocation during a safe lull, not incoming damage or required movement.", "If talented, Ice Block is defensive immunity, not a permanent threat reset. Cold Snap resets Frost cooldowns, not Arcane Power or Evocation. Ice Barrier can protect casts from damage pushback.")),
    section("consumables", "Consumables", p("Start with mana recovery and encounter survival, then add offensive buffs within your budget. Potions share a cooldown: reserve protection or healing when needed. Runes consume health, so use them only with a safe health margin."), { kind: "wowhead", entries: [
      { type: "item", id: 13444, name: "Major Mana Potion", note: "Core: mana recovery during longer encounters." },
      { type: "item", id: 12662, name: "Demonic Rune", note: "Situational: trades health for mana; coordinate with incoming damage." },
      { type: "item", id: 13454, name: "Greater Arcane Elixir", note: "Useful: spell damage." },
      { type: "item", id: 17708, name: "Elixir of Frost Power", note: "Useful: Frost spell damage." },
      { type: "item", id: 13931, name: "Nightfin Soup", note: "Useful: food supporting mana regeneration." },
      { type: "item", id: 13512, name: "Flask of Supreme Power", note: "Optional expensive spell-damage flask; agree a budget." },
      { type: "item", id: 13457, name: "Greater Fire Protection Potion", note: "Encounter option for fire damage in Molten Core." },
    ] }),
    section("world-buffs", "World buffs", p("Rallying Cry of the Dragonslayer, Songflower Serenade and Dire Maul's Slip'kik's Savvy offer spell crit. Spirit of Zandalar improves primary stats. Warchief's Blessing offers Horde mana regeneration and health; its melee haste does not speed Frostbolt. Coordinate collection if your group uses buffs. These are mature-Era options, not a claim that every buff belongs to Phase 1, and this guide does not make them readiness requirements.")),
    section("professions", "Professions", p("Tailoring supports crafted caster equipment, including the Mage-only Robe of the Archmage. Engineering adds explosives and utility, with positioning and self-damage risks. Alchemy or gathering can support your consumable budget. Choose around your plans and the reference item's profession requirements; you do not need to change professions merely to read this guide. First Aid is a useful secondary profession.")),
    section("gear", "Gear — Pre-Raid and Phase 1", p("These sets read the accepted Frost Mage registry used by Advice. Pre-Raid follows its mature-Era non-raid pool; Phase 1 follows its phase and source rules. Expand a slot for targets and alternatives, and check acquisition and profession notes before farming. This reference is not a personalized upgrade calculation."), { kind: "gear", specKey: "era-mage-frost", phases: [0, 1] }),
    section("raid-preparation", "Raid preparation", list("Repair, train ranks, bring reagents for group buffs and portals, and prepare water and mana gems before the pull.", "Confirm Winter's Chill coverage, curse removal, interrupt and Polymorph assignments. Put those spells on accessible bindings.", "Review positioning and escape routes before committing to a cast. On Lucifron, prioritize assigned curse removal; on Geddon, leave the group immediately with Living Bomb."), { kind: "links", guideIds: ["era-molten-core", "era-boss-50663", "era-boss-50668"] }),
    section("mistakes", "Common mistakes", list("Copying a build without checking who supplies Winter's Chill, or assuming every Frost build has Ice Block.", "Overcapping Frost hit while treating Arcane spells as capped too.", "Spending the last mana before using recovery, clipping Blizzard, or using area damage into crowd control.", "Finishing one more Frostbolt instead of moving or removing an assigned curse.")),
  ],
};
