import type { GuideContent } from "../../../lib/guides/types.ts";
import { icy, list, p, section, wowhead, source } from "../helpers.ts";

export const fury: GuideContent = {
  summary: "A raid preparation guide for dual-wield Fury: build rage, spend it deliberately, and keep your melee uptime safe.",
  tags: ["Melee", "Warrior", "Preparation"],
  sources: [
    { ...source("Classic Warrior talent positions and rank IDs", "WoWSims Classic", "https://github.com/wowsims/classic/blob/ade8d105bb81fb3e4620077b6ddfa73f11c7a60c/ui/core/talents/trees/warrior.json"), accessedAt: "2026-09-21" },
    wowhead("Fury Warrior overview", "classes/warrior/fury/dps-overview-pve"),
    wowhead("Fury talents and builds", "classes/warrior/fury/dps-talent-builds-pve"),
    wowhead("Fury stats and weapon skill", "classes/warrior/fury/dps-stat-priority-attributes-pve"),
    wowhead("Fury abilities and rotation", "classes/warrior/fury/dps-rotation-cooldowns-abilities-pve"),
    icy("Warrior priority and cooldowns", "warrior-dps-pve-rotation-cooldowns-abilities"),
    icy("Warrior consumables", "warrior-dps-pve-enchants-consumables"),
    wowhead("Fury consumables and raid buffs", "classes/warrior/fury/dps-consumables-raid-buffs-pve"),
  ],
  sections: [
    section("overview", "Overview", p("Fury turns weapon damage into rage and rage into special attacks. Strong weapons, group buffs and sustained contact with a target help that loop. Cleave and Execute give it useful burst windows; movement, threat limits and low rage can interrupt them. Plan around the encounter rather than a fixed button sequence."), p("This is a level-60 Classic Era DPS guide. It does not describe Fury tanking, and its talent suggestions are separate from your character’s saved Armory talents.")),
    section("talents", "Talents", { kind: "talent-build", buildId: "era-fury-dual-wield" }, { kind: "callout", label: "Common strategy", text: "17 Arms / 34 Fury / 0 Protection is a common dual-wield raid build. Utility points can vary; this is not the only valid Fury build." }, list("Arms: work toward Impale, with Deep Wounds and its Improved Rend prerequisite. Tactical Mastery helps retain rage when changing stance; Anger Management supports rage management.", "Fury: build around Bloodthirst, Flurry and Death Wish, with Cruelty, Dual Wield Specialization and Improved Execute. Battle Shout talents support your group.", "A two-handed build changes weapon and Slam priorities, particularly with Horde Windfury support. Do not copy a dual-wield priority unchanged into that setup."), { kind: "wowhead", entries: [{ type: "spell", id: 23881, name: "Bloodthirst", note: "Fury capstone — 1 talent point; train subsequent ability ranks." }, { type: "spell", id: 12328, name: "Death Wish", note: "Fury cooldown — 1 talent point." }] }, p("The visual guide build shows one complete 17/34/0 allocation. It is a read-only recommendation, not your imported talents or a respec calculator. The explanation below the trees describes its goals; reviewed sources discuss optional point swaps.")),
    section("stats", "Stats, hit and weapon skill", p("Train your equipped weapon types to maximum skill first. Against a level-63 raid boss, special attacks need 9% hit at 300 weapon skill, or 6% at 305 skill. Those are special-attack miss thresholds, not caps for every dual-wield auto attack; they do not remove dodges."), p("Weapon skill also reduces glancing-blow damage penalties. Check the actual weapon type covered by a racial or item bonus; a sword bonus does not help an axe. Attack from behind to avoid parries and blocks."), p("Once the relevant hit threshold is covered, compare weapon quality, Strength/attack power and critical strike together. Critical strikes support Flurry; Strength supplies attack power. Extra hit can still help white attacks. Buffs and your complete loadout change tradeoffs, so a single unconditional stat ordering is misleading.")),
    section("rotation", "Rotation / priority", list("Single target: keep Battle Shout active, follow assigned Sunder Armor duties, then prioritize Bloodthirst and use Whirlwind when rage allows. Maintain auto attacks from behind.", "Heroic Strike spends rage on the next main-hand swing and replaces its normal rage generation. Queue it with surplus rage; do not starve your next Bloodthirst. There is no universal rage threshold for every weapon and buff setup.", "Execute phase: below 20% health, Execute becomes a major rage outlet. Avoid dumping rage into Heroic Strike before it. Bloodthirst can remain competitive with strong attack power; adjust to rage income instead of blindly following a fixed sequence.", "Multiple targets: use Whirlwind and Cleave only when targets are safely tanked and crowd control will remain intact. Keep priority-target damage and assigned interrupts ahead of incidental cleave.")),
    section("cooldowns", "Cooldowns", p("Use Death Wish during a window when you can stay on target and the tank has control. Its defensive penalty matters during incoming damage. Recklessness also increases risk: agree a safe burn window rather than activating it during a dangerous mechanic. Bloodrage costs health; avoid it when already close to dying."), p("Coordinate damage cooldowns with useful uptime, group buffs and Execute opportunities. Saving every cooldown for the final seconds can waste an earlier use, while using them just before forced movement wastes their duration.")),
    section("consumables", "Consumables", p("Choose a practical budget with your group. These categories describe utility, not admission requirements. Healing, rage and protection potions compete for potion cooldowns."), { kind: "wowhead", entries: [
      { type: "item", id: 13446, name: "Major Healing Potion", note: "Core: an emergency health reserve." },
      { type: "item", id: 14530, name: "Heavy Runecloth Bandage", note: "Core: recovery during a safe break; requires First Aid." },
      { type: "item", id: 13452, name: "Elixir of the Mongoose", note: "Useful: offensive Agility and critical strike buff." },
      { type: "item", id: 9206, name: "Elixir of Giants", note: "Useful: Strength option." },
      { type: "item", id: 13442, name: "Mighty Rage Potion", note: "Useful: rage and a temporary Strength boost in a damage window." },
      { type: "item", id: 18262, name: "Elemental Sharpening Stone", note: "Useful: weapon enhancement; keep your main hand free for Windfury when receiving it." },
      { type: "item", id: 13457, name: "Greater Fire Protection Potion", note: "Situational: absorbs fire damage, especially useful for Ragnaros preparation." },
    ] }),
    section("world-buffs", "World buffs", p("Rallying Cry of the Dragonslayer, Songflower Serenade and Dire Maul tribute buffs can substantially change damage and rage income. Warchief’s Blessing is another important Horde buff. Plan collection with the raid if desired; losing a buff is not a reason to ignore mechanics or stop participating. Guides do not make these buffs a readiness requirement.")),
    section("professions", "Professions", p("Engineering offers combat tools and explosives, but check target immunities and avoid breaking control. Sapper use also costs health. Gathering or Alchemy can support your consumable budget; profession choice should fit your time and group needs. First Aid is a secondary profession and useful even when you choose other primary professions.")),
    section("gear", "Gear — Pre-Raid and Phase 1", p("These targets and alternatives come from the same published Fury reference used by Advice and Session Planner. They are a planning list, not a personalized upgrade calculation. Read faction, profession and weapon-context notes before farming. Pre-Raid uses the accepted mature-Era non-raid pool; Phase 1 applies the same phase availability and source rules as Advice."), { kind: "gear", specKey: "era-warrior-fury", phases: [0, 1] }),
    section("raid-preparation", "Raid preparation", list("Repair, train weapon skill and ability ranks, and prepare your consumables before the invite.", "Confirm your interrupt, Sunder and emergency off-tank assignments. Carry a shield if you have agreed to help tank; a DPS build alone is not a tanking plan.", "Check Battle Shout coverage, threat expectations and your route out of melee for each encounter. Reserve bag space and time for the return trip.")),
    section("boss-notes", "Molten Core boss notes", p("Garr rewards controlled damage rather than indiscriminate cleave. On Baron Geddon, leave immediately with Living Bomb. For Ragnaros, save a clear escape route for Wrath and let the tank recover control before re-entering."), { kind: "links", guideIds: ["era-molten-core", "era-boss-50666", "era-boss-50668", "era-boss-50672"] }),
    section("mistakes", "Common mistakes", list("Treating the special-attack hit threshold as a guarantee that every attack lands.", "Spending all rage on queued attacks, then missing a priority ability or interrupt.", "Using cleave into controlled adds, chasing the boss through danger, or mistaking a guide talent build for your imported talents.")),
  ],
};
