import type { GuideContent } from "../../../lib/guides/types.ts";
import { icy, list, p, section, source, wowhead } from "../helpers.ts";

export const holy: GuideContent = {
  summary: "Prepare a level-60 Classic Era Holy Priest for raid healing: choose the right heal, preserve mana and keep your assignments alive.",
  tags: ["Healer", "Priest", "Preparation"],
  sources: [
    icy("Classic Priest healing overview and professions", "priest-healer-pve-guide"),
    icy("Classic Holy and Power Infusion raid builds", "priest-healer-pve-spec-builds-talents"),
    icy("Classic Priest healing and mana management", "priest-healer-pve-rotation-cooldowns-abilities"),
    icy("Classic Priest healing stats", "priest-healer-pve-stat-priority"),
    icy("Classic Priest spells and dispels", "priest-healer-pve-spell-summary"),
    icy("Classic Priest consumables and world buffs", "priest-healer-pve-enchants-consumables"),
    wowhead("Classic Priest spell selection and ranks", "classes/priest/healer-rotation-cooldowns-abilities-pve"),
    source("Classic Priest talent metadata", "WoWSims Classic", "https://github.com/wowsims/classic/blob/c925c1184dcd0c5eaff2d128af899be639235b63/ui/core/talents/trees/priest.json"),
  ].map(s => ({ ...s, accessedAt: "2026-09-22" })),
  sections: [
    section("overview", "Overview", p("Holy Priest has a flexible healing toolkit for tanks and raid members. Your task is to keep assigned targets alive while retaining enough mana for the encounter, not to win every healing-meter race. This guide covers level-60 Classic Era; Circle of Healing, Prayer of Mending, Penance and Shadowfiend are not available here.")),
    section("strengths", "Strengths and limitations", list("A broad choice of direct heals, Renew, emergency shields and party healing lets you respond to different damage patterns. Fortitude, Spirit support and dispels provide value beyond raw healing.", "Mana can disappear quickly through unnecessary fast heals and overhealing. Cast times, movement and party restrictions limit what you can cover. Agree assignments and stand where you can reach them before damage starts.")),
    section("talents", "Talents", { kind: "talent-build", buildId: "era-holy-standard", alternativeBuildIds: ["era-holy-power-infusion"] }, list("Standard Holy raid healing uses 21 Discipline / 30 Holy / 0 Shadow. Spiritual Guidance and Spiritual Healing support throughput; Divine Spirit supplies raid utility. Both displayed builds retain Meditation, Inner Focus, Healing Focus, Divine Fury and Inspiration.", "The sourced Power Infusion alternative is 32/19/0 and is Discipline-heavy. It gives up deep-Holy healing talents to support a coordinated caster damage window. Consider it only when healing coverage permits that tradeoff; it is not the default recommendation for a fresh healer.", "These exact representative allocations include Holy Nova and omit Lightwell. Coordinate Divine Spirit coverage and utility variations with the other Priests. They are guide builds, not a reading of your current talents. Viewing the alternative does not relabel a Discipline character as Holy or change your Advice gear reference.")),
    section("stats", "Healing stats", p("Healing power improves effective spell output and can make cheaper ranks practical. MP5 continues to restore mana during sustained casting. Spirit supports regeneration outside the five-second rule and adds healing through Spiritual Guidance in the standard Holy build. Intellect increases your mana pool; spell crit can trigger Inspiration but is not dependable emergency healing."), p("Keep enough stamina to survive the encounter. Balance throughput and regeneration around fight duration, incoming damage and consumable use rather than a rigid score. Healing spells on allies do not need a raid spell-hit cap. Offensive spells and enemy dispels are a different question.")),
    section("healing", "Healing spell selection and ranks", list("For modest sustained damage, keep an efficient Heal rank ready; Heal rank 3 is a useful starting point to test. Greater Heal covers larger predicted hits. Start the cast ahead of damage and cancel before completion if the heal will no longer be needed.", "Keep more than one Greater Heal rank bound: a low rank for efficient coverage and a higher trained rank for dangerous damage. The right rank changes with healing gear and your assignment; do not assume the cheapest cast will save a target.", "Flash Heal is the fast rescue tool, not a default mana sink. Rank 7 handles urgent damage; a lower rank such as 4 can serve smaller deficits. Train available ranks and reserve the full-strength option for emergencies.", "Renew helps during movement and predictable continued damage. Avoid refreshing it before useful ticks land or competing with another Priest's assignment. Power Word: Shield buys time but is costly, applies Weakened Soul and can interfere with rage generation on tanks; coordinate shields rather than blanketing automatically.", "Prayer of Healing affects your own party within range, not any chosen raid group. Use it when several party members need healing; choose a rank that fits their deficits. Holy Nova is short-range situational utility, not a replacement for larger heals.")),
    section("mana", "Mana management", p("Mana expenditure starts the five-second window that suppresses normal Spirit regeneration. Meditation preserves part of that regeneration; MP5 remains active. Cancelling an unfinished heal avoids its mana cost, so planned pauses can restore more mana. Do not force a regeneration break while your assignment is dying."), p("Use mana recovery early enough to benefit again in a long fight, leaving room for the return. Call out when you need coverage or an agreed Innervate. Drink between pulls, reduce avoidable overhealing and review which ranks actually landed useful healing.")),
    section("cooldowns", "Cooldowns", p("Inner Focus makes the next eligible spell free and boosts its critical chance. Pair it with a useful large heal or Prayer of Healing instead of wasting it on overheal. If using the Power Infusion alternative, agree the recipient and timing; its raid benefit depends on coordination. Fade temporarily reduces threat rather than erasing it permanently. Move toward tank help when needed and keep healing safely. Race-specific abilities such as Desperate Prayer or Fear Ward are not available to every Priest.")),
    section("dispels", "Dispels", list("Dispel Magic removes harmful magic from allies or removable beneficial magic from enemies. Cure Disease and Abolish Disease handle disease; they do not remove curses or poisons. Check the debuff type and raid plan rather than clicking every icon indiscriminately.", "Assign dispel coverage and backups before the pull. On Lucifron, handle assigned magic effects while curse removal belongs to classes that can remove curses. A dangerous dispel may outrank a small heal, but keep the tank covered when switching tasks.")),
    section("consumables", "Consumables", p("Start with water, mana recovery and encounter survival, then add healing buffs within your budget. Potions share a cooldown. Runes consume health, so avoid them during dangerous incoming damage."), { kind: "wowhead", entries: [
      { type: "item", id: 13444, name: "Major Mana Potion", note: "Core mana recovery for longer fights." },
      { type: "item", id: 12662, name: "Demonic Rune", note: "Optional health-for-mana recovery; use with a safe margin." },
      { type: "item", id: 13931, name: "Nightfin Soup", note: "Mana regeneration food." },
      { type: "item", id: 20748, name: "Brilliant Mana Oil", note: "Healing and mana regeneration weapon oil; check availability and budget." },
      { type: "item", id: 13511, name: "Flask of Distilled Wisdom", note: "Optional expensive mana-pool buffer." },
      { type: "item", id: 13457, name: "Greater Fire Protection Potion", note: "Encounter-dependent fire protection." },
    ] }),
    section("world-buffs", "World buffs", p("Spirit of Zandalar and Songflower Serenade offer useful stats; Rallying Cry of the Dragonslayer supplies spell crit. Warchief's Blessing can help Horde mana regeneration and health, but its melee haste does not speed healing casts. Coordinate collection when the raid uses buffs. These are mature-Era options, not claims that every buff or consumable belongs to Phase 1, and they are not mandatory readiness requirements.")),
    section("professions", "Professions", p("Tailoring supports crafted healing equipment, including the Priest-only Truefaith Vestments. Alchemy or gathering can help fund mana consumables. Engineering adds utility but explosives demand safe positioning and attention that might be needed for healing. Choose around your budget and equipment plans; a guide does not require a profession change. Cooking and First Aid remain useful secondary skills.")),
    section("gear", "Gear — Pre-Raid and Phase 1", p("These sets read the accepted Holy Priest registry used by Advice. Pre-Raid follows its mature-Era non-raid pool; Phase 1 follows its accepted source rules. Expand each slot for items and alternatives, and check acquisition and profession notes. The Power Infusion talent option does not generate a separate item list or change the shared Holy reference."), { kind: "gear", specKey: "era-priest-holy", phases: [0, 1] }),
    section("raid-preparation", "Raid preparation", list("Repair, train ranks, carry water and the correct candles for your learned prayer ranks, and agree Fortitude, Spirit and Shadow Protection coverage.", "Confirm tank/raid healing, dispels, cooldown recipients and backup assignments. Put low and high heal ranks, emergency tools and dispels on accessible bindings.", "Set raid frames to show health, range and relevant debuffs. Plan where to stand and where to move; keep line of sight to assigned targets and avoid placing yourself in danger to finish a cast."), { kind: "links", guideIds: ["era-molten-core", "era-boss-50663", "era-boss-50664"] }),
    section("mistakes", "Common mistakes", list("Using maximum-rank Flash Heal for every deficit and running dry before the dangerous phase.", "Downranking so aggressively that the heal cannot keep up, or cancelling too late.", "Healing outside your assignment while its tank dies; treating meters as the only measure of success.", "Expecting Prayer of Healing to reach another party, repeatedly overwriting Renew, or shielding a rage tank without coordination.", "Confusing magic, disease, curse and poison dispels; using later-expansion Priest abilities or assumptions.")),
  ],
};
