import type { GuideContent } from "../../../lib/guides/types.ts";
import { icy, list, p, section, source, wowhead } from "../helpers.ts";

export const marksmanship: GuideContent = {
  summary: "Prepare a level-60 Classic Era Marksmanship Hunter: plan your shots, keep your pet useful, and arrive ready for your raid assignments.",
  tags: ["Ranged", "Hunter", "Preparation"],
  sources: [
    icy("Classic Hunter overview and professions", "hunter-dps-pve-guide"),
    icy("Classic Hunter raid builds", "hunter-dps-pve-spec-builds-talents"),
    icy("Classic Hunter shot timing and cooldowns", "hunter-dps-pve-rotation-cooldowns-abilities"),
    wowhead("Classic Hunter abilities and rotation", "classes/hunter/dps-rotation-cooldowns-abilities-pve"),
    icy("Classic Hunter stats and hit", "hunter-dps-pve-stat-priority"),
    icy("Classic Hunter pet care and training", "hunter-dps-pets-guide"),
    icy("Classic Hunter consumables and buffs", "hunter-dps-pve-enchants-consumables"),
    source("Classic Hunter talent metadata", "WoWSims Classic", "https://github.com/wowsims/classic/blob/c925c1184dcd0c5eaff2d128af899be639235b63/ui/core/talents/trees/hunter.json"),
  ].map(s => ({ ...s, accessedAt: "2026-09-21" })),
  sections: [
    section("overview", "Overview", p("Marksmanship combines ranged physical damage, pet damage and Trueshot Aura for its party. This guide covers level-60 Classic Era raiding, with early-raid preparation in mind. Your Hunter uses mana; pet focus is a separate resource. Steady Shot, Kill Command and Misdirection are not part of this Era toolkit.")),
    section("strengths", "Strengths and limitations", list("Ranged pulls, kiting and Tranquilizing Shot can solve raid problems beyond damage. Trueshot Aura rewards thoughtful party placement.", "Minimum ranged distance, movement and interrupted shot timing cost damage. Pet deaths and mana shortages reduce sustained output. Plan a safe firing position before the pull rather than assuming every encounter permits uninterrupted shots.")),
    section("talents", "Talents", { kind: "talent-build", buildId: "era-marksmanship-standard", alternativeBuildIds: ["era-marksmanship-surefooted"] }, list("Standard raid Marksmanship is 20 Beast Mastery / 31 Marksmanship / 0 Survival. It combines Trueshot Aura, Aimed Shot and Mortal Shots with Unleashed Fury and Ferocity for pet damage.", "The 2/31/18 Surefooted variant trades pet investment for 3% hit and Survival utility. Use it when that hit closes a real gear shortfall; it is not a free damage gain once already capped. Both displayed allocations come from the reviewed Classic raid-build source.", "Coordinate Hunter's Mark coverage. These examples have 3/5 Improved Hunter's Mark; a designated marker may use a different allocation. Utility and creature-type slaying choices vary by assignment. The visual selections are guide recommendations, not your imported talents.")),
    section("stats", "Stats and hit", p("At 300 ranged weapon skill, plan for 9% hit against a level-63 raid boss. Surefooted contributes up to 3%, leaving 6% from gear in that example. Racial skill applies only to its matching weapon: Troll bows and Dwarf guns change the requirement. Check actual skill and equipment instead of applying one cap to every setup."), p("Agility provides ranged attack power and crit; ranged weapon damage, useful hit, attack power and crit all matter. Ranged attacks do not glance. Intellect supports your mana pool and stamina helps you survive, but neither replaces offensive stats. Compare complete loadouts; do not treat these notes as universal simulation weights.")),
    section("rotation", "Rotation / priority", list("Confirm the tank's pull, your assigned mark and pet target. Maintain Aspect of the Hawk for normal ranged damage and keep Auto Shot active from a safe distance.", "Build your stationary sequence around Auto Shot, Aimed Shot and Multi-Shot. Reserve mana and attention for assigned Tranquilizing Shots. Arcane Shot shares Aimed Shot's cooldown, so it is not a routine extra button between Aimed casts.", "Avoid automatic Serpent Sting use in a physical-shot sequence; consider mana, raid debuff policy and the encounter. Do not import later-expansion shot-spam macros.")),
    section("auto-shot", "Auto Shot timing", p("Use a shot timer and learn the rhythm of your weapon with your actual quiver and haste effects. Move between shots, then stop in time for the next firing window. Starting another action as Auto Shot becomes ready can delay it. A slower weapon often suits letting Auto Shot fire before Aimed Shot; faster or hasted timings can favor deliberate clipping. There is no single fixed sequence for every weapon speed.")),
    section("aimed-multi", "Aimed Shot and Multi-Shot", p("Aimed Shot needs a stationary casting window. Begin it after checking movement mechanics and the next shot timer, not just its cooldown. Multi-Shot is useful against one target as well as several, but its extra targets can break control or pull an unwanted pack. Hold it when the spread is unsafe. If mana is tight, a lower Multi-Shot rank can conserve resources; avoid spending everything before the encounter ends.")),
    section("pets", "Pet considerations", list("Bring a levelled, happy pet with trained ability ranks and appropriate training-point choices. Feed it suitable food and check loyalty; a neglected pet loses value even with pet talents.", "Cats offer strong personal damage; wolves offer Furious Howl utility. Choose around the encounter and reliable uptime, not appearance alone. Train relevant resistances when needed.", "Turn off Growl for tanked raid targets. Use explicit attack and follow bindings, send the pet only after control is established, and recall it from lethal effects. Dismiss before risky shortcuts if pathing might pull enemies. Revive during a safe opening; do not sacrifice your own survival to rescue it.")),
    section("cooldowns", "Cooldowns", p("Use Rapid Fire and offensive trinkets during a safe period of sustained shooting. Watch the changed shot rhythm rather than keeping an unhasted timing by habit. Feign Death is a threat-management tool that can fail; stop attacking and confirm the result before resuming. Keep mana recovery available for long fights and required utility.")),
    section("consumables", "Consumables", p("Prioritize ammunition, mana recovery and survival before expensive damage buffs. Potions share a cooldown, so reserve protection or healing when the encounter demands it. Runes trade health for mana and need a safe health margin."), { kind: "wowhead", entries: [
      { type: "item", id: 13452, name: "Elixir of the Mongoose", note: "Offensive agility and crit option." },
      { type: "item", id: 13928, name: "Grilled Squid", note: "Agility food; check cost and availability." },
      { type: "item", id: 13444, name: "Major Mana Potion", note: "Mana for sustained shots and utility." },
      { type: "item", id: 12662, name: "Demonic Rune", note: "Optional mana recovery at a health cost." },
      { type: "item", id: 13457, name: "Greater Fire Protection Potion", note: "Encounter-dependent Molten Core preparation." },
    ] }),
    section("world-buffs", "World buffs", p("Rallying Cry of the Dragonslayer and Songflower Serenade provide useful offensive bonuses; Spirit of Zandalar increases primary stats. Coordinate collection only if your raid uses these buffs. Not every melee benefit improves ranged attacks: Warchief's Blessing's melee haste does not accelerate Auto Shot. These are mature-Era options, not Phase 1 availability claims or mandatory readiness requirements.")),
    section("professions", "Professions", p("Engineering offers explosives and practical utility, with range, threat and self-damage considerations. Leatherworking can support crafted gear; gathering or Alchemy can fund consumables. Pick around your budget and equipment plans rather than changing professions just to follow a guide. Cooking supplies food and First Aid supplies useful recovery between damage events.")),
    section("gear", "Gear — Pre-Raid and Phase 1", p("These references read the same accepted Marksmanship recommendation registry as Advice. Pre-Raid uses its mature-Era non-raid pool; Phase 1 follows the accepted phase/source rules. Expand a slot for targets and alternatives. Check weapon type, ammunition, acquisition and profession requirements. Talent selection does not silently change this shared gear reference or calculate personal stat weights."), { kind: "gear", specKey: "era-hunter-marksman", phases: [0, 1] }),
    section("raid-preparation", "Raid preparation", list("Repair, train shot ranks, equip the correct arrows or bullets and bring enough for the full raid. Check your quiver or ammo pouch, pet food and pet training before travelling.", "Confirm pull, mark and Tranquilizing Shot assignments. For Magmadar, learn Tranquilizing Shot from the Lucifron drop when available and agree the rotation and backup call with the raid.", "Plan safe ranged distance, pet recalls and movement. Keep consumables and utility on accessible bindings; losing a damage cast is preferable to missing an assigned mechanic."), { kind: "links", guideIds: ["era-molten-core", "era-boss-50663", "era-boss-50664"] }),
    section("mistakes", "Common mistakes", list("Clipping shots accidentally while following a macro built for a different weapon or expansion.", "Spending mana on unnecessary shots, then missing a utility assignment.", "Taking Surefooted without accounting for gear hit, or using a racial skill bonus with the wrong weapon.", "Breaking crowd control with Multi-Shot, leaving Growl on, or letting pet pathing pull enemies.", "Standing inside minimum ranged distance or ignoring movement to finish one more Aimed Shot.")),
  ],
};
