import type { GuideContent } from "../../../lib/guides/types.ts";
import { icy, list, p, section, source, wowhead } from "../helpers.ts";

export const moltenCoreContent: GuideContent = {
  summary: "Prepare for a 40-player journey through Blackrock Mountain: controlled pulls, assigned dispels and ten progression encounters.",
  tags: ["Raid", "Preparation", "40 players"],
  sources: [icy("Molten Core raid guide — standard Classic sections", "molten-core-raid-guides"), wowhead("Molten Core raid overview", "molten-core-raid-overview-wow-classic"), source("Molten Core raid guide", "Warcraft Tavern", "https://www.warcrafttavern.com/wow-classic/guides/mc/")],
  sections: [
    section("overview", "Overview and entry", p("Molten Core is a level-60, 40-player Classic Era raid in Blackrock Mountain. The entrance lies inside Blackrock Depths. Completing Attunement to the Core gives access through Lothos Riftwaker, saving the dungeon trip.")),
    section("preparation", "Raid preparation", list("Repair and bring food, water, class reagents and recovery consumables. Confirm the meeting point and attunement before raid time.", "Arrange rune dousing before the run: the seven runes must be extinguished to summon Majordomo. Hydraxian Waterlords progression provides Aqual Quintessence; Eternal Quintessence is reusable. After Majordomo surrenders, he can summon Ragnaros.", "Assign tanks, dispellers, interrupts and crowd control by target. Bring enough coverage for simultaneous adds rather than imposing one fixed class composition.")),
    section("resistance", "Resistance and consumables", p("Fire protection is useful for dangerous fire damage, particularly Ragnaros. Tanks may trade offensive pieces for fire resistance where survival calls for it; most players do not need a raid-wide resistance uniform. Shazzrah deals Arcane damage, and several encounters also deal Shadow damage: fire resistance cannot solve every mechanic."), p("Agree your protection-potion plan with healers and leave room for recovery potions. Consumables support movement and dispels; they cannot replace them.")),
    section("assignments", "Dispels, interrupts and role preparation", list("Tanks: mark add ownership and pickup backups before pulling. Keep frontal attacks away from the group.", "Healers: cover off-tanks as well as the boss tank, and confirm range before widely separated pulls.", "DPS: know the kill target, your control assignment and when to stop attacking. Hunters with Tranquilizing Shot handle Magmadar’s Frenzy.", "Mages and Druids remove curses. Priests and Paladins can remove harmful magic; offensive dispels need appropriate Priest or Shaman coverage. Assign interrupt rotations for Sulfuron’s priests.")),
    section("trash", "Trash", p("Pull into cleared space. Face core hounds away from the raid, avoid edges around knockbacks, and handle Firelord spawns promptly. Small hound packs need coordinated kills so surviving pack members do not undo progress. Patrol awareness matters even while drinking or recovering from a boss.")),
    section("boss-order", "Boss quick reference", p("All ten encounters below belong to standard Era progression. This navigation follows the accepted encounter order; it is not a mandatory route. Groups may pull Baron Geddon before Shazzrah. No encounter is marked optional here; the rune and Majordomo requirements still govern access to Ragnaros."), { kind: "bosses", raidId: 2000 }),
    section("mistakes", "Common raid-wide mistakes", list("Pulling before add ownership and dispel coverage are clear.", "Breaking crowd control with incidental cleave or chasing into uncleared patrols.", "Spending preparation time on buffs while forgetting repairs, entry access or rune dousing."), { kind: "links", guideIds: ["era-fury"] }),
  ],
};
