import assert from "node:assert/strict";
import test from "node:test";
import { MemoryGuildRepository } from "../lib/guilds/repository.ts";
import { previewGuildCsv } from "../lib/guilds/csv.ts";
import { defaultCapabilities, hasCapability } from "../lib/guilds/permissions.ts";

const member = { characterId: "char-1", characterName: "Aidy", className: "Warrior", spec: "Fury", level: 60, race: "Orc", faction: "Horde" as const, realm: "Firemaw", region: "eu" as const, realmType: "era" as const, contentVersion: "era" as const, role: "DPS", readiness: "ready" as const };
test("guild vertical slice creates roster, raid, signup, groups and assignments", () => { const repo = new MemoryGuildRepository(); const guild = repo.createGuild("owner", { name: "Ashen Vanguard", region: "eu", realmSlug: "firemaw", realmName: "Firemaw", characterRealmType: "era", contentVersion: "era", faction: "Horde", description: "Classic Era guild" }); const saved = repo.addMember("owner", guild.id, member); const raid = repo.createRaid("owner", guild.id, { name: "Molten Core", instance: "Molten Core", startsAt: "2026-08-15T19:00", durationMinutes: 240 }); repo.setSignup("owner", guild.id, raid.id, saved.id, "confirmed"); repo.selectRoster("owner", guild.id, raid.id, [saved.id]); repo.saveGroup("owner", guild.id, raid.id, { id: "", name: "Group 1", memberCharacterIds: [saved.id] }); repo.saveAssignment("owner", guild.id, raid.id, { id: "", characterId: saved.id, label: "Onyxia whelp control" }); const workspace = repo.getWorkspace("owner", guild.id); assert.equal(workspace.roster.length, 1); assert.equal(workspace.events[0].signups[0].status, "confirmed"); assert.deepEqual(workspace.events[0].selectedCharacterIds, [saved.id]); assert.equal(workspace.events[0].groups[0].memberCharacterIds[0], saved.id); assert.equal(workspace.events[0].assignments[0].label, "Onyxia whelp control"); });
test("guild mutations enforce server-side ownership", () => { const repo = new MemoryGuildRepository(); const guild = repo.createGuild("owner", { name: "Private", region: "eu", realmSlug: "firemaw", realmName: "Firemaw", characterRealmType: "era", contentVersion: "era", faction: "Alliance", description: "" }); assert.throws(() => repo.getWorkspace("intruder", guild.id), /not authorized/i); assert.throws(() => repo.createRaid("intruder", guild.id, { name: "Raid", instance: "Molten Core", startsAt: "now", durationMinutes: 180 }), /not authorized/i); });
test("JSON guild import creates a replaceable development roster", () => { const repo = new MemoryGuildRepository(); const guild = repo.importGuild("owner", { name: "Imported", realmName: "Firemaw", realmSlug: "firemaw", faction: "Horde", roster: [member] }); assert.equal(guild.importProvider, "json"); assert.equal(repo.getWorkspace("owner", guild.id).roster[0].characterName, "Aidy"); });
test("CSV preview handles UTF-8 quoted commas and reports row errors without mutation", () => { const preview = previewGuildCsv("name,region,realm,class,level,faction,guildRank,mainName,preferredRole,notes\n\"Aïdy\",eu,Firemaw,Warrior,60,Horde,Officer,,DPS,\"Needs, review\"\nBad,xx,Firemaw,Warrior,no,Horde,,,,"); assert.equal(preview.rows[0].notes, "Needs, review"); assert.equal(preview.rows[0].name, "Aïdy"); assert.ok(preview.issues.some((issue) => issue.row === 3)); });
test("role defaults and capability overrides are centralized", () => { const owner = { id: "m", guildId: "g", userId: "u", role: "owner" as const, capabilities: [], active: true, createdAt: "", updatedAt: "" }; assert.ok(hasCapability(owner, "manage-permissions")); assert.deepEqual(defaultCapabilities("member"), []); assert.equal(hasCapability({ ...owner, role: "member", capabilities: ["manage-notes"], }, "manage-notes"), true); });
