import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";

if (!process.env.TEST_DATABASE_URL) { test("raid workflow integration requires TEST_DATABASE_URL", { skip: true }, () => {}); } else {
  process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  const { query, closePool } = await import("../lib/guilds/db.ts");
  const { PostgresGuildRepository } = await import("../lib/guilds/postgres-repository.ts");
  const { saveMemberSignup, setSignupOverride, clearSignupOverride, saveRosterState, mutateAssignment, reorderAssignments, duplicateAssignment, duplicateAssignmentSection, deleteAssignmentSection } = await import("../lib/guilds/raid-workflows.ts");
  test.after(async () => { await closePool(); });
  async function fixture(){const owner=randomUUID(),officer=randomUUID();await query("INSERT INTO users(id,email,password_hash,name) VALUES($1,$2,'x','Owner'),($3,$4,'x','Officer')",[owner,`${owner}@r`,officer,`${officer}@r`]);const repo=new PostgresGuildRepository();const guild=await repo.createGuild(owner,{name:`Raid ${owner.slice(0,6)}`,region:"eu",realmSlug:"firemaw",realmName:"Firemaw",characterRealmType:"era",contentVersion:"era",faction:"Horde",description:""});await query("INSERT INTO guild_workspace_memberships(guild_id,user_id,role,capabilities) VALUES($1,$2,'officer',$3)",[guild.id,officer,JSON.stringify(["manage-roster","manage-raid","manage-assignments","manage-signup-overrides"])]);const member=await repo.addMember(owner,guild.id,{characterId:`char-${owner}`,characterName:"Aidy",className:"Warrior",spec:"Fury",level:60,race:"Orc",faction:"Horde",realm:"Firemaw",region:"eu",realmType:"era",contentVersion:"era",role:"DPS",readiness:"ready"});const raid=await repo.createRaid(owner,guild.id,{name:"Raid",instance:"Molten Core",startsAt:"2026-08-15T19:00:00Z",durationMinutes:180});await query("INSERT INTO guild_member_links(guild_member_id,user_id,status,verification_method) VALUES($1,$2,'approved','officer-verified')",[member.id,owner]);return{owner,officer,guild,member,raid};}
  async function clean(f:any){await query("UPDATE guilds SET archived_at=now() WHERE id=$1",[f.guild.id]);await query("DELETE FROM raid_assignment_assignees WHERE assignment_id IN(SELECT id FROM raid_assignments WHERE raid_event_id=$1)",[f.raid.id]);await query("DELETE FROM raid_assignments WHERE raid_event_id=$1",[f.raid.id]);await query("DELETE FROM raid_signups WHERE raid_event_id=$1",[f.raid.id]);await query("DELETE FROM raid_roster_entries WHERE raid_event_id=$1",[f.raid.id]);await query("DELETE FROM raid_events WHERE id=$1",[f.raid.id]);await query("DELETE FROM guild_member_links WHERE guild_member_id=$1",[f.member.id]);await query("DELETE FROM audit_events WHERE guild_id=$1",[f.guild.id]);await query("DELETE FROM guild_members WHERE guild_id=$1",[f.guild.id]);await query("DELETE FROM guild_workspace_memberships WHERE guild_id=$1",[f.guild.id]);await query("DELETE FROM guilds WHERE id=$1",[f.guild.id]);await query("DELETE FROM users WHERE id=ANY($1::uuid[])",[[f.owner,f.officer]]);}
  test("member signup preserves submitted value through override and clear",async()=>{const f=await fixture();try{await saveMemberSignup({id:f.owner},f.guild.id,f.raid.id,f.member.id,"accepted","DPS","", "ready");await setSignupOverride({id:f.officer},f.guild.id,f.raid.id,f.member.id,"tentative","Officer review");let row=(await query("SELECT member_status,effective_status,override_actor_user_id FROM raid_signups WHERE raid_event_id=$1",[f.raid.id])).rows[0];assert.equal(row.member_status,"accepted");assert.equal(row.effective_status,"tentative");assert.equal(row.override_actor_user_id,f.officer);await clearSignupOverride({id:f.officer},f.guild.id,f.raid.id,f.member.id);row=(await query("SELECT member_status,effective_status,override_actor_user_id FROM raid_signups WHERE raid_event_id=$1",[f.raid.id])).rows[0];assert.equal(row.effective_status,"accepted");assert.equal(row.override_actor_user_id,null);}finally{await clean(f);}});
  test("roster groups and assignment revisions reject stale writes",async()=>{const f=await fixture();try{const version=await saveRosterState({id:f.officer},f.guild.id,f.raid.id,1,{selected:[f.member.id],benched:[],groups:{"Group 1":[f.member.id]},roles:{[f.member.id]:"DPS"}});assert.equal(version,2);await assert.rejects(()=>saveRosterState({id:f.officer},f.guild.id,f.raid.id,1,{selected:[],benched:[f.member.id],groups:{},roles:{}}),/stale|current roster/i);const assignmentVersion=await mutateAssignment({id:f.officer},f.guild.id,f.raid.id,1,"create",{id:"",characterId:f.member.id,characterIds:[f.member.id],label:"Interrupt",detail:"",category:"interrupt",section:"Molten Core",position:0});assert.equal(assignmentVersion,2);await assert.rejects(()=>mutateAssignment({id:f.officer},f.guild.id,f.raid.id,1,"edit",{id:"bad",characterId:f.member.id,label:"Changed",detail:""}),/stale assignment|current version/i);assert.equal((await query("SELECT count(*)::int AS count FROM audit_events WHERE guild_id=$1 AND action LIKE 'raid.assignment-%'",[f.guild.id])).rows[0].count,1);}finally{await clean(f);}});
  test("simultaneous first-time signups produce one valid row",async()=>{const f=await fixture();try{const results=await Promise.allSettled([saveMemberSignup({id:f.owner},f.guild.id,f.raid.id,f.member.id,"accepted","DPS","","first"),saveMemberSignup({id:f.owner},f.guild.id,f.raid.id,f.member.id,"tentative","DPS","","second")]);assert.equal((await query("SELECT count(*)::int AS count FROM raid_signups WHERE raid_event_id=$1 AND guild_member_id=$2",[f.raid.id,f.member.id])).rows[0].count,1);const row=(await query("SELECT member_status,effective_status FROM raid_signups WHERE raid_event_id=$1 AND guild_member_id=$2",[f.raid.id,f.member.id])).rows[0];assert.ok(["accepted","tentative"].includes(row.member_status));assert.equal(row.effective_status,row.member_status);assert.ok(results.some((result)=>result.status==="fulfilled"));assert.equal((await query("SELECT count(*)::int AS count FROM audit_events WHERE guild_id=$1 AND action='signup.changed'",[f.guild.id])).rows[0].count,2);}finally{await clean(f);}});
  test("concurrent member update and officer override preserve separate fields",async()=>{const f=await fixture();try{await saveMemberSignup({id:f.owner},f.guild.id,f.raid.id,f.member.id,"accepted","DPS","","initial");await Promise.all([saveMemberSignup({id:f.owner},f.guild.id,f.raid.id,f.member.id,"late","DPS","Healer","updated note"),setSignupOverride({id:f.officer},f.guild.id,f.raid.id,f.member.id,"tentative","Officer coverage")]);let row=(await query("SELECT member_status,effective_status,member_note,override_actor_user_id,override_reason FROM raid_signups WHERE raid_event_id=$1",[f.raid.id])).rows[0];assert.equal(row.member_status,"late");assert.equal(row.member_note,"updated note");assert.equal(row.effective_status,"tentative");assert.equal(row.override_actor_user_id,f.officer);assert.equal(row.override_reason,"Officer coverage");await clearSignupOverride({id:f.officer},f.guild.id,f.raid.id,f.member.id);row=(await query("SELECT effective_status FROM raid_signups WHERE raid_event_id=$1",[f.raid.id])).rows[0];assert.equal(row.effective_status,"late");}finally{await clean(f);}});
  test("assignment edit, duplicate, reorder, section duplicate, and delete are versioned",async()=>{const f=await fixture();try{await saveRosterState({id:f.officer},f.guild.id,f.raid.id,1,{selected:[f.member.id],benched:[],groups:{},roles:{}});let version=await mutateAssignment({id:f.officer},f.guild.id,f.raid.id,1,"create",{id:"",characterId:f.member.id,characterIds:[f.member.id],label:"Interrupt",detail:"Original",category:"interrupt",section:"Molten Core",position:0});let assignment=(await query("SELECT id FROM raid_assignments WHERE raid_event_id=$1",[f.raid.id])).rows[0];version=await reorderAssignments({id:f.officer},f.guild.id,f.raid.id,version,"Molten Core",assignment.id,"top");version=await mutateAssignment({id:f.officer},f.guild.id,f.raid.id,version,"edit",{id:assignment.id,characterId:f.member.id,characterIds:[f.member.id],label:"Edited",detail:"Updated",category:"interrupt",section:"Molten Core",position:0});assert.equal(version,4);const copy=await duplicateAssignment({id:f.officer},f.guild.id,f.raid.id,version,assignment.id,true);assert.equal(copy.version,5);version=await duplicateAssignmentSection({id:f.officer},f.guild.id,f.raid.id,copy.version,"Molten Core",false);assert.equal(version,6);await deleteAssignmentSection({id:f.officer},f.guild.id,f.raid.id,version,"Copy of Molten Core");assert.equal((await query("SELECT count(*)::int AS count FROM audit_events WHERE guild_id=$1 AND action IN('raid.assignment-edit','raid.assignment-reordered','raid.assignment-duplicated','raid.section-duplicated','raid.section-deleted')",[f.guild.id])).rows[0].count,5);}finally{await clean(f);}});
}
