import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
if (!process.env.TEST_DATABASE_URL) { test("Postgres workflow integration requires TEST_DATABASE_URL", { skip: true }, () => {}); } else {
  process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  const { query } = await import("../lib/guilds/db.ts");
  const { PostgresGuildRepository } = await import("../lib/guilds/postgres-repository.ts");
  const { saveRaidRoster, submitClaim, decideClaim, transferOwnership } = await import("../lib/guilds/workflows.ts");
  const { applyCsvImport } = await import("../lib/guilds/csv-apply.ts");
  const { mapPostgresError } = await import("../lib/guilds/postgres-errors.ts");
  const input = { region:"eu" as const, realmSlug:"firemaw", realmName:"Firemaw", characterRealmType:"era" as const, contentVersion:"era" as const, faction:"Horde" as const, description:"integration" };
  async function fixture() { const owner=randomUUID(), officer=randomUUID(), outsider=randomUUID(); await query("INSERT INTO users(id,email,password_hash,name) VALUES($1,$2,'x','Owner'),($3,$4,'x','Officer'),($5,$6,'x','Outsider')",[owner,`${owner}@i`,officer,`${officer}@i`,outsider,`${outsider}@i`]); const repo=new PostgresGuildRepository(); const guild=await repo.createGuild(owner,{...input,name:`Guild ${owner.slice(0,6)}`}); await query("INSERT INTO guild_workspace_memberships(guild_id,user_id,role,capabilities) VALUES($1,$2,'officer',$3)",[guild.id,officer,JSON.stringify(["import-roster","manage-roster","manage-raid","manage-assignments","manage-signup-overrides"])]); return {owner,officer,outsider,guild,repo}; }
  async function clean(f:any) { await query("DELETE FROM guild_member_links WHERE guild_member_id IN (SELECT id FROM guild_members WHERE guild_id=$1)",[f.guild.id]); await query("DELETE FROM raid_assignment_assignees WHERE assignment_id IN (SELECT id FROM raid_assignments WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1))",[f.guild.id]); await query("DELETE FROM raid_assignments WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1)",[f.guild.id]); await query("DELETE FROM raid_signups WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1)",[f.guild.id]); await query("DELETE FROM raid_roster_entries WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1)",[f.guild.id]); await query("DELETE FROM raid_events WHERE guild_id=$1",[f.guild.id]); await query("DELETE FROM audit_events WHERE guild_id=$1",[f.guild.id]); await query("DELETE FROM guild_members WHERE guild_id=$1",[f.guild.id]); await query("DELETE FROM guild_workspace_memberships WHERE guild_id=$1",[f.guild.id]); await query("DELETE FROM guilds WHERE id=$1",[f.guild.id]); await query("DELETE FROM users WHERE id IN($1,$2,$3)",[f.owner,f.officer,f.outsider]); }
  test("transactional CSV import persists and marks absent members inactive", async()=>{const f=await fixture(); try { const csv="name,region,realm,class,level,faction,guildRank,mainName,preferredRole,notes\nAïdy,eu,Firemaw,Warrior,60,Horde,Officer,,DPS,\nOld,eu,Firemaw,Rogue,60,Horde,Member,,DPS,"; await applyCsvImport({id:f.officer},f.guild.id,csv,"mark-inactive"); const second="name,region,realm,class,level,faction,guildRank,mainName,preferredRole,notes\nAïdy,eu,Firemaw,Warrior,60,Horde,Officer,,DPS,"; const result=await applyCsvImport({id:f.officer},f.guild.id,second,"mark-inactive"); assert.equal(result.markedInactive,1); assert.equal((await query("SELECT count(*)::int AS count FROM guild_members WHERE guild_id=$1 AND active=false",[f.guild.id])).rows[0].count,1); assert.ok((await query("SELECT 1 FROM audit_events WHERE guild_id=$1 AND action='roster.import-applied'",[f.guild.id])).rows[0]); } finally {await clean(f);}});
  test("ownership transfer makes old owner officer and rejects officer transfer", async()=>{const f=await fixture(); try { await transferOwnership({id:f.owner},f.guild.id,f.officer,`TRANSFER ${f.guild.id}`); const roles=await query("SELECT user_id,role FROM guild_workspace_memberships WHERE guild_id=$1 ORDER BY user_id",[f.guild.id]); assert.ok(roles.rows.some((r)=>r.user_id===f.officer&&r.role==='owner')); assert.ok(roles.rows.some((r)=>r.user_id===f.owner&&r.role==='officer')); await assert.rejects(()=>transferOwnership({id:f.owner},f.guild.id,f.officer,`TRANSFER ${f.guild.id}`),/permission|owner/i); } finally {await clean(f);}});
  test("claims approve, reject and revoke with officer verification", async()=>{const f=await fixture(); try { const member=await f.repo.addMember(f.owner,f.guild.id,{characterId:`c-${f.owner}`,characterName:"Claimed",className:"Warrior",spec:"Fury",level:60,race:"Orc",faction:"Horde",realm:"Firemaw",region:"eu",realmType:"era",contentVersion:"era",role:"DPS",readiness:"unknown"}); const claim=await submitClaim({id:f.owner},f.guild.id,member.id); await decideClaim({id:f.officer},f.guild.id,claim,"approved","checked roster"); assert.equal((await query("SELECT status,verification_method FROM guild_member_links WHERE id=$1",[claim])).rows[0].status,"approved"); await decideClaim({id:f.officer},f.guild.id,claim,"revoked","ownership changed"); assert.equal((await query("SELECT status FROM guild_member_links WHERE id=$1",[claim])).rows[0].status,"revoked"); } finally {await clean(f);}});
  test("stale roster version is rejected and raw database errors are hidden", async()=>{const f=await fixture(); try { const member=await f.repo.addMember(f.owner,f.guild.id,{characterId:`c-${f.owner}`,characterName:"Roster",className:"Warrior",spec:"Fury",level:60,race:"Orc",faction:"Horde",realm:"Firemaw",region:"eu",realmType:"era",contentVersion:"era",role:"DPS",readiness:"ready"}); const raid=await f.repo.createRaid(f.officer,f.guild.id,{name:"Raid",instance:"Molten Core",startsAt:"2026-08-15T19:00:00Z",durationMinutes:180}); await saveRaidRoster({id:f.officer},f.guild.id,raid.id,1,[member.id],[]); await assert.rejects(()=>saveRaidRoster({id:f.officer},f.guild.id,raid.id,1,[],[member.id]),/stale|current version/i); const mapped=mapPostgresError({code:"23503",detail:"secret table/connection details"}); assert.equal(mapped.message,"The referenced guild record does not belong to this operation."); assert.doesNotMatch(mapped.message,/secret|table|connection/i); } finally {await clean(f);}});
}
