import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";

if (!process.env.TEST_DATABASE_URL) {
  test("Postgres workflow integration requires TEST_DATABASE_URL", { skip: true }, () => {});
} else {
  process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  const { query, closePool } = await import("../lib/guilds/db.ts");
  test.after(async () => { await closePool(); });
  const { PostgresGuildRepository } = await import("../lib/guilds/postgres-repository.ts");
  const { saveRaidRoster, submitClaim, decideClaim, transferOwnership } = await import("../lib/guilds/workflows.ts");
  const { changeRole, deactivateMember, leaveGuild } = await import("../lib/guilds/security.ts");
  const { applyCsvImport } = await import("../lib/guilds/csv-apply.ts");
  const { mapPostgresError } = await import("../lib/guilds/postgres-errors.ts");
  const input = { region: "eu" as const, realmSlug: "firemaw", realmName: "Firemaw", characterRealmType: "era" as const, contentVersion: "era" as const, faction: "Horde" as const, description: "integration" };
  async function fixture() {
    const owner = randomUUID(), officer = randomUUID(), outsider = randomUUID(), target = randomUUID();
    await query("INSERT INTO users(id,email,password_hash,name) VALUES($1,$2,'x','Owner'),($3,$4,'x','Officer'),($5,$6,'x','Outsider'),($7,$8,'x','Target')", [owner, `${owner}@i`, officer, `${officer}@i`, outsider, `${outsider}@i`, target, `${target}@i`]);
    const repo = new PostgresGuildRepository();
    const guild = await repo.createGuild(owner, { ...input, name: `Guild ${owner.slice(0, 6)}` });
    await query("INSERT INTO guild_workspace_memberships(guild_id,user_id,role,capabilities) VALUES($1,$2,'officer',$3),($1,$4,'member','[]')", [guild.id, officer, JSON.stringify(["import-roster", "manage-roster", "manage-raid", "manage-assignments", "manage-signup-overrides", "manage-permissions"]), target]);
    return { owner, officer, outsider, target, guild, repo };
  }
  async function clean(f: any) {
    await query("UPDATE guilds SET archived_at=now() WHERE id=$1", [f.guild.id]);
    await query("DELETE FROM guild_member_links WHERE guild_member_id IN (SELECT id FROM guild_members WHERE guild_id=$1)", [f.guild.id]);
    await query("DELETE FROM raid_assignment_assignees WHERE assignment_id IN (SELECT id FROM raid_assignments WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1))", [f.guild.id]);
    await query("DELETE FROM raid_assignments WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1)", [f.guild.id]);
    await query("DELETE FROM raid_signups WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1)", [f.guild.id]);
    await query("DELETE FROM raid_roster_entries WHERE raid_event_id IN (SELECT id FROM raid_events WHERE guild_id=$1)", [f.guild.id]);
    await query("DELETE FROM raid_events WHERE guild_id=$1", [f.guild.id]);
    await query("DELETE FROM audit_events WHERE guild_id=$1", [f.guild.id]);
    await query("DELETE FROM guild_members WHERE guild_id=$1", [f.guild.id]);
    await query("DELETE FROM guild_workspace_memberships WHERE guild_id=$1", [f.guild.id]);
    await query("DELETE FROM guilds WHERE id=$1", [f.guild.id]);
    await query("DELETE FROM users WHERE id IN($1,$2,$3,$4)", [f.owner, f.officer, f.outsider, f.target]);
  }
  test("transactional CSV import persists and marks absent members inactive", async () => { const f = await fixture(); try { const csv = "name,region,realm,class,level,faction,guildRank,mainName,preferredRole,notes\nAïdy,eu,Firemaw,Warrior,60,Horde,Officer,,DPS,\nOld,eu,Firemaw,Rogue,60,Horde,Member,,DPS,"; await applyCsvImport({ id: f.officer }, f.guild.id, csv, "mark-inactive"); const result = await applyCsvImport({ id: f.officer }, f.guild.id, "name,region,realm,class,level,faction,guildRank,mainName,preferredRole,notes\nAïdy,eu,Firemaw,Warrior,60,Horde,Officer,,DPS,", "mark-inactive"); assert.equal(result.markedInactive, 1); } finally { await clean(f); } });
  test("ownership transfer makes old owner officer and rejects officer transfer", async () => { const f = await fixture(); try { await transferOwnership({ id: f.owner }, f.guild.id, f.officer, `TRANSFER ${f.guild.id}`); const roles = await query("SELECT user_id,role FROM guild_workspace_memberships WHERE guild_id=$1", [f.guild.id]); assert.ok(roles.rows.some((r) => r.user_id === f.officer && r.role === "owner")); assert.ok(roles.rows.some((r) => r.user_id === f.owner && r.role === "officer")); await assert.rejects(() => transferOwnership({ id: f.owner }, f.guild.id, f.officer, `TRANSFER ${f.guild.id}`), /permission|owner/i); } finally { await clean(f); } });
  test("claims approve and revoke with officer verification", async () => { const f = await fixture(); try { const member = await f.repo.addMember(f.owner, f.guild.id, { characterId: `c-${f.owner}`, characterName: "Claimed", className: "Warrior", spec: "Fury", level: 60, race: "Orc", faction: "Horde", realm: "Firemaw", region: "eu", realmType: "era", contentVersion: "era", role: "DPS", readiness: "unknown" }); const claim = await submitClaim({ id: f.owner }, f.guild.id, member.id); await decideClaim({ id: f.officer }, f.guild.id, claim, "approved", "checked roster"); await decideClaim({ id: f.officer }, f.guild.id, claim, "revoked", "ownership changed"); assert.equal((await query("SELECT status FROM guild_member_links WHERE id=$1", [claim])).rows[0].status, "revoked"); } finally { await clean(f); } });
  test("stale roster version is rejected and raw database errors are hidden", async () => { const f = await fixture(); try { const member = await f.repo.addMember(f.owner, f.guild.id, { characterId: `c-${f.owner}`, characterName: "Roster", className: "Warrior", spec: "Fury", level: 60, race: "Orc", faction: "Horde", realm: "Firemaw", region: "eu", realmType: "era", contentVersion: "era", role: "DPS", readiness: "ready" }); const raid = await f.repo.createRaid(f.officer, f.guild.id, { name: "Raid", instance: "Molten Core", startsAt: "2026-08-15T19:00:00Z", durationMinutes: 180 }); await saveRaidRoster({ id: f.officer }, f.guild.id, raid.id, 1, [member.id], []); await assert.rejects(() => saveRaidRoster({ id: f.officer }, f.guild.id, raid.id, 1, [], [member.id]), /stale|current version/i); const mapped = mapPostgresError({ code: "23503", detail: "secret table/connection details" }); assert.equal(mapped.message, "The referenced guild record does not belong to this operation."); assert.doesNotMatch(mapped.message, /secret|table|connection/i); } finally { await clean(f); } });
  test("database rejects a second active owner safely", async () => { const f = await fixture(); try { await assert.rejects(() => query("UPDATE guild_workspace_memberships SET role='owner' WHERE guild_id=$1 AND user_id=$2", [f.guild.id, f.target]), (error: any) => { const mapped = mapPostgresError(error); assert.equal(mapped.code, "CONFLICT"); assert.doesNotMatch(mapped.message, /constraint|23505|table/i); return true; }); } finally { await clean(f); } });
  test("final owner cannot be deactivated, demoted, or leave", async () => { const f = await fixture(); try { await assert.rejects(() => deactivateMember({ id: f.owner }, f.guild.id, f.owner), /final owner|transfer ownership/i); await assert.rejects(() => changeRole({ id: f.owner }, f.guild.id, f.owner, "member"), /transfer ownership/i); await assert.rejects(() => leaveGuild({ id: f.owner }, f.guild.id), /final owner|transfer ownership/i); assert.equal((await query("SELECT owner_user_id FROM guilds WHERE id=$1", [f.guild.id])).rows[0].owner_user_id, f.owner); } finally { await clean(f); } });
  test("inactive, cross-guild, and officer ownership targets are rejected", async () => { const f = await fixture(); try { await assert.rejects(() => transferOwnership({ id: f.officer }, f.guild.id, f.target, `TRANSFER ${f.guild.id}`), /owner|permission/i); await query("UPDATE guild_workspace_memberships SET active=false WHERE guild_id=$1 AND user_id=$2", [f.guild.id, f.target]); await assert.rejects(() => transferOwnership({ id: f.owner }, f.guild.id, f.target, `TRANSFER ${f.guild.id}`), /active target|membership|owner/i); await assert.rejects(() => transferOwnership({ id: f.owner }, f.guild.id, f.outsider, `TRANSFER ${f.guild.id}`), /active target|membership|owner/i); } finally { await clean(f); } });
  test("concurrent ownership transfers serialize to exactly one success", async () => { const f = await fixture(); try { const results = await Promise.allSettled([transferOwnership({ id: f.owner }, f.guild.id, f.officer, `TRANSFER ${f.guild.id}`), transferOwnership({ id: f.owner }, f.guild.id, f.target, `TRANSFER ${f.guild.id}`)]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); assert.equal((await query("SELECT count(*)::int AS count FROM guild_workspace_memberships WHERE guild_id=$1 AND role='owner' AND active=true", [f.guild.id])).rows[0].count, 1); assert.equal((await query("SELECT count(*)::int AS count FROM audit_events WHERE guild_id=$1 AND action='guild.ownership-transferred'", [f.guild.id])).rows[0].count, 1); } finally { await clean(f); } });
  test("failed transfer writes no successful transfer audit", async () => { const f = await fixture(); try { await assert.rejects(() => transferOwnership({ id: f.owner }, f.guild.id, f.outsider, `TRANSFER ${f.guild.id}`), /active target|membership|owner/i); assert.equal((await query("SELECT count(*)::int AS count FROM audit_events WHERE guild_id=$1 AND action='guild.ownership-transferred'", [f.guild.id])).rows[0].count, 0); } finally { await clean(f); } });
  test("mapped PostgreSQL categories never expose technical details", () => { for (const code of ["23503", "23514", "23502", "40001", "40P01", "57P01", "08006", "99999"]) { const error = mapPostgresError({ code, constraint: "secret_table_constraint", detail: "postgres://secret-host/db SQL stack trace" }); assert.ok(["CROSS_GUILD_REFERENCE", "CONFLICT", "UNAVAILABLE"].includes(error.code)); assert.doesNotMatch(error.message, /secret|postgres|SQL|stack|constraint|table|host/i); } });
}
