import Link from "next/link";
import { notFound } from "next/navigation";
import { VersionShell } from "../../../components/version-shell";
import { isContentVersion } from "../../../lib/game-data";
import { requireAuthenticatedUser } from "../../../lib/auth";
import { savedCharacterRepository } from "../../../lib/characters/saved-repository";
import { characterSyncRepository } from "../../../lib/characters/sync-repository";
import { refreshCharacterAction } from "../../../lib/characters/sync-actions";
import type { ContentVersion } from "../../../lib/types";

export default async function ProfilePage({ params }: { params: Promise<{ version: string }> }) {
  const { version: raw } = await params; if (!isContentVersion(raw)) notFound(); const version = raw as ContentVersion; const user = await requireAuthenticatedUser(); const characters = await savedCharacterRepository.listSavedCharacters(user.id); const primary = characters.find((character) => character.isPrimary); const sync = primary ? await characterSyncRepository.getLatestSuccessful(primary.id) : undefined; const history = primary ? await characterSyncRepository.getHistory(primary.id, 5) : [];
  return <VersionShell version={version}><main className="mx-auto min-h-[calc(100vh-148px)] max-w-[900px] px-5 py-12 lg:px-8 lg:py-16"><div className="eyebrow">Account</div><h1 className="display mt-3 text-5xl">Your PrePull profile.</h1><section className="panel mt-10 rounded-2xl p-6"><dl className="grid gap-5 text-sm sm:grid-cols-2"><div><dt className="text-xs text-[var(--muted)]">Name</dt><dd className="mt-1 font-semibold">{user.displayName}</dd></div><div><dt className="text-xs text-[var(--muted)]">Saved characters</dt><dd className="mt-1 font-semibold">{characters.length}</dd></div></dl></section>{primary && <><section className="panel mt-5 rounded-2xl p-6"><div className="eyebrow">Primary character</div><h2 className="display mt-2 text-3xl">{primary.characterName}</h2><p className="mt-2 text-sm text-[var(--muted)]">{primary.className} · {primary.realmName} · {primary.characterRealmType}</p><p className="mt-3 text-sm text-[var(--muted)]">{sync ? `Last refreshed ${new Date(sync.syncedAt).toLocaleString()}.` : "Never refreshed. Current equipment is not yet stored."}</p><form action={refreshCharacterAction}><input type="hidden" name="characterId" value={primary.id} /><button className="button-primary mt-5" type="submit">Refresh character</button></form></section>{sync && <section className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="panel rounded-2xl p-6"><div className="eyebrow">Current equipment</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{sync.equipment.map((item) => <div className="rounded-lg border border-[var(--line)] p-3" key={item.slot}><p className="text-[10px] uppercase tracking-widest text-[var(--muted)]">{item.slot}</p><p className="mt-1 text-sm font-semibold">{item.name}</p><p className="mt-1 text-xs text-[var(--muted)]">Item {item.itemId || "empty"}</p></div>)}</div></article><article className="panel rounded-2xl p-6"><div className="eyebrow">Recent updates</div><div className="mt-4 space-y-3">{history.map((entry, index) => <div className="border-l-2 border-[var(--line)] pl-3" key={entry.id}><p className="text-sm font-semibold">{entry.status === "success" ? `${entry.equipment.length ? entry.equipment.length : 0} gear slots recorded` : "Refresh failed"}</p><p className="mt-1 text-xs text-[var(--muted)]">{new Date(entry.syncedAt).toLocaleString()}</p>{index === history.length - 1 && <p className="mt-1 text-xs text-[var(--muted)]">Baseline</p>}</div>)}</div></article></section>}</>}</main></VersionShell>;
}
