import type { CharacterSource, ContentVersion, EquipmentSlot, Faction } from "../types.ts";
import type { CuratedReferenceProfile, ReferenceContext, ReferenceGearSet, ReferenceItemEntry, ReferenceProvenance, ReferenceRecommendationTier, ReferenceVerificationStatus } from "./types.ts";
import { eraFuryCandidates } from "../gear-analysis/dataset.ts";

export const authoringHeaders = ["contentVersion", "class", "spec", "role", "phase", "context", "setId", "slot", "itemId", "tier", "rank", "sourceType", "sourceName", "activity", "boss", "faction", "race", "profession", "notes", "provenanceId", "verificationStatus"] as const;
export type AuthoringHeader = typeof authoringHeaders[number];
export type AuthoringRow = Record<AuthoringHeader, string>;
export type CuratedProvenanceRecord = { id: string; title: string; sourceType: string; sourceName: string; sourceUrl?: string; author?: string; reviewedAt: string; reviewer?: string; notes?: string };
export const provenanceRegistry: Record<string, CuratedProvenanceRecord> = {
  "prepull-curated-2026-08": { id: "prepull-curated-2026-08", title: "PrePull curated Classic Era reference dataset", sourceType: "internal-review", sourceName: "PrePull data review", reviewedAt: "2026-08-12", reviewer: "PrePull data review", notes: "Structured conclusions only; no numerical DPS claim." },
};
export const validPhases = new Set(["pre-raid", "phase-1", "phase-2", "phase-3", "phase-4", "phase-5", "phase-6"]);
export const phaseNumber = (value: string) => value === "pre-raid" ? 0 : Number(value.replace("phase-", ""));
export const phaseLabel = (value: number) => value === 0 ? "pre-raid" : `phase-${value}`;
export const validTiers = new Set<ReferenceRecommendationTier>(["bis", "excellent", "strong", "alternative", "entry"]);
export const validContexts = new Set<ReferenceContext>(["general", "balanced", "threat", "mitigation", "resistance", "fire-resistance", "nature-resistance", "frost-resistance", "throughput", "sustain"]);
export const validSlots = new Set<EquipmentSlot>(["Head", "Neck", "Shoulder", "Back", "Chest", "Wrist", "Hands", "Waist", "Legs", "Feet", "Finger 1", "Finger 2", "Trinket 1", "Trinket 2", "Main Hand", "Off Hand / Shield", "Ranged / Relic"]);
export const validSourceTypes = new Set(["dungeon", "raid", "quest", "crafted", "reputation", "vendor", "world-drop", "pvp", "profession", "other"]);
const sourceTypeMap: Record<string, CharacterSource["type"]> = { dungeon: "Dungeon", raid: "Raid", quest: "Quest", crafted: "Profession", reputation: "Reputation", vendor: "Vendor", "world-drop": "World Drop", pvp: "PvP", profession: "Profession", other: "Vendor" };
const value = (row: AuthoringRow, key: AuthoringHeader) => row[key]?.trim() ?? "";
export function parseCsv(input: string): string[][] { const records: string[][] = []; let record: string[] = [], field = "", quoted = false; for (let i = 0; i < input.length; i += 1) { const char = input[i]; const next = input[i + 1]; if (char === '"' && quoted && next === '"') { field += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { record.push(field); field = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && next === "\n") i += 1; record.push(field); if (record.some((cell) => cell.length > 0)) records.push(record); record = []; field = ""; } else field += char; } if (quoted) throw new Error("CSV contains an unterminated quoted field."); if (field.length || record.length) { record.push(field); records.push(record); } return records; }
export function parseAuthoringCsv(input: string): { rows: AuthoringRow[]; errors: string[] } { let records: string[][]; try { records = parseCsv(input); } catch (error) { return { rows: [], errors: [error instanceof Error ? error.message : "Invalid CSV"] }; } if (!records.length) return { rows: [], errors: ["CSV is empty."] }; const headers = records[0].map((header) => header.trim()); const errors: string[] = []; for (const header of authoringHeaders) if (!headers.includes(header)) errors.push(`Missing required column: ${header}`); for (const header of headers) if (!authoringHeaders.includes(header as AuthoringHeader)) errors.push(`Unknown column: ${header}`); if (errors.length) return { rows: [], errors }; const rows = records.slice(1).map((cells) => Object.fromEntries(authoringHeaders.map((header) => [header, cells[headers.indexOf(header)] ?? ""])) as AuthoringRow); return { rows, errors };
}
export function rowToEntry(row: AuthoringRow, provenance: CuratedProvenanceRecord): ReferenceItemEntry { const itemId = Number(value(row, "itemId")); const item = eraFuryCandidates.find((candidate) => candidate.itemId === itemId); const sourceType = sourceTypeMap[value(row, "sourceType")] ?? "Vendor"; const source: CharacterSource = { type: sourceType, ...(value(row, "sourceName") ? { instance: value(row, "sourceName") } : {}), ...(value(row, "boss") ? { boss: value(row, "boss") } : {}), ...(value(row, "profession") ? { profession: value(row, "profession") } : {}) }; const factionSources = itemId === 13959 ? { Alliance: "Maxwell's Mission", Horde: "Warlord's Command" } : itemId === 13965 ? { Alliance: "General Drakkisath's Demise", Horde: "For The Horde!" } : undefined; const craftedByProfession = sourceType === "Profession" ? value(row, "profession") || source.profession : undefined; const requiresRaidContent = sourceType === "Raid"; const setBonusGroup = [16984, 15050, 15051, 15052].includes(itemId) ? "black-dragon-mail" : undefined; const setBonusEffects = setBonusGroup ? ["2-piece: +1% hit", "3-piece: +2% critical strike"] : undefined; const uniqueIds = new Set([19325, 21182, 13098, 18500, 17713, 2246, 12548, 13217]); const uniqueGroup = uniqueIds.has(itemId) ? `unique:${itemId}` : item?.uniqueGroup; const parsedRank = Number(value(row, "rank")); return { itemId, slot: value(row, "slot") as EquipmentSlot, tier: value(row, "tier") as ReferenceRecommendationTier, ...(Number.isInteger(parsedRank) && parsedRank > 0 ? { rank: parsedRank } : {}), phase: phaseNumber(value(row, "phase")), source, ...(value(row, "setId") ? { setId: value(row, "setId") } : {}), ...(setBonusGroup ? { setBonusGroup, setBonusEffects } : {}), ...(value(row, "faction") ? { faction: value(row, "faction") as Faction } : {}), ...(factionSources ? { factionSources } : {}), ...(value(row, "race") ? { raceNotes: value(row, "race") } : {}), ...(craftedByProfession ? { craftedByProfession } : {}), ...(uniqueGroup ? { uniqueGroup } : {}), ...(value(row, "notes") ? { notes: value(row, "notes") } : {}), ...(requiresRaidContent ? { requiresRaidContent } : {}), provenanceId: value(row, "provenanceId"), provenance: { source: provenance.sourceName, reviewedAt: provenance.reviewedAt, reviewedBy: provenance.reviewer ?? provenance.author ?? "Unassigned", verificationStatus: value(row, "verificationStatus") as ReferenceVerificationStatus, notes: provenance.notes } };
}
export function profileForRows(rows: AuthoringRow[], profiles: CuratedReferenceProfile[]): CuratedReferenceProfile | undefined { const first = rows[0]; return profiles.find((profile) => profile.contentVersion === value(first, "contentVersion") && profile.className.toLowerCase() === value(first, "class").toLowerCase() && profile.specialization.toLowerCase() === value(first, "spec").toLowerCase()); }
export function rowsToSets(rows: AuthoringRow[], profiles: CuratedReferenceProfile[]): { sets: ReferenceGearSet[]; errors: string[] } { const errors: string[] = []; const groups = new Map<string, { rows: AuthoringRow[]; profile?: CuratedReferenceProfile }>(); for (const row of rows) { const key = `${value(row, "contentVersion")}:${value(row, "class").toLowerCase()}:${value(row, "spec").toLowerCase()}:${value(row, "setId")}:${value(row, "context")}:${value(row, "phase")}`; const group = groups.get(key) ?? { rows: [], profile: profileForRows([row], profiles) }; group.rows.push(row); groups.set(key, group); } const sets: ReferenceGearSet[] = []; for (const [key, group] of groups) { const [contentVersion, className, specialization, setId, context, phaseText] = key.split(":"); const provenanceId = value(group.rows[0], "provenanceId"); const provenance = provenanceRegistry[provenanceId]; if (!provenance) { errors.push(`${setId}: unknown provenance ID ${provenanceId || "(blank)"}.`); continue; } const slots: Partial<Record<EquipmentSlot, ReferenceItemEntry[]>> = {}; for (const row of group.rows) { const entry = rowToEntry(row, provenance); (slots[entry.slot] ??= []).push(entry); } sets.push({ id: setId, contentVersion: contentVersion as ContentVersion, className, specialization, role: value(group.rows[0], "role"), phase: phaseNumber(phaseText), name: `${className} ${specialization} ${phaseText} ${context}`, context: context as ReferenceContext, description: "Imported curated reference data.", methodology: "Curated reference", sourceProvenance: { source: provenance.sourceName, reviewedAt: provenance.reviewedAt, reviewedBy: provenance.reviewer ?? "Unassigned", verificationStatus: value(group.rows[0], "verificationStatus") as ReferenceVerificationStatus, notes: provenance.notes }, complete: false, status: "draft", slots }); } return { sets, errors }; }
export function csvEscape(value: unknown): string { const text = String(value ?? ""); return /[",\n\r]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
export function rowsToCsv(rows: AuthoringRow[]): string { return `${authoringHeaders.join(",")}\n${rows.map((row) => authoringHeaders.map((header) => csvEscape(row[header])).join(",")).join("\n")}\n`; }
export function setToRows(set: ReferenceGearSet, provenanceId = "prepull-curated-2026-08"): AuthoringRow[] { return Object.values(set.slots).flatMap((entries) => (entries ?? []).map((entry) => ({ contentVersion: set.contentVersion, class: set.className.toLowerCase(), spec: set.specialization.toLowerCase(), role: set.role, phase: phaseLabel(set.phase), context: entry.context ?? set.context, setId: set.id, slot: entry.slot, itemId: String(entry.itemId), tier: entry.tier, rank: "", sourceType: entry.source.type.toLowerCase().replace(" ", "-"), sourceName: entry.source.instance ?? entry.source.zone ?? entry.source.quest ?? entry.source.profession ?? "", activity: entry.source.instance ?? entry.source.zone ?? "", boss: entry.source.boss ?? "", faction: entry.faction ?? "", race: entry.raceNotes ?? "", profession: entry.professionRequirements?.join(";") ?? "", notes: entry.notes ?? "", provenanceId: entry.provenanceId ?? provenanceId, verificationStatus: entry.provenance.verificationStatus }))); }
