export type CandidateDisposition = "strong-add" | "conditional-add" | "redundant" | "raid-origin" | "needs-review";
export type MatureCandidate = { item: string; itemId?: number; slot: string; source: string; sourceContentType: "crafted" | "quest" | "reputation" | "world-drop" | "silithus" | "pvp" | "raid" | "unknown"; raidOrigin: boolean; requiresRaidParticipation: boolean; tradeable: boolean; faction: string; raceContext: string; professionContext: string; setDependency: string; accessibility: string; whyFuryCares: string; equivalent: boolean; disposition: CandidateDisposition; proposedTier?: string; proposedPosition?: string; ultimateTarget?: boolean; realisticTarget?: boolean; evidence: string[] };

export const matureFuryCandidates: MatureCandidate[] = [
  { item: "Titanic Leggings", itemId: 22385, slot: "Legs", source: "Blacksmithing 300; Plans: Titanic Leggings world drop", sourceContentType: "crafted", raidOrigin: false, requiresRaidParticipation: false, tradeable: true, faction: "Both", raceContext: "None", professionContext: "Crafted by Blacksmithing; character need not know Blacksmithing", setDependency: "None", accessibility: "Very expensive materials and rare recipe; not a normal tonight farm", whyFuryCares: "High offensive stats and mature-Era availability", equivalent: false, disposition: "conditional-add", proposedTier: "excellent", proposedPosition: "Above or alongside Cloudkeeper; requires loadout review", ultimateTarget: true, realisticTarget: false, evidence: ["https://wowpedia.fandom.com/wiki/Titanic_Leggings", "https://warcraft.wiki.gg/wiki/Plans:_Titanic_Leggings"] },
  { item: "Diamond Flask", itemId: 20130, slot: "Trinket", source: "Warrior class quest: Voodoo Feathers", sourceContentType: "quest", raidOrigin: false, requiresRaidParticipation: false, tradeable: false, faction: "Both", raceContext: "Warrior-only", professionContext: "None", setDependency: "None", accessibility: "Class quest through Sunken Temple; choice is permanent/contextual", whyFuryCares: "On-use +75 Strength for 1 minute with a 6-minute cooldown", equivalent: false, disposition: "strong-add", proposedTier: "bis", proposedPosition: "Paired trinket context; not a universal replacement for every encounter", ultimateTarget: true, realisticTarget: true, evidence: ["https://warcraft.wiki.gg/wiki/Diamond_Flask", "https://worldofwarcraft.blizzard.com/news/23302789/wow-classic-class-quests-and-new-reputation-rewards"] },
  { item: "Darkmoon Card: Maelstrom", itemId: 19289, slot: "Trinket", source: "Darkmoon Faire / Darkmoon Prize", sourceContentType: "quest", raidOrigin: false, requiresRaidParticipation: false, tradeable: true, faction: "Both", raceContext: "None", professionContext: "None", setDependency: "None", accessibility: "Long/expensive card acquisition", whyFuryCares: "Proc trinket may be relevant but requires effect/context review", equivalent: false, disposition: "needs-review", proposedTier: "strong", proposedPosition: "Needs effect validation", ultimateTarget: false, realisticTarget: false, evidence: ["https://www.wowhead.com/classic/item=19289/darkmoon-card-maelstrom"] },
  { item: "Don Julio's Band", itemId: 19325, slot: "Finger", source: "Alterac Valley reputation vendor", sourceContentType: "pvp", raidOrigin: false, requiresRaidParticipation: false, tradeable: false, faction: "Both; faction-specific AV vendor", raceContext: "None", professionContext: "None", setDependency: "Unique-Equipped", accessibility: "Alterac Valley reputation commitment, not a dungeon farm", whyFuryCares: "Strong melee stats and hit/crit value", equivalent: false, disposition: "conditional-add", proposedTier: "excellent", proposedPosition: "Ring pool after reputation/accessibility review", ultimateTarget: true, realisticTarget: true, evidence: ["https://warcraft.wiki.gg/wiki/Don_Julio%27s_Band"] },
  { item: "Band of Earthen Might", itemId: 21182, slot: "Finger", source: "Cenarion Circle / Silithus reputation", sourceContentType: "silithus", raidOrigin: false, requiresRaidParticipation: false, tradeable: false, faction: "Both", raceContext: "None", professionContext: "None", setDependency: "None", accessibility: "Reputation and assignment grind", whyFuryCares: "Melee offensive stats; conservative contextual ring option", equivalent: false, disposition: "conditional-add", proposedTier: "strong", proposedPosition: "Ring pool after reputation/accessibility review", ultimateTarget: false, realisticTarget: true, evidence: ["https://www.wowhead.com/classic/item=21182/band-of-earthen-might"] },
  { item: "Black Dragonscale Boots", itemId: 16984, slot: "Feet", source: "Dragonscale Leatherworking; Fiery Core and Lava Core dependency", sourceContentType: "crafted", raidOrigin: true, requiresRaidParticipation: false, tradeable: true, faction: "Both", raceContext: "None", professionContext: "Crafted by Dragonscale Leatherworking", setDependency: "Black Dragon Mail set", accessibility: "Raid-origin materials", whyFuryCares: "Set piece is excluded from the mature non-raid reference set because its material chain begins in Molten Core", equivalent: false, disposition: "raid-origin", proposedPosition: "Do not import into mature Pre-Raid", ultimateTarget: false, realisticTarget: false, evidence: ["https://www.wowhead.com/classic/item=16984/black-dragonscale-boots"] },
  { item: "Earthstrike", itemId: 21180, slot: "Trinket", source: "Cenarion Circle / Silithus reputation", sourceContentType: "silithus", raidOrigin: false, requiresRaidParticipation: false, tradeable: false, faction: "Both", raceContext: "None", professionContext: "None", setDependency: "None", accessibility: "Substantial reputation/assignment grind", whyFuryCares: "Powerful on-use offensive trinket", equivalent: false, disposition: "conditional-add", proposedTier: "excellent", proposedPosition: "Paired trinket context; not a tonight farm", ultimateTarget: true, realisticTarget: false, evidence: ["https://www.wowhead.com/classic/item=21180/earthstrike"] },
  { item: "Abyssal Plate Legplates of Striking", itemId: 20671, slot: "Legs", source: "Duke of Shards / Silithus", sourceContentType: "silithus", raidOrigin: false, requiresRaidParticipation: false, tradeable: true, faction: "Both", raceContext: "None", professionContext: "None", setDependency: "Random suffix of Striking", accessibility: "Outdoor elite encounter and rare suffix", whyFuryCares: "Potential strength/AP/haste leg option", equivalent: false, disposition: "needs-review", proposedTier: "strong", proposedPosition: "Needs exact Classic stat/source verification", ultimateTarget: false, realisticTarget: false, evidence: ["https://www.wowhead.com/classic/item=20671/abyssal-plate-legplates"] },
  { item: "Black Dragonscale Mail", slot: "Chest / Shoulders / Legs / Feet", source: "Dragonscale Leatherworking", sourceContentType: "crafted", raidOrigin: false, requiresRaidParticipation: false, tradeable: true, faction: "Both", raceContext: "Mail armor; class legality and Fury value require review", professionContext: "Crafted by Dragonscale Leatherworking; character need not know it", setDependency: "2-piece +1% hit; 3-piece +2% crit; 4-piece +10 fire resistance", accessibility: "Expensive scales and set commitment", whyFuryCares: "Set breakpoints may matter more than isolated pieces", equivalent: false, disposition: "conditional-add", proposedTier: "strong", proposedPosition: "Context/set-aware only; no independent slot reorder", ultimateTarget: false, realisticTarget: false, evidence: ["https://www.wowhead.com/classic/item=15050/black-dragonscale-breastplate"] },
  { item: "PvP reputation/rank rewards", slot: "Multiple", source: "Alterac Valley, Arathi Basin, Warsong Gulch, or PvP rank", sourceContentType: "pvp", raidOrigin: false, requiresRaidParticipation: false, tradeable: false, faction: "Faction/rep dependent", raceContext: "None", professionContext: "None", setDependency: "Varies", accessibility: "Separate reputation and rank gates; must not be conflated", whyFuryCares: "Some weapons/armor can be meaningful alternatives", equivalent: false, disposition: "needs-review", proposedPosition: "Audit each reward with exact phase/source evidence", ultimateTarget: false, realisticTarget: false, evidence: ["https://worldofwarcraft.blizzard.com/en-us/news/23302789/wow-classic-class-quests-and-new-reputation-rewards"] },
];

export const candidateByName = (name: string) => matureFuryCandidates.find((candidate) => candidate.item === name);
