import fs from "node:fs";
import path from "node:path";
import { eraFuryCuratedProfile } from "./data.ts";
import type { CuratedReferenceProfile, ReferenceGearSet, ReferenceItemEntry } from "./types.ts";

export const generatedCuratedPath = path.resolve("data/curated/generated/imported-reference.json");
type GeneratedSet = ReferenceGearSet & { className: string; specialization: string };
const phaseOneUniqueIds = new Set([17075, 18832, 18805, 18816, 17063, 18821]);
const phaseOneReview: Record<number, ReferenceItemEntry["reviewDecision"]> = { 18817: "approved-conditional", 18404: "approved", 19146: "approved", 19143: "approved-conditional", 18823: "approved-conditional", 19137: "approved", 18821: "approved", 17063: "approved-conditional", 17075: "approved-conditional", 17068: "approved-conditional", 18832: "approved", 18805: "approved-conditional", 18816: "approved-conditional", 17069: "approved", 17072: "approved" };
const decorateEntry = (entry: ReferenceItemEntry, set: ReferenceGearSet): ReferenceItemEntry => ({ ...entry, ...(set.id === "era-fury-phase-1" ? { origin: "phase-1-addition" as const, reviewDecision: phaseOneReview[entry.itemId] ?? "review-required", ...(entry.source.type === "Raid" || entry.itemId === 18404 ? { raidOrigin: true, requiresRaidContent: true } : {}), ...(phaseOneUniqueIds.has(entry.itemId) ? { uniqueGroup: `unique:${entry.itemId}` } : {}), ...(entry.itemId === 18404 ? { factionSources: { Alliance: "Celebrating Good Times", Horde: "For All To See" }, source: { ...entry.source, instance: "Onyxia's Lair", quest: "Head of Onyxia" } } : {}), ...(entry.itemId === 18823 ? { weaponContext: "Dagger +5", conditionalEffects: ["+5 dagger skill", "1% critical strike"] } : {}), ...(entry.itemId === 18816 ? { weaponContext: "One-hand dagger; Main Hand or Off Hand" } : {}) } : {}) });
function readGeneratedSets(): GeneratedSet[] { if (!fs.existsSync(generatedCuratedPath)) return []; try { const value = JSON.parse(fs.readFileSync(generatedCuratedPath, "utf8")) as GeneratedSet[]; return Array.isArray(value) ? value : []; } catch { return []; } }
function normalizeSet(set: GeneratedSet, metadata: ReferenceGearSet | undefined): ReferenceGearSet { const normalized = { ...metadata, ...set, id: set.id, className: metadata?.className ?? set.className.replace(/^warrior$/i, "Warrior"), specialization: metadata?.specialization ?? set.specialization.replace(/^fury$/i, "Fury"), name: metadata?.name ?? set.name, context: metadata?.context ?? set.context, referenceFrame: metadata?.referenceFrame ?? (set.phase === 0 ? "progression-era" : "current-era"), description: metadata?.description ?? set.description, methodology: metadata?.datasetVersion === "era-fury-pre-raid-v1" ? "Curated Reference" : metadata?.methodology ?? set.methodology, sourceProvenance: set.sourceProvenance, complete: set.complete, status: metadata?.status ?? set.status, publishedAt: metadata?.publishedAt, datasetVersion: metadata?.datasetVersion, changelog: metadata?.changelog, allowedRaidSources: metadata?.allowedRaidSources ?? set.allowedRaidSources, composition: metadata?.composition ?? set.composition, slots: Object.fromEntries(Object.entries(set.slots).map(([slot, entries]) => [slot, (entries ?? []).map((entry) => decorateEntry(entry as ReferenceItemEntry, set))])) }; return normalized; }
const entryCount = (set: ReferenceGearSet) => Object.values(set.slots).reduce((total, entries) => total + (entries?.length ?? 0), 0);
const compose = (set: ReferenceGearSet, all: ReferenceGearSet[]): ReferenceGearSet => {
  const composition = set.composition;
  const baseId = composition?.baseSetId;
  if (!composition || !baseId) return set;
  if (baseId === set.id) throw new Error(`Circular curated composition: ${set.id} inherits itself.`);
  const base = all.find((candidate) => candidate.id === baseId);
  if (!base) throw new Error(`Missing curated composition base ${baseId} for ${set.id}.`);
  if (base.composition?.baseSetId === set.id) throw new Error(`Circular curated composition: ${set.id} <-> ${base.id}.`);
  const exclusions = new Set(composition.exclusions ?? []);
  const slots: ReferenceGearSet["slots"] = {};
  for (const [slot, entries] of Object.entries(base.slots)) slots[slot as keyof ReferenceGearSet["slots"]] = (entries ?? []).filter((entry) => !exclusions.has(entry.itemId)).map((entry) => ({ ...entry, origin: "inherited" }));
  for (const [slot, entries] of Object.entries(set.slots)) slots[slot as keyof ReferenceGearSet["slots"]] = [...(slots[slot as keyof ReferenceGearSet["slots"]] ?? []), ...(entries ?? [])];
  return { ...set, slots, complete: false, composition: { ...composition, setId: composition.setId ?? set.id, additions: Object.values(set.slots).flatMap((entries) => entries ?? []) }, description: `${set.description} Composed from ${base.id} without mutating the base set.` };
};
export class CuratedReferenceRepository { private readonly profile: CuratedReferenceProfile; constructor(profile: CuratedReferenceProfile = eraFuryCuratedProfile) { this.profile = profile; } getProfile(): CuratedReferenceProfile { const generated = readGeneratedSets(); if (!generated.length) throw new Error(`Generated curated reference data is missing: ${generatedCuratedPath}`); const metadata = new Map(this.profile.sets.map((set) => [set.id, set])); const normalized = generated.map((set) => normalizeSet(set, metadata.get(set.id))); const generatedIds = new Set(normalized.map((set) => set.id)); const shells = this.profile.sets.filter((set) => !generatedIds.has(set.id)); const all = [...normalized, ...shells]; const sets = all.map((set) => compose(set, all)); return { ...this.profile, defaultSetId: sets.some((set) => set.id === this.profile.defaultSetId) ? this.profile.defaultSetId : sets[0]?.id ?? this.profile.defaultSetId, sets }; } getSets() { return this.getProfile().sets; } getSet(setId: string) { return this.getSets().find((set) => set.id === setId); } }
export const curatedReferenceRepository = new CuratedReferenceRepository();
export const getCanonicalCuratedProfile = () => curatedReferenceRepository.getProfile();
