import fs from "node:fs";
import path from "node:path";
import { eraFuryCuratedProfile } from "./data.ts";
import type { CuratedReferenceProfile, ReferenceGearSet, ReferenceItemEntry } from "./types.ts";

export const generatedCuratedPath = path.resolve("data/curated/generated/imported-reference.json");
type GeneratedSet = ReferenceGearSet & { className: string; specialization: string };
function readGeneratedSets(): GeneratedSet[] { if (!fs.existsSync(generatedCuratedPath)) return []; try { const value = JSON.parse(fs.readFileSync(generatedCuratedPath, "utf8")) as GeneratedSet[]; return Array.isArray(value) ? value : []; } catch { return []; } }
function normalizeSet(set: GeneratedSet, metadata: ReferenceGearSet | undefined): ReferenceGearSet { return { ...metadata, ...set, id: set.id, className: metadata?.className ?? set.className.replace(/^warrior$/i, "Warrior"), specialization: metadata?.specialization ?? set.specialization.replace(/^fury$/i, "Fury"), name: metadata?.name ?? set.name, context: metadata?.context ?? set.context, referenceFrame: metadata?.referenceFrame ?? (set.phase === 0 ? "progression-era" : "current-era"), description: metadata?.description ?? set.description, methodology: metadata?.datasetVersion === "era-fury-pre-raid-v1" ? "Curated Reference" : metadata?.methodology ?? set.methodology, sourceProvenance: set.sourceProvenance, complete: set.complete, status: metadata?.status ?? set.status, publishedAt: metadata?.publishedAt, datasetVersion: metadata?.datasetVersion, changelog: metadata?.changelog, slots: Object.fromEntries(Object.entries(set.slots).map(([slot, entries]) => [slot, (entries ?? []) as ReferenceItemEntry[]])) }; }
export class CuratedReferenceRepository { private readonly profile: CuratedReferenceProfile; constructor(profile: CuratedReferenceProfile = eraFuryCuratedProfile) { this.profile = profile; } getProfile(): CuratedReferenceProfile { const generated = readGeneratedSets(); if (!generated.length) throw new Error(`Generated curated reference data is missing: ${generatedCuratedPath}`); const metadata = new Map(this.profile.sets.map((set) => [set.id, set])); const sets = generated.map((set) => normalizeSet(set, metadata.get(set.id))); const generatedIds = new Set(sets.map((set) => set.id)); return { ...this.profile, defaultSetId: sets.some((set) => set.id === this.profile.defaultSetId) ? this.profile.defaultSetId : sets[0]?.id ?? this.profile.defaultSetId, sets: [...sets, ...this.profile.sets.filter((set) => !generatedIds.has(set.id))] }; } getSets() { return this.getProfile().sets; } getSet(setId: string) { return this.getSets().find((set) => set.id === setId); } }
export const curatedReferenceRepository = new CuratedReferenceRepository();
export const getCanonicalCuratedProfile = () => curatedReferenceRepository.getProfile();
