import { EquippedItem, NormalizedCharacter, UpgradeRecommendation } from "../types";
import { eraItems, source, tbcItems } from "../characters/items";

const current = (character: NormalizedCharacter, slot: EquippedItem["slot"]) => character.equipment.find((item) => item.slot === slot);
export function getMockRecommendations(character: NormalizedCharacter): UpgradeRecommendation[] {
  const items = character.contentVersion === "era" ? eraItems : tbcItems;
  if (character.contentVersion === "era") return [
    { slot: "Shoulder", currentItem: current(character, "Shoulder"), candidateItem: { ...items.shoulders, itemId: 16832, name: "Giantstalker's Spaulders", stats: { Agility: "+31", Stamina: "+14" } }, upgradeTier: "Meaningful", reason: "A clean stat upgrade that also starts a strong raid set path.", source: source("Raid", { instance: "Molten Core", boss: "Garr", difficulty: "Raid" }), difficulty: "Raid", availability: "Weekly lockout" },
    { slot: "Finger 2", currentItem: current(character, "Finger 2"), candidateItem: { ...items.ring, itemId: 18805, name: "Core Forged Ring", slot: "Finger 2", stats: { "Attack power": "+16", "Critical strike": "+1%" } }, upgradeTier: "Meaningful", reason: "A reliable ring upgrade from a raid boss already on your route.", source: source("Raid", { instance: "Molten Core", boss: "Garr", difficulty: "Raid" }), difficulty: "Raid", availability: "Weekly lockout" },
    { slot: "Trinket 2", currentItem: current(character, "Trinket 2"), candidateItem: { ...items.trinket, itemId: 13966, name: "Mark of the Chosen", slot: "Trinket 2", stats: { "All stats": "+25 proc" } }, upgradeTier: "Minor", reason: "An accessible quest reward that fills a weaker trinket slot.", source: source("Quest", { quest: "Mark of the Chosen", zone: "The Hinterlands", difficulty: "Quest" }), difficulty: "Quest", availability: "Always available" },
    { slot: "Main Hand", currentItem: current(character, "Main Hand"), candidateItem: { ...items.blade, itemId: 17068, name: "Deathbringer", stats: { Strength: "+20", "Critical strike": "+1%" } }, upgradeTier: "Major", reason: "A substantial weapon improvement for your current setup.", source: source("Raid", { instance: "Blackwing Lair", boss: "Nefarian", difficulty: "Raid" }), difficulty: "Raid", availability: "Late progression" },
    { slot: "Chest", currentItem: current(character, "Chest"), candidateItem: { ...items.chest, itemId: 16963, name: "Bloodfang Chestpiece", quality: "Epic", stats: { Agility: "+30", Stamina: "+20" } }, upgradeTier: "BestInSlot", reason: "The defining chest piece for a complete endgame set.", source: source("Raid", { instance: "Blackwing Lair", boss: "Nefarian", difficulty: "Raid" }), difficulty: "Raid", availability: "Late progression" },
  ];
  return [
    { slot: "Chest", currentItem: current(character, "Chest"), candidateItem: { ...items.chest, itemId: 28602, name: "Chestguard of the Conniver", stats: { "Healing power": "+55", Stamina: "+25" } }, upgradeTier: "Meaningful", reason: "A practical chest upgrade available on a focused heroic run.", source: source("Dungeon", { instance: "The Mechanar", difficulty: "Heroic" }), difficulty: "Heroic", availability: "Daily heroic" },
    { slot: "Neck", currentItem: current(character, "Neck"), candidateItem: { ...items.necklace, itemId: 28745, name: "Pendant of the Violet Eye", quality: "Epic", stats: { "Healing power": "+30", "Mana per 5": "+6" } }, upgradeTier: "Major", reason: "A strong caster necklace that stays relevant through early raids.", source: source("Raid", { instance: "Karazhan", boss: "The Curator", difficulty: "Raid" }), difficulty: "Raid", availability: "Weekly lockout" },
    { slot: "Trinket 2", currentItem: current(character, "Trinket 2"), candidateItem: { ...items.trinket2, itemId: 29376, name: "Essence of the Martyr", quality: "Epic", stats: { "Healing power proc": "+300" } }, upgradeTier: "Meaningful", reason: "A dungeon badge path gives you a dependable healing cooldown.", source: source("Badge Vendor", { zone: "Shattrath City", npc: "Olus", difficulty: "Badge Vendor" }), difficulty: "Badge Vendor", availability: "30 Badges" },
  ];
}
export function summarizeUpgrades(recommendations: UpgradeRecommendation[]) { return { total: recommendations.length, meaningful: recommendations.filter((item) => ["Meaningful", "Major", "BestInSlot"].includes(item.upgradeTier)).length, easy: recommendations.filter((item) => ["Minor", "Meaningful"].includes(item.upgradeTier) && ["Quest", "Dungeon", "Vendor", "Badge Vendor"].includes(item.source.type)).length, dungeon: recommendations.filter((item) => item.source.type === "Dungeon").length, raid: recommendations.filter((item) => item.source.type === "Raid").length }; }
export function groupRecommendations(recommendations: UpgradeRecommendation[]) { return Object.values(recommendations.reduce<Record<string, UpgradeRecommendation[]>>((groups, recommendation) => { const location = recommendation.source.instance ?? recommendation.source.zone ?? recommendation.source.type; (groups[location] ??= []).push(recommendation); return groups; }, {})); }
