import { eraFuryCandidates } from "../dataset.ts";
import { eraFuryWarriorProfile } from "../profiles.ts";
import { scoreLoadout } from "../engine.ts";
import { furyCalibrationFixtures } from "./fixtures.ts";
import type { CalibrationCase } from "./types.ts";
import type { EquippedItem } from "../../types.ts";

const numberFrom = (value: string | undefined) => Number(value?.match(/[-+]?\d+(?:\.\d+)?/)?.[0] ?? 0);
const stat = (item: { stats: Record<string, string> }, names: string[]) => Object.entries(item.stats).reduce((sum, [name, value]) => names.some((needle) => name.toLowerCase().includes(needle)) ? sum + numberFrom(value) : sum, 0);
const setCounts = (loadout: Record<string, EquippedItem | undefined>) => Object.values(loadout).reduce<Record<string, number>>((counts, item) => { if (item?.setId) counts[item.setId] = (counts[item.setId] ?? 0) + 1; return counts; }, {});
const setLabel = (id: string) => id === "might" ? "Might" : id === "wrath" ? "Battlegear of Wrath" : id === "fury-tier1" ? "Fury tier 1" : id === "dalrends" ? "Dal'Rend's Arms" : id;
const breakdown = (snapshot: ReturnType<typeof scoreLoadout>) => { const profile = eraFuryWarriorProfile; const hit = Math.min(snapshot.hit, profile.hitBreakpoint.target) * profile.hitBreakpoint.belowWeight + Math.max(0, snapshot.hit - profile.hitBreakpoint.target) * profile.hitBreakpoint.atOrAboveWeight; const contributions = { Strength: snapshot.strength * (profile.statWeights.Strength ?? 0), Agility: snapshot.agility * (profile.statWeights.Agility ?? 0), "Attack Power": snapshot.attackPower * (profile.statWeights["Attack power"] ?? 0), Crit: snapshot.crit * (profile.statWeights.Crit ?? 0), Hit: hit, "Set contribution": snapshot.setValue, "Effect contribution": snapshot.specialEffectValue, "Weapon DPS": snapshot.weaponDps * profile.weaponRule.dpsWeight, "Weapon speed": snapshot.weaponSpeed * profile.weaponRule.speedWeight }; return { contributions, total: Object.values(contributions).reduce((sum, value) => sum + value, 0) }; };

export function formatCalibrationDiagnostic(caseData: CalibrationCase) {
  const fixture = furyCalibrationFixtures.find((entry) => entry.name === caseData.characterFixture); const candidateA = eraFuryCandidates.find((item) => item.itemId === caseData.itemA); const candidateB = eraFuryCandidates.find((item) => item.itemId === caseData.itemB);
  if (!fixture || !candidateA || !candidateB) return `Unable to diagnose ${caseData.id}: fixture or candidate missing.`;
  const base = Object.fromEntries(fixture.character.equipment.map((item) => [item.slot, item])); const loadoutA = { ...base, [caseData.slot]: { ...candidateA, slot: caseData.slot } }; const loadoutB = { ...base, [caseData.slot]: { ...candidateB, slot: caseData.slot } }; const snapshotA = scoreLoadout(loadoutA, eraFuryWarriorProfile); const snapshotB = scoreLoadout(loadoutB, eraFuryWarriorProfile); const detailsA = breakdown(snapshotA); const detailsB = breakdown(snapshotB); const printItem = (label: string, item: typeof candidateA) => [`${label}:`, `item ID: ${item.itemId}`, `name: ${item.name}`, `stats: ${JSON.stringify(item.stats)}`, `Strength: ${stat(item, ["strength"])}`, `Agility: ${stat(item, ["agility"])}`, `Attack Power: ${stat(item, ["attack power", "attack_power"])}`, `Crit: ${stat(item, ["crit", "critical strike"])}`, `Hit: ${stat(item, ["hit"])}`, `weapon skill: ${item.weapon?.weaponSkillBonus ?? 0}`, `special effect: ${item.specialEffectId ?? "none"}`, `set membership: ${item.setId ? setLabel(item.setId) : "none"}`, `other modeled properties: ${JSON.stringify({ itemLevel: item.itemLevel, weapon: item.weapon, confidence: item.confidence })}`];
  const printBreakdown = (label: string, details: ReturnType<typeof breakdown>) => [`${label} complete-loadout score breakdown:`, ...Object.entries(details.contributions).map(([name, value]) => `${name} contribution: ${value.toFixed(2)}`), `Total candidate score: ${details.total.toFixed(2)}`];
  const countsA = setCounts(loadoutA); const countsB = setCounts(loadoutB); const activeA = eraFuryWarriorProfile.setBonuses.filter((bonus) => (countsA[bonus.setId] ?? 0) >= bonus.pieces).map((bonus) => `${bonus.label} (${bonus.pieces}-piece, +${bonus.value})`); const activeB = eraFuryWarriorProfile.setBonuses.filter((bonus) => (countsB[bonus.setId] ?? 0) >= bonus.pieces).map((bonus) => `${bonus.label} (${bonus.pieces}-piece, +${bonus.value})`);
  return [...printItem("Breastplate of Might", candidateA), "", ...printItem("Savage Gladiator Chain", candidateB), "", ...printBreakdown("Breastplate of Might", detailsA), "", ...printBreakdown("Savage Gladiator Chain", detailsB), "", "LOADOUT DELTA (A versus B):", `Strength: ${(snapshotA.strength - snapshotB.strength).toFixed(2)}`, `Agility: ${(snapshotA.agility - snapshotB.agility).toFixed(2)}`, `Attack Power: ${(snapshotA.attackPower - snapshotB.attackPower).toFixed(2)}`, `Crit: ${(snapshotA.crit - snapshotB.crit).toFixed(2)}`, `Hit: ${(snapshotA.hit - snapshotB.hit).toFixed(2)}`, `Set contribution: ${(snapshotA.setValue - snapshotB.setValue).toFixed(2)}`, `Special effects: ${(snapshotA.specialEffectValue - snapshotB.specialEffectValue).toFixed(2)}`, `Weapon DPS: ${(snapshotA.weaponDps - snapshotB.weaponDps).toFixed(2)}`, `Weapon speed: ${(snapshotA.weaponSpeed - snapshotB.weaponSpeed).toFixed(2)}`, `Other modeled differences: none`, "", "MIGHT SET CHECK:", `A Might pieces equipped: ${countsA.might ?? 0}`, `A active Might bonuses: ${activeA.join(", ") || "none"}`, `B Might pieces equipped: ${countsB.might ?? 0}`, `B active Might bonuses: ${activeB.join(", ") || "none"}`, "", `PrePull: A score = ${snapshotA.score.toFixed(2)}`, `PrePull: B score = ${snapshotB.score.toFixed(2)}`, `PrePull: A wins by ${(snapshotA.score - snapshotB.score).toFixed(2)}`, "", "Interpretation: the current heuristic values A's additional Strength more than B's Agility; no Might set bonus or special effect is applied by the profile.", "Classification: probable scoring-weight issue / unclear until additional cases; no profile change made."].join("\n");
}
