import type { EquippedItem, NormalizedCharacter, WeaponSkillContext } from "../../types.ts";
import type { CalibrationCase, CalibrationFixture, CalibrationReference, CalibrationScenario } from "./types.ts";

const item = (itemId: number, name: string, slot: NormalizedCharacter["equipment"][number]["slot"], stats: Record<string, string>, extra: Partial<EquippedItem> = {}): EquippedItem => ({ itemId, name, slot, quality: "Epic", stats, icon: name.slice(0, 2).toUpperCase(), ...extra });
const wrath = (itemId: number, name: string, slot: NormalizedCharacter["equipment"][number]["slot"], stats: Record<string, string>) => item(itemId, name, slot, stats, { setId: "wrath" });
const hordeBuffs = "Gift of the Wild; Arcane Intellect; Power Word: Fortitude; Windfury Totem";
const allianceBuffs = "Blessing of Kings; Blessing of Might; Arcane Intellect; Power Word: Fortitude";
const hordeImbues = "MH: Windfury Totem; OH: Elemental Sharpening Stone";
const allianceImbues = "MH: Dense Sharpening Stone; OH: Elemental Sharpening Stone";

const exactEquipment = (waist: ReturnType<typeof item> = item(16960, "Waistband of Wrath", "Waist", { Strength: "+20", Stamina: "+20" }), mainHand = item(17075, "Vis'kag the Bloodletter", "Main Hand", { "Attack power": "+20", Crit: "+1" }, { weapon: { damageMin: 100, damageMax: 187, speed: 2.6, dps: 55.2, hand: "one-hand", weaponType: "Sword" } }), offHand = item(12939, "Dal'Rend's Tribal Guardian", "Off Hand / Shield", { Strength: "+4" }, { setId: "dalrends", weapon: { damageMin: 52, damageMax: 97, speed: 1.8, dps: 41.4, hand: "one-hand", weaponType: "Sword" } })) => [
  wrath(16963, "Helm of Wrath", "Head", { Strength: "+17", Stamina: "+40" }), item(18404, "Onyxia Tooth Pendant", "Neck", { Hit: "+1", Crit: "+1" }), wrath(16961, "Pauldrons of Wrath", "Shoulder", { Strength: "+13", Stamina: "+27" }), item(17102, "Cloak of the Shrouded Mists", "Back", { Agility: "+22" }), wrath(16966, "Breastplate of Wrath", "Chest", { Strength: "+17", Stamina: "+40" }), wrath(16959, "Bracelets of Wrath", "Wrist", { Strength: "+13", Stamina: "+27" }), wrath(16964, "Gauntlets of Wrath", "Hands", { Strength: "+15", Stamina: "+20" }), waist, wrath(16962, "Legplates of Wrath", "Legs", { Strength: "+19", Stamina: "+27" }), wrath(16965, "Sabatons of Wrath", "Feet", { Strength: "+13", Stamina: "+30" }), item(17063, "Band of Accuria", "Finger 1", { Hit: "+2" }, { uniqueGroup: "17063" }), item(18821, "Quick Strike Ring", "Finger 2", { Strength: "+5", Stamina: "+8", Crit: "+1", "Attack power": "+30" }, { uniqueGroup: "18821" }), item(13965, "Blackhand's Breadth", "Trinket 1", { Crit: "+2" }), item(18466, "Royal Seal of Eldre'Thalas", "Trinket 2", {}, { uniqueGroup: "18466" }), mainHand, offHand, item(18282, "Core Marksman Rifle", "Ranged / Relic", { Agility: "+7" })];

const numberStat = (item: EquippedItem, key: string) => Number.parseFloat(item.stats[key]?.replace("%", "") ?? "0") || 0;
const weaponSkill = (race: string, weapon: EquippedItem) => { const type = weapon.weapon?.weaponType ?? ""; const racial = race === "Orc" && type.includes("Axe") ? 5 : race === "Human" && (type.includes("Sword") || type.includes("Mace")) ? 5 : 0; return 300 + racial + (weapon.weapon?.weaponSkillBonus ?? 0); };
const completeTalents = "Arms (17 points): Improved Heroic Strike 3/3, Improved Rend 3/3, Tactical Mastery 5/5, Anger Management 1/1, Deep Wounds 3/3, Impale 2/2; Fury (34 points): Cruelty 5/5, Unbridled Wrath 5/5, Improved Cleave 2/3, Piercing Howl 1/1, Improved Berserker Rage 2/2, Enrage 5/5, Flurry 5/5, Dual Wield Specialization 5/5, Improved Execute 2/2, Bloodthirst 1/1, Death Wish 1/1; Protection (0 points): none";
const setPieces = (equipment: EquippedItem[]) => Object.entries(equipment.reduce<Record<string, number>>((counts, equipped) => { if (equipped.setId) counts[equipped.setId] = (counts[equipped.setId] ?? 0) + 1; return counts; }, {})).map(([setId, count]) => `${setId === "wrath" ? "Battlegear of Wrath" : setId === "dalrends" ? "Dal'Rend's Arms" : setId}: ${count}/${setId === "wrath" ? 8 : 2}`);
const activeSets = (equipment: EquippedItem[]) => { const counts = equipment.reduce<Record<string, number>>((result, entry) => { if (entry.setId) result[entry.setId] = (result[entry.setId] ?? 0) + 1; return result; }, {}); const active: string[] = []; if ((counts.wrath ?? 0) >= 2) active.push("Battlegear of Wrath 2-piece: profile-modeled +35 score"); if ((counts.wrath ?? 0) >= 4) active.push("Battlegear of Wrath 4-piece: profile-modeled +75 score"); return active; };
const derived = (race: string, equipment: EquippedItem[]) => { const mh = equipment.find((entry) => entry.slot === "Main Hand")!; const oh = equipment.find((entry) => entry.slot === "Off Hand / Shield")!; const strength = equipment.reduce((total, entry) => total + numberStat(entry, "Strength"), 0); const agility = equipment.reduce((total, entry) => total + numberStat(entry, "Agility"), 0); const hit = equipment.reduce((total, entry) => total + numberStat(entry, "Hit"), 0); const crit = equipment.reduce((total, entry) => total + numberStat(entry, "Crit") + numberStat(entry, "Critical strike"), 0); const attackPower = equipment.reduce((total, entry) => total + numberStat(entry, "Attack power"), 0) + strength * 2; const mhSkill = weaponSkill(race, mh); const ohSkill = weaponSkill(race, oh); return { strength, agility, hit, crit, attackPower, talentPoints: 51, mainHandWeaponSkill: mhSkill, offHandWeaponSkill: ohSkill, weaponSkill: `MH ${mh.weapon?.weaponType ?? "Unknown"} ${mhSkill} / OH ${oh.weapon?.weaponType ?? "Unknown"} ${ohSkill}`, mainHand: `${mh.name} (#${mh.itemId})`, offHand: `${oh.name} (#${oh.itemId})`, setPiecesEquipped: setPieces(equipment), activeSetBonuses: activeSets(equipment) }; };
const baseline = (overrides: Partial<CalibrationScenario> = {}): CalibrationScenario => ({ level: 60, targetLevel: 63, race: "Orc", faction: "Horde", talents: completeTalents, buffs: hordeBuffs, debuffs: "Faerie Fire; Curse of Recklessness; Sunder Armor x5; Improved Expose Armor absent", consumables: "Elixir of the Mongoose; Juju Power; Juju Might; Smoked Desert Dumpling", weaponImbues: hordeImbues, fightDuration: "120 seconds", worldBuffs: "NONE", weaponSkill: "derived from equipped weapons", mainHand: "derived", offHand: "derived", mainHandWeaponSkill: 0, offHandWeaponSkill: 0, hit: 0, crit: 0, attackPower: 0, strength: 0, agility: 0, talentPoints: 51, setPiecesEquipped: [], activeSetBonuses: [], ...overrides });
const character = (name: string, scenario: CalibrationScenario, equipment: EquippedItem[]): NormalizedCharacter => ({ id: `calibration-${name}`, name, region: "eu", realm: "Firemaw", contentVersion: "era", realmType: "era", level: 60, race: scenario.race, class: "Warrior", spec: "Fury", faction: scenario.faction, professions: ["Engineering", "Mining"], equipment, weaponSkillContext: { skills: { Sword: scenario.mainHandWeaponSkill, Axe: scenario.race === "Orc" ? 305 : 300, Mace: scenario.race === "Human" ? 305 : 300 }, racialBonuses: scenario.race === "Orc" ? { Axe: 5 } : { Sword: 5, Mace: 5 }, source: "profile" } satisfies WeaponSkillContext });
const fixture = (name: string, scenario: CalibrationScenario, equipment = exactEquipment()): CalibrationFixture => { const calculated = derived(scenario.race, equipment); const resolved = { ...scenario, ...calculated, faction: scenario.race === "Human" ? "Alliance" as const : "Horde" as const, buffs: scenario.race === "Human" ? allianceBuffs : hordeBuffs, weaponImbues: scenario.race === "Human" ? allianceImbues : hordeImbues }; return { name, character: character(name, resolved, equipment), scenario: resolved }; };
const referencePending = (notes: string, scenario: CalibrationScenario): CalibrationReference => ({ status: "pending", source: "simulation", tool: "WoWSims Classic Warrior", toolVersion: "manual entry required", notes, scenario });

const hitEquipment = (hitItems: EquippedItem[]) => { const equipment = exactEquipment(); for (const replacement of hitItems) { const index = equipment.findIndex((entry) => entry.slot === replacement.slot); if (index >= 0) equipment.splice(index, 1, replacement); } return equipment; };
const below = baseline();
const atTarget = baseline();
const above = baseline();
const freshEquipment = exactEquipment(); freshEquipment.splice(4, 1, item(11726, "Savage Gladiator Chain", "Chest", { Strength: "+14", Agility: "+7" }));
const preRaidEquipment = exactEquipment(item(18393, "Warpwood Binding", "Waist", { Strength: "+15", Agility: "+12", Crit: "+1" }), item(12940, "Dal'Rend's Sacred Charge", "Main Hand", { Strength: "+4" }, { setId: "dalrends", weapon: { damageMin: 63, damageMax: 118, speed: 2, dps: 45.3, hand: "one-hand", weaponType: "Sword" }}));
const noSetEquipment = exactEquipment().map((entry) => entry.setId === "wrath" ? { ...entry, setId: undefined } : entry);
const strengthCritEquipment = noSetEquipment.map((entry) => entry.slot === "Trinket 2" ? item(11815, "Hand of Justice", "Trinket 2", { "Attack power": "+20" }, { uniqueGroup: "11815" }) : entry.slot === "Ranged / Relic" ? item(17069, "Striker's Mark", "Ranged / Relic", { Agility: "+20", Hit: "+1" }) : entry);
const atTargetEquipment = hitEquipment([item(19137, "Onslaught Girdle", "Waist", { Strength: "+20", Agility: "+20", Hit: "+1", Crit: "+1" }), item(12927, "Truestrike Shoulders", "Shoulder", { Strength: "+12", Agility: "+12", Hit: "+1" }), item(15063, "Devilsaur Gauntlets", "Hands", { Agility: "+14", Hit: "+1", Crit: "+1" }), item(15062, "Devilsaur Leggings", "Legs", { Agility: "+20", Hit: "+1", Crit: "+1" }), item(13386, "Archivist Cape", "Back", { Agility: "+7", Hit: "+1" }), item(13954, "Verdant Footpads", "Feet", { Agility: "+15", Hit: "+1" })]);
const aboveEquipment = hitEquipment([...atTargetEquipment.filter((entry) => entry.slot !== "Neck"), item(13098, "Painweaver Band", "Finger 2", { "Attack power": "+20", Crit: "+1", Hit: "+1" })]);
export const furyCalibrationFixtures: CalibrationFixture[] = [fixture("fresh-60", baseline(), freshEquipment), fixture("pre-raid", baseline(), preRaidEquipment), fixture("molten-core", baseline()), fixture("bwl", baseline({ race: "Human" })), fixture("aq", baseline({ race: "Human" })), fixture("naxx-near-bis", baseline()), fixture("hit-below-target", below, hitEquipment([])), fixture("hit-at-target", atTarget, atTargetEquipment), fixture("hit-above-target", above, aboveEquipment), fixture("strength-crit", baseline(), strengthCritEquipment)];

const pending = (text: string, fixtureName: string) => referencePending(text, furyCalibrationFixtures.find((fixture) => fixture.name === fixtureName)!.scenario);
export const furyCalibrationCases: CalibrationCase[] = [
  { id: "dps-chest-vs-tier-chest", characterFixture: "strength-crit", slot: "Chest", itemA: 16865, itemB: 11726, reference: pending("Manual Guybrush reference entered for offensive-stats versus defensive-tier chest comparison.", "strength-crit"), tags: ["offensive-stats", "defensive-tier"], notes: "Breastplate of Might versus Savage Gladiator Chain." },
  { id: "hit-below-target-neck", characterFixture: "hit-below-target", slot: "Neck", itemA: 18404, itemB: 19577, reference: pending("Manual reference required below the Hit breakpoint.", "hit-below-target"), tags: ["hit-below-target"], notes: "Onyxia Tooth Pendant versus Rage of Mugamba." },
  { id: "hit-above-target-waist", characterFixture: "hit-above-target", slot: "Waist", itemA: 19137, itemB: 18393, reference: pending("Manual reference required above the Hit breakpoint.", "hit-above-target"), tags: ["hit-above-target"], notes: "Onslaught Girdle versus Warpwood Binding." },
  { id: "main-hand-dps-vs-stats", characterFixture: "molten-core", slot: "Main Hand", itemA: 17075, itemB: 18832, reference: pending("Manual raw weapon comparison required; no Thunderfury proc confound.", "molten-core"), tags: ["weapon-dps", "main-hand"], notes: "Vis'kag versus Brutality Blade." },
  { id: "fast-vs-slow-main-hand", characterFixture: "bwl", slot: "Main Hand", itemA: 18832, itemB: 17075, reference: pending("Manual speed comparison required with equal sword skill context.", "bwl"), tags: ["weapon-speed", "main-hand"], notes: "Real one-hand swords; neither adds item weapon skill." },
  { id: "off-hand-comparison", characterFixture: "molten-core", slot: "Off Hand / Shield", itemA: 12939, itemB: 18832, reference: pending("Manual off-hand comparison required.", "molten-core"), tags: ["off-hand"], notes: "Dal'Rend's Tribal Guardian versus Brutality Blade without a Dal'Rend's set-threshold confound." },
  { id: "weapon-skill-race", characterFixture: "aq", slot: "Main Hand", itemA: 17075, itemB: 23577, reference: pending("Manual Human sword-skill comparison; Hungering Cold is only in the swapped main hand.", "aq"), tags: ["weapon-skill", "race"], notes: "Human +5 Sword versus The Hungering Cold item context." },
  { id: "set-vs-non-set", characterFixture: "molten-core", slot: "Chest", itemA: 16966, itemB: 11726, reference: pending("Manual Wrath set threshold comparison required.", "molten-core"), tags: ["set-bonus"], notes: "Seven other Wrath pieces remain equipped in both loadouts." },
  { id: "proc-vs-passive-trinket", characterFixture: "fresh-60", slot: "Trinket 2", itemA: 11815, itemB: 18466, reference: pending("Manual two-minute Hand of Justice versus Warrior Royal Seal comparison.", "fresh-60"), tags: ["trinket", "proc"], notes: "Warrior Royal Seal variant is #18466; both trinket slots are unique-safe." },
  { id: "high-ilvl-downgrade", characterFixture: "pre-raid", slot: "Chest", itemA: 22416, itemB: 11726, reference: pending("Manual legal high-item-level versus dungeon chest comparison.", "pre-raid"), tags: ["item-level-trap"], notes: "Dreadnaught Breastplate is a real Warrior set item; no synthetic future item." },
  { id: "hit-near-target", characterFixture: "hit-at-target", slot: "Waist", itemA: 19137, itemB: 18393, reference: pending("Manual breakpoint comparison required.", "hit-at-target"), tags: ["hit-at-target"], notes: "Exact total Hit is recorded in the fixture." },
  { id: "racial-weapon-context", characterFixture: "naxx-near-bis", slot: "Off Hand / Shield", itemA: 12939, itemB: 18832, reference: pending("Manual Orc weapon context comparison required.", "naxx-near-bis"), tags: ["race", "weapon-skill"], notes: "Orc Axe +5 is disclosed; both candidates are swords, so it does not silently change skill." },
];
