import { eraFuryCandidates } from "../dataset.ts";
import { furyCalibrationCases, furyCalibrationFixtures } from "./fixtures.ts";
import { validateCalibrationCase } from "./validate.ts";
import type { CalibrationCase } from "./types.ts";

const candidateMap = new Map(eraFuryCandidates.map((candidate) => [candidate.itemId, candidate]));
const fixtureMap = new Map(furyCalibrationFixtures.map((fixture) => [fixture.name, fixture]));
const label = (id: number) => { const item = candidateMap.get(id); return item ? `${item.name} (#${item.itemId})` : `Missing candidate (#${id})`; };
const swappedSkill = (fixture: (typeof furyCalibrationFixtures)[number], caseData: CalibrationCase, id: number) => { const candidate = candidateMap.get(id); const weapon = candidate?.weapon; if (!weapon) return `${fixture.scenario.mainHandWeaponSkill}/${fixture.scenario.offHandWeaponSkill}`; const racial = fixture.scenario.race === "Human" && (weapon.weaponType?.includes("Sword") || weapon.weaponType?.includes("Mace")) ? 5 : fixture.scenario.race === "Orc" && weapon.weaponType?.includes("Axe") ? 5 : 0; const skill = 300 + racial + (weapon.weaponSkillBonus ?? 0); return caseData.slot === "Main Hand" ? `${skill}/${fixture.scenario.offHandWeaponSkill}` : `${fixture.scenario.mainHandWeaponSkill}/${skill}`; };
const equipmentLine = (entry: (typeof furyCalibrationFixtures)[number]["character"]["equipment"][number]) => `${entry.slot}: ${entry.name} (#${entry.itemId})${entry.setId ? ` [set ${entry.setId}]` : ""}${entry.uniqueGroup ? ` [unique ${entry.uniqueGroup}]` : ""}`;

export function formatPendingCase(caseData: CalibrationCase) {
  const fixture = fixtureMap.get(caseData.characterFixture); if (!fixture) return `CASE: ${caseData.id}\nInvalid fixture: ${caseData.characterFixture}`;
  const { scenario } = fixture; const readiness = validateCalibrationCase(caseData);
  return [`CASE: ${caseData.id}`, `Mechanic: ${caseData.tags.join(", ")}`, `Ready for external simulation: ${readiness.ready ? "YES" : "NO"}`, ...(readiness.issues.length ? ["Readiness issues:", ...readiness.issues.map((issue) => `- ${issue.code}: ${issue.message}`)] : []), "", "EXACT COMBAT STATE", `Faction: ${scenario.faction}`, `Race: ${scenario.race}`, `Level: ${scenario.level}`, `Talents (${scenario.talentPoints} points): ${scenario.talents}`, `Target: level ${scenario.targetLevel}`, `Duration: ${scenario.fightDuration}`, `World buffs: ${scenario.worldBuffs}`, `Raid buffs: ${scenario.buffs}`, `Boss debuffs: ${scenario.debuffs}`, `Consumables: ${scenario.consumables}`, `Weapon imbues: ${scenario.weaponImbues}`, `Main hand: ${scenario.mainHand}`, `Off hand: ${scenario.offHand}`, `Weapon skill: MH ${scenario.mainHandWeaponSkill} / OH ${scenario.offHandWeaponSkill}`, `ITEM-DERIVED STATS (equipment contributions only): Hit ${scenario.hit}; Crit ${scenario.crit}; Attack Power ${scenario.attackPower}; Strength ${scenario.strength}; Agility ${scenario.agility}`, "FINAL UNBUFFED CHARACTER STATS: not independently modeled; use item-derived values as simulator sanity checks only", `Set pieces equipped: ${scenario.setPiecesEquipped.join("; ") || "None"}`, `Active set bonuses: ${scenario.activeSetBonuses.join("; ") || "None"}`, "", "COMPLETE BASE LOADOUT", ...fixture.character.equipment.map(equipmentLine), "", `LOADOUT A SWAP: ${label(caseData.itemA)}`, `Loadout A weapon skill after swap: MH/OH ${swappedSkill(fixture, caseData, caseData.itemA)}`, `LOADOUT B SWAP: ${label(caseData.itemB)}`, `Loadout B weapon skill after swap: MH/OH ${swappedSkill(fixture, caseData, caseData.itemB)}`, "", "REFERENCE INPUT (intentionally pending)", "Simulator: WoWSims Classic Warrior or Guybrush Warrior Sim", "Tool version/date: enter after permitted manual simulation", "Loadout A DPS: enter after simulation", "Loadout B DPS: enter after simulation", "Iterations: enter after simulation", "Captured date/reviewer: enter after simulation"].join("\n");
}

export function pendingCases(cases = furyCalibrationCases) { return cases.filter((caseData) => !caseData.reference || caseData.reference.status === "pending"); }
