import Link from "next/link";
import { notFound } from "next/navigation";
import { VersionShell } from "../../../../../../components/version-shell";
import { requireUser } from "../../../../../../lib/guilds/auth";
import { getRaidDetail } from "../../../../../../lib/guilds/raid-detail";
import { signupAction, saveSignupOverrideAction, clearSignupOverrideAction, saveRosterStateAction, saveAssignmentAction } from "../../../../../../lib/guilds/actions";
import type { ContentVersion } from "../../../../../../lib/types";

const display = (value: unknown) => String(value ?? "—").replaceAll("-", " ");
export default async function RaidDetailPage({ params }: { params: { version: string; guildId: string; raidId: string } }) {
  const user = await requireUser(); let data; try { data = await getRaidDetail(user.id, params.guildId, params.raidId); } catch { notFound(); }
  const { guild, event, roster, signups, selected, bench, groups, assignments, audit, canManageRoster, canManageAssignments } = data;
  const readiness = selected.filter((entry: any) => roster.find((member: any) => member.id === entry.guild_member_id)?.readiness === "ready").length;
  return <VersionShell version={params.version as ContentVersion}><main className="mx-auto max-w-6xl px-5 py-12"><Link href={`/${params.version}/guilds/${params.guildId}`} className="text-xs text-[var(--muted)]">← Guild workspace</Link><header className="mt-8 flex flex-wrap justify-between gap-4"><div><p className="eyebrow">RaidBoard · {event.instance}</p><h1 className="display mt-2 text-4xl">{event.name}</h1><p className="mt-2 text-sm text-[var(--muted)]">{event.starts_at} · {display(event.status)}</p></div><div className="panel rounded-xl p-4"><p className="eyebrow">Readiness</p><p className="text-2xl">{readiness}/{selected.length}</p><p className="text-xs text-[var(--muted)]">selected ready</p></div></header>
    <section className="panel mt-6 rounded-2xl p-6"><h2 className="text-xl font-semibold">Signup totals</h2><div className="mt-4 flex flex-wrap gap-4 text-sm">{["accepted","tentative","unavailable","late","no-response"].map((status) => <span key={status}><strong>{signups.filter((s:any)=>(s.effective_status||"no-response")===status).length}</strong> <span className="capitalize text-[var(--muted)]">{status}</span></span>)}</div></section>
    <section className="panel mt-6 rounded-2xl p-6"><h2 className="text-xl font-semibold">Member signup</h2><p className="mt-1 text-sm text-[var(--muted)]">Your submitted status remains separate from any officer override.</p><form action={signupAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="guildId" value={guild.id}/><input type="hidden" name="eventId" value={event.id}/><label className="text-sm">Submitted status<select name="status" defaultValue="tentative" className="field mt-1 w-full"><option value="accepted">Accepted</option><option value="tentative">Tentative</option><option value="unavailable">Unavailable</option><option value="late">Late</option></select></label><label className="text-sm">Preferred role<input name="preferredRole" className="field mt-1 w-full" placeholder="Damage, tank, healer"/></label><label className="text-sm">Alternate role<input name="alternateRole" className="field mt-1 w-full"/></label><label className="text-sm">Note<input name="note" className="field mt-1 w-full"/></label><button className="button-primary sm:col-span-2" type="submit">Save my signup</button></form></section>
    <section className="panel mt-6 rounded-2xl p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Signup list</h2><p className="text-xs text-[var(--muted)]">Member submitted status and effective status are shown separately.</p></div><span className="text-xs text-[var(--muted)]">Roster version {event.version} · Assignment version {event.assignment_version}</span></div><div className="mt-4 grid gap-3">{signups.map((signup:any)=><article key={signup.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap justify-between gap-2"><span>{signup.character_name} <small className="text-[var(--muted)]">{signup.realm}</small></span><span className="capitalize">Effective: {display(signup.effective_status)}</span></div><p className="mt-1 text-xs text-[var(--muted)]">Member submitted: {display(signup.member_status)} · Roles: {signup.preferred_role || "—"}{signup.alternate_role ? ` / ${signup.alternate_role}` : ""}</p>{signup.override_actor_user_id ? <p className="mt-1 text-xs text-amber-200">Officer override by {signup.override_actor_name ?? signup.override_actor_user_id}{signup.override_reason ? `: ${signup.override_reason}` : ""}</p> : null}{canManageRoster ? <div className="mt-3 flex flex-wrap gap-2"><form action={saveSignupOverrideAction} className="flex gap-2"><input type="hidden" name="guildId" value={guild.id}/><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="memberId" value={signup.guild_member_id}/><select name="effectiveStatus" aria-label="Effective signup status" className="field"><option value="accepted">Accepted</option><option value="tentative">Tentative</option><option value="unavailable">Unavailable</option><option value="late">Late</option><option value="no-response">No response</option></select><input name="reason" placeholder="Reason" className="field"/><button className="button-secondary" type="submit">Override</button></form>{signup.override_actor_user_id ? <form action={clearSignupOverrideAction}><input type="hidden" name="guildId" value={guild.id}/><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="memberId" value={signup.guild_member_id}/><button className="button-secondary" type="submit">Clear override</button></form> : null}</div> : null}</article>)}</div></section>
    {canManageRoster ? <section className="panel mt-6 rounded-2xl p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Selected roster and bench</h2><p className="text-sm text-[var(--muted)]">Selected: {selected.length} · Bench: {bench.length} · Groups: {groups.length} · five players maximum per group.</p></div><span className="text-xs text-[var(--muted)]">Loaded version {event.version}</span></div><form action={saveRosterStateAction} className="mt-4"><input type="hidden" name="guildId" value={guild.id}/><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="rosterVersion" value={event.version}/><div className="grid gap-3 md:grid-cols-2">{roster.map((member:any)=>{const entry=[...selected,...bench].find((item:any)=>item.guild_member_id===member.id);const isSelected=selected.some((item:any)=>item.guild_member_id===member.id);return <label key={member.id} className="flex items-center gap-3 rounded-lg border border-white/10 p-3 text-sm"><input type="checkbox" name={isSelected?"selectedId":"benchId"} value={member.id} defaultChecked={Boolean(entry)} aria-label={`${isSelected?"Selected":"Bench"} ${member.character_name}`}/><span className="flex-1">{member.character_name} <small className="text-[var(--muted)]">{member.class_name} · {member.readiness}</small></span><select name="roleEntry" defaultValue={`${member.id}:${entry?.role_name??""}`} className="field text-xs"><option value={`${member.id}:`}>Role</option><option value={`${member.id}:Tank`}>Tank</option><option value={`${member.id}:Healer`}>Healer</option><option value={`${member.id}:DPS`}>DPS</option></select>{isSelected ? <select name="groupEntry" defaultValue={`${entry?.group_name??"none"}:${member.id}`} className="field text-xs"><option value={`none:${member.id}`}>Unassigned</option>{Array.from({length:8},(_,index)=><option key={index} value={`Group ${index+1}:${member.id}`}>Group {index+1}</option>)}</select> : null}</label>})}</div><button className="button-primary mt-4" type="submit">Save roster state</button></form></section> : null}
    <section className="panel mt-6 rounded-2xl p-6"><h2 className="text-xl font-semibold">Groups</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{groups.map((group:any)=><div key={group.name} className="rounded-lg border border-white/10 p-3"><h3>{group.name}</h3><p className="mt-1 text-xs text-[var(--muted)]">{group.members.length}/5 · {group.members.map((m:any)=>m.character_name).join(", ")}</p></div>)}{!groups.length?<p className="text-sm text-[var(--muted)]">No group assignments yet.</p>:null}</div></section>
    <section className="panel mt-6 rounded-2xl p-6"><div className="flex justify-between gap-3"><h2 className="text-xl font-semibold">Assignments</h2><span className="text-xs text-[var(--muted)]">Version {event.assignment_version}</span></div>{canManageAssignments?<form action={saveAssignmentAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="guildId" value={guild.id}/><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="assignmentVersion" value={event.assignment_version}/><input type="hidden" name="operation" value="create"/><label className="text-sm">Assignment label<input name="label" className="field mt-1 w-full" required/></label><label className="text-sm">Category<input name="category" defaultValue="general" className="field mt-1 w-full"/></label><label className="text-sm sm:col-span-2">Assignment text<textarea name="detail" className="field mt-1 w-full"/></label><button className="button-primary sm:col-span-2" type="submit">Create assignment</button></form>:null}<div className="mt-5 grid gap-3">{assignments.map((assignment:any)=><article key={assignment.id} className="rounded-lg border border-white/10 p-3"><div className="flex justify-between gap-2"><h3>{assignment.label}</h3><span className="text-xs text-[var(--muted)]">{assignment.section} · {assignment.category}</span></div><p className="mt-1 text-sm">{assignment.detail || "—"}</p><p className="mt-1 text-xs text-[var(--muted)]">Assignees: {(assignment.assignees??[]).map((a:any)=>a.name).join(", ") || "None"}</p>{canManageAssignments?<form action={saveAssignmentAction} className="mt-3"><input type="hidden" name="guildId" value={guild.id}/><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="assignmentVersion" value={event.assignment_version}/><input type="hidden" name="operation" value="delete"/><input type="hidden" name="assignmentId" value={assignment.id}/><button className="button-secondary" type="submit">Delete</button></form>:null}</article>)}</div></section>
    <section className="panel mt-6 rounded-2xl p-6"><h2 className="text-xl font-semibold">Recent raid activity</h2>{audit.map((entry:any)=><p key={`${entry.created_at}-${entry.action}`} className="mt-2 text-xs text-[var(--muted)]">{new Date(entry.created_at).toLocaleString()} · {entry.actor_name??"System"} · {entry.action}</p>)}</section>
  </main></VersionShell>;
}
