import { notFound } from "next/navigation";
import { Hero } from "../../components/hero";
import { RaidCard, ToolCard, ClassCard } from "../../components/cards";
import { SectionHeader } from "../../components/section-header";
import { VersionShell } from "../../components/version-shell";
import { gameVersions, isGameVersion } from "../../lib/game-data";
import { GameVersion } from "../../lib/types";
export default async function Home({ params }: { params: Promise<{ version: string }> }) {
  const resolvedParams = await params; if (!isGameVersion(resolvedParams.version)) notFound(); const version = resolvedParams.version as GameVersion; const data = gameVersions[version]; return <VersionShell version={version}><main><Hero version={version} /><section className="mx-auto max-w-[1240px] px-5 pb-24 lg:px-8"><SectionHeader eyebrow="The road ahead" title="Prepare for your next raid" description={data.tagline} link="View all raids" /><div className="flex gap-4 overflow-x-auto pb-4">{data.raids.map((raid) => <RaidCard key={raid.name} raid={raid} version={version} />)}</div></section><section className="bg-[var(--surface)]/45 py-20"><div className="mx-auto max-w-[1240px] px-5 lg:px-8"><SectionHeader eyebrow="Built for preparation" title="PrePull tools" description="A better way to turn game time into raid time." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.tools.map((tool) => <ToolCard key={tool.name} tool={tool} version={version} />)}</div></div></section><section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8"><SectionHeader eyebrow="Know your role" title="Classes" description="Understand your kit, your role, and what comes next." link="Explore classes" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{data.classes.map((info) => <ClassCard key={info.name} info={info} version={version} />)}</div></section></main></VersionShell>; }
