import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Hero } from "../../components/hero";
import { RaidCard, ToolCard, ClassCard } from "../../components/cards";
import { SectionHeader } from "../../components/section-header";
import { VersionShell } from "../../components/version-shell";
import { gameVersions, isContentVersion } from "../../lib/game-data";
import type { ContentVersion } from "../../lib/types";

const versionCopy = {
  era: { name: "Classic Era", short: "Era", statement: "Built for the long game in Azeroth.", description: "Curated priorities, raid preparation, and guild coordination for level 60 Classic Era." },
  tbc: { name: "The Burning Crusade", short: "TBC", statement: "Built for the journey beyond the portal.", description: "A focused preparation hub for level 70 characters, Outland raids, and TBC guilds." },
} as const;

export async function generateMetadata({ params }: { params: Promise<{ version: string }> }): Promise<Metadata> { const { version } = await params; if (!isContentVersion(version)) return {}; return { title: `PrePull — ${versionCopy[version].name} preparation`, description: versionCopy[version].description }; }

export default async function Home({ params }: { params: Promise<{ version: string }> }) {
  const resolved = await params; if (!isContentVersion(resolved.version)) notFound(); const version = resolved.version as ContentVersion; const data = gameVersions[version]; const copy = versionCopy[version];
  return <VersionShell version={version}><main><Hero version={version} />
    <section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div className="lg:sticky lg:top-28"><div className="eyebrow">Preparation, connected</div><h2 className="display mt-4 text-4xl leading-tight tracking-[-.035em] sm:text-5xl">One clear view from character to guild.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[var(--text-muted)]">PrePull connects personal priorities with the people and events around your next raid—without hiding decisions behind unexplained scores.</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-[var(--border)] bg-[var(--border)] sm:grid-cols-2"><ValueCard number="01" title="Know what matters next" body="Refresh your equipment and get a short, explainable list of realistic upgrades." /><ValueCard number="02" title="Turn priorities into a session" body="Build a focused preparation plan around the time and activity you prefer." /><ValueCard number="03" title="Coordinate the whole roster" body="Share readiness, identify common opportunities, and organise Prep Runs together." /><ValueCard number="04" title="Plan around the game" body="Keep verified holidays, battleground weekends, and world events within reach." /></div></div></section>
    <section className="home-band border-y border-[var(--border)] py-20 lg:py-24"><div className="mx-auto max-w-[1240px] px-5 lg:px-8"><SectionHeader eyebrow={`${copy.short} progression`} title="Prepare for the road ahead" description={`${copy.statement} Explore the raids your roster is working toward.`} link="Explore raids" /><div className="home-scroll flex gap-4 overflow-x-auto pb-4">{data.raids.map((raid) => <RaidCard key={raid.name} raid={raid} version={version} />)}</div></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8 lg:py-28"><SectionHeader eyebrow="A complete preparation loop" title="Less tab switching. More useful game time." description="The tools stay connected to the same character, content version, and guild context." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.tools.map((tool) => <ToolCard key={tool.name} tool={tool} version={version} />)}</div></section>
    <section className="border-y border-[var(--border)] bg-[var(--surface-muted)]/65"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-24"><div><div className="eyebrow">How it works</div><h2 className="display mt-4 text-4xl tracking-[-.035em]">From login to ready in three moves.</h2><Link href={`/${version}/onboarding`} className="button-secondary focus-ring mt-7 rounded-full">Open your dashboard <span className="ml-2" aria-hidden="true">→</span></Link></div><ol className="space-y-3"><WorkflowStep number="1" title="Connect your character" body="Save a public profile and establish your current equipment baseline." /><WorkflowStep number="2" title="Choose a practical path" body="Review curated recommendations or build a focused preparation session." /><WorkflowStep number="3" title="Bring the plan to your guild" body="Share readiness voluntarily and coordinate the opportunities that help everyone." /></ol></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8 lg:py-24"><SectionHeader eyebrow={`${copy.short} classes`} title="Preparation for every role" description="Explore class context while supported recommendation coverage continues to expand." link="Explore classes" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{data.classes.map((info) => <ClassCard key={info.name} info={info} version={version} />)}</div></section>
    <section className="mx-auto max-w-[1240px] px-5 pb-20 lg:px-8 lg:pb-28"><div className="home-cta relative overflow-hidden rounded-[2rem] border border-[var(--border-strong)] px-6 py-12 sm:px-10 lg:flex lg:items-end lg:justify-between lg:px-14 lg:py-16"><div className="relative z-10"><div className="eyebrow">Your next pull starts here</div><h2 className="display mt-4 max-w-2xl text-4xl leading-tight tracking-[-.04em] sm:text-5xl">Make every hour before raid night count.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[var(--text-muted)]">Start with your character, then build a preparation rhythm that fits {copy.name}.</p></div><div className="relative z-10 mt-8 flex flex-wrap gap-3 lg:mt-0"><Link href={`/${version}/characters/connect`} className="button-primary focus-ring rounded-full px-6 py-3.5">Connect character</Link><Link href={`/${version}/guilds`} className="button-secondary focus-ring rounded-full px-6 py-3.5">Open guild tools</Link></div></div></section>
  </main></VersionShell>;
}

function ValueCard({ number, title, body }: { number: string; title: string; body: string }) { return <article className="bg-[var(--surface)] p-6 sm:p-7"><div className="text-[10px] font-bold tracking-[.2em] text-[var(--accent)]">{number}</div><h3 className="display mt-8 text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">{body}</p></article>; }
function WorkflowStep({ number, title, body }: { number: string; title: string; body: string }) { return <li className="panel grid gap-4 rounded-2xl p-5 sm:grid-cols-[3rem_1fr] sm:items-start"><span className="display grid h-11 w-11 place-items-center rounded-full border border-[var(--border-strong)] text-lg text-[var(--accent-hover)]">{number}</span><div><h3 className="text-base font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">{body}</p></div></li>; }
