import type { EquippedItem } from "../types.ts";
import type { NormalizedItemMetadata } from "./types.ts";
import type { ItemFetchReason } from "../blizzard/item-data-provider.ts";
import { normalizedItemMetadata, readCachedItemMetadata, writeCachedItemMetadata } from "./store.ts";
import { validateMetadataRecord } from "./validate.ts";

export type MetadataSyncResult = { uniqueIds: number; alreadyKnown: number; fetched: number; unresolved: number[]; unresolvedReasons: Record<number, ItemFetchReason>; conflicts: Array<{ itemId: number; existingName: string; resolvedName: string }>; validationErrors: string[]; records: NormalizedItemMetadata[] };
export type MetadataResolution = { item: EquippedItem | null; reason?: ItemFetchReason };
export type MetadataResolver = (itemId: number) => Promise<MetadataResolution>;
export function detectMetadataNameConflict(existing: NormalizedItemMetadata, resolved: EquippedItem) { return existing.itemId === resolved.itemId && existing.name !== resolved.name ? { itemId: existing.itemId, existingName: existing.name, resolvedName: resolved.name } : undefined; }
export async function syncCuratedMetadata(itemIds: number[], resolver?: MetadataResolver, persist = false): Promise<MetadataSyncResult> { const unique = [...new Set(itemIds)]; const known = normalizedItemMetadata(); const unresolved: number[] = []; const unresolvedReasons: Record<number, ItemFetchReason> = {}; const conflicts: MetadataSyncResult["conflicts"] = []; let fetched = 0; for (const itemId of unique) { if (known.has(itemId)) continue; const resolution = resolver ? await resolver(itemId).catch(() => ({ item: null, reason: "unknown-error" as ItemFetchReason })) : { item: null, reason: "missing-credentials" as ItemFetchReason }; if (!resolution.item) { unresolved.push(itemId); unresolvedReasons[itemId] = resolution.reason ?? "unknown-error"; continue; } const existing = known.get(itemId); const conflict = existing && detectMetadataNameConflict(existing, resolution.item); if (conflict) { conflicts.push(conflict); continue; } known.set(itemId, { ...resolution.item, provenance: { source: "blizzard-api", verifiedAt: new Date().toISOString(), contentVersion: "era", realmType: "era" } }); fetched += 1; } const records = [...known.values()].filter((record) => record.provenance.source !== "manual-dataset"); if (persist && fetched && !conflicts.length) writeCachedItemMetadata(records); const validationErrors = records.flatMap((record) => validateMetadataRecord(record).filter((issue) => issue.severity === "error").map((issue) => `#${issue.itemId}: ${issue.message}`)); return { uniqueIds: unique.length, alreadyKnown: unique.length - fetched - unresolved.length, fetched, unresolved, unresolvedReasons, conflicts, validationErrors, records }; }
