import Link from "next/link";
import { GearAnalysisResult } from "../lib/gear-analysis/types";

export function AnalysisStatus({ analysis }: { analysis: GearAnalysisResult }) {
  if (!analysis.supported) return <section className="mx-auto max-w-[1240px] px-5 pb-16 lg:px-8"><div className="panel rounded-xl p-5 text-sm text-[var(--muted)]">{analysis.message}</div></section>;
  return <section className="mx-auto max-w-[1240px] px-5 pb-16 lg:px-8"><div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="panel rounded-xl p-5"><div className="eyebrow mb-2">Analysis assumptions</div><h2 className="display text-2xl">{analysis.profileVersion}</h2><ul className="mt-4 space-y-2 text-xs leading-5 text-[var(--muted)]">{analysis.assumptions && <><li>Hit target: {analysis.assumptions.hitTarget}%</li><li>Phase: {analysis.assumptions.currentPhase}</li><li>{analysis.assumptions.enchantTreatment}</li><li>{analysis.assumptions.worldBuffs} World buffs</li><li>{analysis.assumptions.specialEffects}</li></>}</ul><Link href={analysis.assumptions?.methodologyPath ?? "#"} className="mt-5 inline-block text-xs font-semibold text-[var(--primary-light)]">How PrePull evaluates gear →</Link></div><div className="panel rounded-xl p-5"><div className="eyebrow mb-2">What should I do next?</div><h2 className="display text-2xl">Highest-value destinations</h2>{analysis.activities.length ? <div className="mt-4 space-y-3">{analysis.activities.slice(0, 3).map((activity) => <div key={activity.destination} className="border-b border-[var(--line)] pb-3 text-sm"><div className="flex items-center justify-between gap-4"><span className="text-[var(--text)]">{activity.destination}</span><span className="text-right text-xs text-[var(--muted)]">{activity.score} priority</span></div><p className="mt-1 text-xs text-[var(--muted)]">{activity.recommendation}</p></div>)}</div> : <p className="mt-4 text-sm text-[var(--muted)]">No curated upgrades currently beat this loadout.</p>}</div></div></section>;
}

export function AnalysisSlotPanel({ analysis, slot }: { analysis: GearAnalysisResult; slot: string }) {
  if (!analysis.supported) return null;
  const entry = analysis.bySlot[slot];
  if (!entry) return <div className="panel mt-8 rounded-xl p-5 text-sm text-[var(--muted)]">No curated upgrade currently beats this slot.</div>;
  const options = [entry.bestRealistic, entry.bestInSlot, ...entry.otherOptions].filter(Boolean);
  return <section className="mt-8 panel rounded-xl p-5"><div className="eyebrow mb-2">Compared loadouts</div><h2 className="display text-2xl">Other evaluated options</h2><div className="mt-5 space-y-4">{options.map((recommendation) => recommendation && <div key={`${recommendation.candidateItem.itemId}-${recommendation.upgradeTier}`} className="border-b border-[var(--line)] pb-4 last:border-0 last:pb-0"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-[var(--text)]">{recommendation.candidateItem.name}</strong><span className="text-xs text-[var(--primary-light)]">{recommendation.upgradeTier} · {recommendation.confidence} confidence</span></div><p className="mt-2 text-xs leading-5 text-[var(--muted)]">{recommendation.reason}</p><p className="mt-2 text-[11px] text-[var(--muted)]">{recommendation.source.instance ?? recommendation.source.zone ?? recommendation.source.type} · {recommendation.source.boss ?? recommendation.source.quest ?? recommendation.difficulty}</p></div>)}</div></section>;
}
