import { CharacterLogsLoader } from "./character-logs-loader";
import { CharacterSheet } from "./character-sheet";
import { projectArmory } from "../lib/armory/projection";
import Link from "next/link";
import { CharacterRealmType, ContentVersion, EquipmentSlot, EquippedItem, NormalizedCharacter, UpgradeRecommendation, UpgradeSummary } from "../lib/types";
import { groupRecommendations } from "../lib/upgrades/mock-upgrades";
import { GearAnalysisResult } from "../lib/gear-analysis/types";

const qualityClass: Record<string, string> = { Poor: "text-zinc-500", Common: "text-zinc-300", Uncommon: "text-emerald-400", Rare: "text-blue-400", Epic: "text-purple-400", Legendary: "text-orange-400" };
const upgradeClass: Record<string, string> = { Minor: "text-[var(--muted)]", Meaningful: "text-[var(--primary-light)]", Major: "text-orange-300", BestInSlot: "text-purple-300" };
const characterPath = (character: NormalizedCharacter) => `/${character.contentVersion}/character/${character.realmType}/${character.region}/${character.realm.toLowerCase()}/${character.name.toLowerCase()}`;
export function CharacterOverview({ character, saved = false }: { saved?: boolean; character: NormalizedCharacter; recommendations: UpgradeRecommendation[]; summary: UpgradeSummary }) { return <main className="mx-auto max-w-[1240px] px-5 py-12 lg:px-8"><CharacterSheet saved={saved} logs={<CharacterLogsLoader input={{ contentVersion: character.contentVersion, realmType: character.realmType, region: character.region, realm: character.realm, characterName: character.name }} />} armory={projectArmory(character, (saved ? character.dataMeta?.lastUpdated : character.dataMeta?.retrievedAt) ?? new Date().toISOString())} /></main>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-[var(--line)] pb-3"><dt className="text-[var(--muted)]">{label}</dt><dd className="text-right text-[var(--text)]">{value}</dd></div>; }
function NextSteps({ recommendations, version, live }: { recommendations: UpgradeRecommendation[]; version: ContentVersion; live?: boolean }) { const groups = groupRecommendations(recommendations); return <section className="mt-20 border-t border-[var(--line)] pt-12"><div className="eyebrow mb-3">Your next move</div><h2 className="display text-3xl">What should I do next?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--muted)]">{live ? "Upgrade analysis will appear once PrePull has trusted source data for this live profile." : "A short list of realistic destinations, grouped from your current upgrade paths."}</p>{groups.length > 0 && <div className="mt-7 grid gap-4 md:grid-cols-2">{groups.map((group) => { const location = group[0].source.instance ?? group[0].source.zone ?? group[0].source.type; return <div className="panel rounded-xl p-5" key={location}><div className="flex items-start justify-between gap-3"><div><h3 className="text-base font-semibold text-[var(--text)]">{location}</h3><p className="mt-1 text-xs text-[var(--muted)]">{group.length} possible meaningful upgrade{group.length === 1 ? "" : "s"}</p></div><span className="text-[var(--primary-light)]">⌁</span></div><div className="mt-5 flex flex-wrap gap-2">{group.map((recommendation) => <span key={recommendation.slot} className="rounded-full bg-[var(--surface-raised)] px-3 py-1.5 text-xs text-[var(--muted)]">{recommendation.slot}</span>)}</div><Link href={`/${version}/raids`} className="mt-5 inline-block text-xs font-semibold text-[var(--primary-light)]">View upgrades →</Link></div>; })}</div>}</section>; }
export function GearDetail({ character, recommendation }: { character: NormalizedCharacter; recommendation?: UpgradeRecommendation }) { const currentItem = recommendation?.currentItem; return <main className="mx-auto min-h-[calc(100vh-148px)] max-w-[1000px] px-5 py-12 lg:px-8 lg:py-16"><Link href={characterPath(character)} className="text-xs text-[var(--muted)] hover:text-[var(--primary-light)]">← Back to character</Link><div className="mt-10"><div className="eyebrow mb-3">Slot detail / {recommendation?.slot ?? "Equipment"}</div><h1 className="display text-4xl">Upgrade path</h1><p className="mt-2 text-sm text-[var(--muted)]">A grounded look at what could improve this slot next.</p></div>{recommendation ? <div className="mt-10 grid gap-5 md:grid-cols-2"><ItemPanel title="Currently equipped" item={currentItem} /><div className="rounded-xl border border-[var(--primary)]/40 bg-[var(--surface)] p-5"><div className="eyebrow mb-5">Best realistic upgrade</div><ItemPanel title={recommendation.upgradeTier === "BestInSlot" ? "Best in slot" : recommendation.upgradeTier} item={recommendation.candidateItem} compact /><div className="mt-5 border-t border-[var(--line)] pt-5 text-sm leading-6 text-[var(--muted)]"><p>{recommendation.reason}</p><dl className="mt-4 space-y-2 text-xs"><Detail label="Source" value={recommendation.source.type} /><Detail label="Location" value={recommendation.source.instance ?? recommendation.source.zone ?? "—"} /><Detail label="Boss / vendor" value={recommendation.source.boss ?? recommendation.source.npc ?? recommendation.source.quest ?? "—"} /><Detail label="Difficulty" value={recommendation.difficulty} /></dl></div><Link href={`/${character.contentVersion}/raids`} className="mt-5 inline-block text-xs font-semibold text-[var(--primary-light)]">View guide →</Link></div></div> : <div className="panel mt-10 rounded-xl p-7 text-sm text-[var(--muted)]">No upgrade recommendations are recorded for this slot yet.</div>}</main>; }
function ItemPanel({ title, item, compact }: { title: string; item?: EquippedItem; compact?: boolean }) { return <div className={compact ? "" : "panel rounded-xl p-5"}><div className="eyebrow mb-4">{title}</div>{item ? <><div className="flex gap-4"><span className="grid h-12 w-12 place-items-center rounded-lg bg-[var(--surface-raised)] text-sm font-bold text-[var(--primary-light)]">{item.icon}</span><div><h2 className={`text-base font-semibold ${qualityClass[item.quality]}`}>{item.name}</h2><p className="mt-1 text-xs text-[var(--muted)]">{item.quality}{item.itemLevel ? ` · iLvl ${item.itemLevel}` : ""}</p></div></div><div className="mt-5 space-y-2 text-xs text-[var(--muted)]">{Object.entries(item.stats).map(([label, value]) => <div className="flex justify-between border-b border-[var(--line)] pb-2" key={label}><span>{label}</span><span className="text-[var(--text)]">{value}</span></div>)}</div></> : <p className="text-sm text-[var(--muted)]">No item equipped.</p>}</div>; }
