import type { CuratedEvaluation, CuratedRecommendation } from "../lib/curated-gear/types";

const tierLabel = (recommendation?: CuratedRecommendation["target"]) => recommendation?.reference.tier.toUpperCase() ?? "UNRANKED";
const sourceLabel = (recommendation: CuratedRecommendation) => recommendation.target?.source?.instance ?? recommendation.target?.source?.zone ?? recommendation.target?.source?.type ?? "Unspecified source";
const itemLabel = (item?: CuratedRecommendation["target"]) => item?.name ?? "No ranked target yet";

function RecommendationCard({ recommendation }: { recommendation: CuratedRecommendation }) {
  return <div className="rounded-lg border border-[var(--line)] p-3"><div className="flex justify-between gap-3 text-xs"><span className="font-bold text-[var(--text)]">{recommendation.slot}</span><span className="text-[var(--primary-light)]">{recommendation.scope.replaceAll("-", " ")}</span></div><p className="mt-2 text-sm text-[var(--text)]">{itemLabel(recommendation.target)}</p><p className="mt-1 text-[11px] text-[var(--muted)]">Current: {recommendation.currentItem?.name ?? "empty"}{recommendation.currentTier ? ` · ${recommendation.currentTier}` : ""} · Priority: {recommendation.priority.replaceAll("-", " ")}{recommendation.target ? ` · Target: ${tierLabel(recommendation.target)} · ${sourceLabel(recommendation)}` : ""}</p>{recommendation.bestRealistic && <p className="mt-1 text-[11px] text-[var(--muted)]">Best realistic: {recommendation.bestRealistic.name} · {recommendation.bestRealistic.reference.tier}</p>}<p className="mt-1 text-[11px] text-[var(--muted)]">{recommendation.reason}</p>{recommendation.conditionalNotes.length > 0 && <p className="mt-1 text-[11px] text-[var(--muted)]">Note: {recommendation.conditionalNotes.join(" ")}</p>}<p className="mt-1 text-[10px] uppercase tracking-wider text-[var(--muted)]">Certainty: {recommendation.certainty}</p></div>;
}

export function CuratedOverview({ evaluation }: { evaluation: CuratedEvaluation }) { return <section className="mx-auto max-w-[1240px] px-5 pb-12 lg:px-8"><div className="panel rounded-xl p-5"><div className="eyebrow mb-2">Curated Reference</div><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="display text-2xl">Established progression options</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">{evaluation.methodology}</p></div><span className="rounded-full border border-[var(--line)] px-3 py-1.5 text-[10px] font-bold tracking-widest text-[var(--primary-light)]">{evaluation.set.name}</span></div>{evaluation.referenceAvailability === "not-available" && <p className="mt-4 rounded-lg border border-[var(--line)] p-3 text-sm text-[var(--muted)]">Reference data not yet available for this progression level. Later-phase curated data is required; no Pre-Raid downgrade recommendations are generated.</p>}<div className="mt-5 grid gap-3 md:grid-cols-2">{evaluation.recommendations.map((recommendation) => <RecommendationCard key={recommendation.slot} recommendation={recommendation} />)}</div>{evaluation.activities.length > 0 && <div className="mt-5 border-t border-[var(--line)] pt-5"><div className="eyebrow mb-2">What should I do next?</div><div className="space-y-2">{evaluation.activities.map((activity) => <div key={activity.activity} className="rounded-lg bg-[var(--surface-raised)] px-3 py-2 text-xs text-[var(--muted)]">{activity.activity} · {activity.upgrades.length} upgrade{activity.upgrades.length === 1 ? "" : "s"} · {activity.slots.join(", ")} · highest tier {activity.highestTier}</div>)}</div></div>}{evaluation.incompleteData && <p className="mt-5 text-xs text-[var(--muted)]">This reference set is incomplete. Unranked slots are intentionally not inferred.</p>}</div></section>; }

export function CuratedSlotPanel({ evaluation, slot }: { evaluation: CuratedEvaluation; slot: string }) { const recommendation = evaluation.recommendations.find((entry) => entry.slot === slot); if (!recommendation) return <div className="panel mt-8 rounded-xl p-5 text-sm text-[var(--muted)]">This slot is not ranked in the selected curated reference set.</div>; const options = [recommendation.target, recommendation.bestRealistic, ...recommendation.otherOptions].filter(Boolean); return <section className="mt-8 panel rounded-xl p-5"><div className="eyebrow mb-2">Curated Reference</div><h2 className="display text-2xl">Target and alternatives</h2><p className="mt-2 text-sm text-[var(--muted)]">{evaluation.methodology}</p><p className="mt-2 text-xs text-[var(--muted)]">Priority: {recommendation.priority.replaceAll("-", " ")} · Current: {recommendation.currentItem?.name ?? "empty"} · Current tier: {recommendation.currentTier ?? "unranked"}</p><div className="mt-5 space-y-3">{options.map((item, index) => item && <div key={`${item.itemId}-${index}`} className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] pb-3 last:border-0 last:pb-0"><div><strong className="text-sm text-[var(--text)]">{item.name}</strong><p className="mt-1 text-[11px] text-[var(--muted)]">{item.reference.tier} · {item.source?.instance ?? item.source?.zone ?? item.source?.type ?? "Unspecified source"}</p></div><span className="text-xs text-[var(--primary-light)]">{index === 0 ? "Target" : item === recommendation.bestRealistic ? "Best realistic" : "Alternative"}</span></div>)}</div></section>; }
