"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { CharacterRealmType, ContentVersion } from "../lib/types";
import { normalizeLookup } from "../lib/characters/normalization";
import { authSignUpHref } from "../lib/auth-callback";

const heroCopy = {
  era: { eyebrow: "Built for World of Warcraft Classic Era", title: "Walk into every raid already prepared.", description: "Turn your character, your next upgrades, and your guild's plans into one clear path from login to first pull.", realm: "Firemaw", atmosphere: "Azeroth awaits" },
  tbc: { eyebrow: "Built for The Burning Crusade Classic", title: "Cross the portal. Leave nothing unprepared.", description: "Track the gear, attunements, events, and guild preparation that matter before your next journey into Outland.", realm: "Spineshatter", atmosphere: "Beyond the Dark Portal" },
} as const;

export function Hero({ version }: { version: ContentVersion }) {
  const copy = heroCopy[version];
  return <section className="home-hero relative overflow-hidden border-b border-[var(--border)]">
    <div className="hero-grid pointer-events-none absolute inset-0" aria-hidden="true" />
    <div className="relative mx-auto grid max-w-[1240px] gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24">
      <div className="relative z-10"><div className="eyebrow mb-6 flex items-center gap-3"><span className="h-px w-10 bg-[var(--accent)]" />{copy.eyebrow}</div><h1 className="display max-w-3xl text-[clamp(3.25rem,7vw,6.8rem)] leading-[.88] tracking-[-.055em] text-[var(--text)]">{copy.title}</h1><p className="mt-7 max-w-xl text-base leading-7 text-[var(--text-muted)] sm:text-lg sm:leading-8">{copy.description}</p><div className="mt-9 flex flex-wrap gap-3"><Link href={authSignUpHref(`/${version}/characters/connect`)} className="button-primary focus-ring rounded-full px-6 py-3.5">Find your character <span aria-hidden="true" className="ml-2">→</span></Link><Link href={authSignUpHref(`/${version}/characters/connect`)} className="button-secondary focus-ring rounded-full px-6 py-3.5">Create account</Link></div><dl className="mt-12 grid max-w-2xl grid-cols-3 border-y border-[var(--border)] py-5"><HeroFact value="5" label="supported specs" /><HeroFact value="10" label="curated sets" /><HeroFact value="1" label="shared prep hub" /></dl></div>
      <div className="relative mx-auto w-full max-w-xl lg:mx-0"><ExpansionEmblem version={version} label={copy.atmosphere} /><CharacterSearch version={version} defaultRealm={copy.realm} /></div>
    </div>
  </section>;
}

function HeroFact({ value, label }: { value: string; label: string }) { return <div className="border-r border-[var(--border)] px-3 first:pl-0 last:border-0 last:pr-0 sm:px-6"><dt className="display text-2xl text-[var(--accent-hover)] sm:text-3xl">{value}</dt><dd className="mt-1 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--text-muted)]">{label}</dd></div>; }

function ExpansionEmblem({ version, label }: { version: ContentVersion; label: string }) { return <div className="expansion-emblem pointer-events-none absolute -right-8 -top-24 hidden h-64 w-64 place-items-center lg:grid" aria-hidden="true"><span className="emblem-orbit absolute inset-0 rounded-full" /><span className="emblem-orbit emblem-orbit-inner absolute inset-8 rounded-full" /><span className="display text-center text-3xl tracking-[-.04em] text-[var(--accent-hover)]"><small className="mb-2 block font-sans text-[9px] font-bold uppercase tracking-[.28em] text-[var(--text-muted)]">{label}</small>{version.toUpperCase()}</span></div>; }

function CharacterSearch({ version, defaultRealm }: { version: ContentVersion; defaultRealm: string }) {
  const router = useRouter(); const [realmType, setRealmType] = useState<CharacterRealmType>(version === "tbc" ? "anniversary" : "era"); const [region, setRegion] = useState("eu"); const [realm, setRealm] = useState(""); const [name, setName] = useState(""); const [status, setStatus] = useState<"idle" | "searching" | "invalid">("idle");
  function submit(event: FormEvent) { event.preventDefault(); if (!realm.trim() || !name.trim()) { setStatus("invalid"); return; } setStatus("searching"); const query = new URLSearchParams({ search: "1", region, realmType, realm: normalizeLookup(realm), name: normalizeLookup(name) }); router.push(authSignUpHref(`/${version}/characters/connect?${query}`)); }
  return <div className="hero-search panel relative z-10 mt-28 rounded-3xl p-5 sm:p-7 lg:mr-12 lg:mt-24"><div className="mb-7 flex items-start justify-between gap-5"><div><div className="eyebrow mb-2">Character intelligence</div><h2 className="display text-3xl">Find your next move.</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Enter an exact realm and character, then create an account or sign in to run the lookup securely.</p></div><span className="search-status-dot mt-2 h-3 w-3 shrink-0 rounded-full bg-[var(--accent)]" aria-hidden="true" /></div><form onSubmit={submit} className="space-y-4"><fieldset><legend className="field-label">Realm ecosystem</legend><div className="grid grid-cols-2 rounded-xl border border-[var(--border)] bg-[var(--surface-muted)] p-1">{(["era", "anniversary"] as CharacterRealmType[]).map((item) => <button type="button" key={item} aria-pressed={realmType === item} onClick={() => setRealmType(item)} className={`focus-ring rounded-lg px-3 py-2.5 text-xs font-bold tracking-wider transition ${realmType === item ? "bg-[var(--accent)] text-[var(--background)] shadow-lg" : "text-[var(--text-muted)] hover:text-[var(--text)]"}`}>{item === "era" ? "ERA" : "ANNIVERSARY"}</button>)}</div></fieldset><div className="grid gap-4 sm:grid-cols-[.65fr_1.35fr]"><label><span className="field-label">Region</span><select value={region} onChange={(event) => setRegion(event.target.value)} className="home-field focus-ring"><option value="eu">Europe</option><option value="us">North America</option></select></label><label><span className="field-label">Realm</span><input value={realm} onChange={(event) => setRealm(event.target.value)} placeholder={defaultRealm} className="home-field focus-ring" required /></label></div><label><span className="field-label">Character name</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Character name" className="home-field focus-ring" required /></label><button disabled={status === "searching"} className="button-primary focus-ring w-full rounded-xl py-3.5">{status === "searching" ? "Continuing…" : "Find your character"}</button></form><p aria-live="polite" className="mt-4 min-h-5 text-center text-xs text-[var(--text-muted)]">{status === "invalid" ? "Enter both a realm and character name to continue." : `${version.toUpperCase()} content selected · realm ecosystem stays independent`}</p></div>;
}
