"use client";

import Link from "next/link";
import { useState } from "react";
import type { ContentVersion } from "../lib/types";
import { filterUnifiedCalendar, type UnifiedCalendarEntry, type UnifiedCalendarFilter, type UnifiedCalendarProjection, type UnifiedGameCalendarEntry } from "../lib/calendar/unified";
import type { CalendarDisplayRegion, GameCalendarEvent } from "../lib/calendar/types";

const filters: { value: UnifiedCalendarFilter; label: string }[] = [
  { value: "all", label: "All" }, { value: "guild", label: "Guild" }, { value: "battlegrounds", label: "Battlegrounds" }, { value: "holidays", label: "Holidays" }, { value: "darkmoon-faire", label: "Darkmoon Faire" }, { value: "world-seasonal", label: "World / Seasonal" },
];
const categoryLabels: Record<GameCalendarEvent["category"], string> = { battleground: "Battleground", "darkmoon-faire": "Darkmoon Faire", holiday: "Holiday", seasonal: "Seasonal", "world-event": "World event", special: "Special", other: "Other" };

export function UnifiedCalendar({ version, projection }: { version: ContentVersion; projection: UnifiedCalendarProjection }) {
  const [filter, setFilter] = useState<UnifiedCalendarFilter>("all");
  const visible = filterUnifiedCalendar(projection, filter);
  const sections = new Map<string, UnifiedCalendarEntry[]>();
  for (const entry of visible.upcoming) sections.set(entry.dateKey, [...(sections.get(entry.dateKey) ?? []), entry]);
  const regionHref = (region: CalendarDisplayRegion) => `/${version}/guilds/${projection.guildId}/calendar?region=${region}`;
  return <>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-4"><div className="flex rounded-full border border-[var(--border)] bg-[var(--surface)] p-1" role="group" aria-label="Game Calendar region">{(["eu", "us"] as const).map((region) => <Link key={region} href={regionHref(region)} aria-current={projection.gameRegion === region ? "true" : undefined} className={`focus-ring rounded-full px-4 py-2 text-xs font-bold ${projection.gameRegion === region ? "bg-[var(--accent)] text-[var(--background)]" : "text-[var(--muted)]"}`}>{region.toUpperCase()}</Link>)}</div><p className="text-xs leading-5 text-[var(--muted)]">Game events: {projection.gameRegion.toUpperCase()} · Guild activity: {projection.guildTimeZone}</p></div>
    <fieldset className="mt-6"><legend className="sr-only">Filter unified calendar</legend><div className="flex flex-wrap gap-2">{filters.map((item) => <button type="button" key={item.value} onClick={() => setFilter(item.value)} aria-pressed={filter === item.value} className={`focus-ring rounded-full border px-3 py-2 text-xs ${filter === item.value ? "border-[var(--accent)] text-[var(--accent-hover)]" : "border-[var(--border)] text-[var(--muted)]"}`}>{item.label}</button>)}</div></fieldset>
    <CalendarSection title="Happening now" eyebrow="Current and today" entries={visible.happeningNow} empty="No active game events or guild activity today for this filter." />
    <section className="mt-12" aria-labelledby="unified-upcoming"><div className="eyebrow">Combined schedule</div><h2 id="unified-upcoming" className="display mt-2 text-3xl">Upcoming</h2>{sections.size ? <div className="mt-6 space-y-9">{[...sections].map(([date, entries]) => <section key={date} aria-labelledby={`unified-date-${date}`}><h3 id={`unified-date-${date}`} className="text-sm font-bold uppercase tracking-wider text-[var(--muted)]">{dateHeading(date, projection.guildToday)}</h3><ul className="mt-3 grid gap-3">{entries.map((entry) => <li key={`${entry.kind}-${entry.id}`}><UnifiedEntryCard entry={entry} /></li>)}</ul></section>)}</div> : <p className="panel mt-5 rounded-2xl p-5 text-sm text-[var(--muted)]">No upcoming events for this filter.</p>}</section>
    {visible.unscheduled.length ? <section className="mt-12" aria-labelledby="unified-unscheduled"><div className="eyebrow">Outside the timeline</div><h2 id="unified-unscheduled" className="display mt-2 text-3xl">Unscheduled Prep Runs</h2><ul className="mt-4 grid gap-3 sm:grid-cols-2">{visible.unscheduled.map((run) => <li key={run.id}><Link href={run.href} className="focus-ring panel block rounded-2xl p-5"><span className="origin-badge">Prep Run</span><h3 className="mt-3 font-semibold">{run.title}</h3><p className="mt-1 text-sm text-[var(--muted)]">For {run.raidName} · Time not set</p></Link></li>)}</ul></section> : null}
  </>;
}

function CalendarSection({ title, eyebrow, entries, empty }: { title: string; eyebrow: string; entries: UnifiedCalendarEntry[]; empty: string }) { return <section className="mt-10" aria-labelledby="unified-now"><div className="eyebrow">{eyebrow}</div><h2 id="unified-now" className="display mt-2 text-3xl">{title}</h2>{entries.length ? <ul className="mt-5 grid gap-3">{entries.map((entry) => <li key={`${entry.kind}-${entry.id}`}><UnifiedEntryCard entry={entry} /></li>)}</ul> : <p className="panel mt-5 rounded-2xl p-5 text-sm text-[var(--muted)]">{empty}</p>}</section>; }

function UnifiedEntryCard({ entry }: { entry: UnifiedCalendarEntry }) {
  if (entry.kind === "game-event") return <GameEntryCard entry={entry} />;
  return <Link href={entry.href} className="focus-ring panel block rounded-2xl p-5"><div className="flex flex-wrap items-center gap-2"><span className="origin-badge">{entry.kind === "raid" ? "Guild Raid" : "Prep Run"}</span><span className="text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">{entry.status}</span></div><div className="mt-3 flex items-start gap-4"><time dateTime={entry.scheduledFor} className="w-14 shrink-0 text-lg font-semibold tabular-nums">{entry.guildLocalTime}</time><div><h3 className="font-semibold">{entry.title}</h3><p className="mt-1 text-xs text-[var(--muted)]">Guild time · {entry.guildLocalDate}</p></div></div></Link>;
}

function GameEntryCard({ entry }: { entry: UnifiedGameCalendarEntry }) { return <article className="panel rounded-2xl p-5"><div className="flex flex-wrap items-center gap-2"><span className="origin-badge">Game</span><span className="text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">{categoryLabels[entry.category]} · {entry.region.toUpperCase()}</span></div><h3 className="display mt-3 text-2xl">{entry.title}</h3><p className="mt-2 text-sm font-semibold"><time>{gameDateLabel(entry)}</time> <span className="font-normal text-[var(--muted)]">· All day / date range</span></p>{entry.shortDescription ? <p className="mt-3 text-sm leading-6 text-[var(--muted)]">{entry.shortDescription}</p> : null}{entry.locationLabel ? <p className="mt-2 text-xs text-[var(--muted)]">Location: {entry.locationLabel}</p> : null}<details className="mt-4 border-t border-[var(--border)] pt-4"><summary className="focus-ring cursor-pointer text-xs font-bold text-[var(--accent-hover)]">Source and verification</summary><div className="mt-3 text-xs leading-5 text-[var(--muted)]"><p>Verified {displayDate(entry.source.verifiedAt, true)}.</p>{entry.source.url ? <a className="focus-ring mt-1 inline-block break-words underline" href={entry.source.url} target="_blank" rel="noreferrer">View source: {entry.source.label}</a> : <p>{entry.source.label}</p>}</div></details></article>; }

function displayDate(value: string, includeYear = false) { return new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", ...(includeYear ? { year: "numeric" as const } : {}), timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)); }
function gameDateLabel(entry: UnifiedGameCalendarEntry) { if (entry.timing.kind === "date-range") return entry.timing.endsOn ? `${displayDate(entry.timing.startsOn)} – ${displayDate(entry.timing.endsOn, entry.timing.startsOn.slice(0, 4) !== entry.timing.endsOn.slice(0, 4))}` : displayDate(entry.timing.startsOn); const format = (value: string) => new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC", timeZoneName: "short" }).format(new Date(value)); return entry.timing.endsAt ? `${format(entry.timing.startsAt)} – ${format(entry.timing.endsAt)}` : format(entry.timing.startsAt); }
function dateHeading(date: string, today: string) { const days = Math.round((Date.parse(`${date}T12:00:00Z`) - Date.parse(`${today}T12:00:00Z`)) / 86_400_000); if (days === 0) return "Today"; if (days === 1) return "Tomorrow"; const value = new Date(`${date}T12:00:00Z`); if (days > 1 && days < 7) return new Intl.DateTimeFormat("en-GB", { weekday: "long", day: "numeric", month: "long", timeZone: "UTC" }).format(value); return new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(value); }
