import Link from "next/link";
import { notFound } from "next/navigation";
import { VersionShell } from "../../../components/version-shell";
import { isContentVersion } from "../../../lib/game-data";
import { loadPrimaryAdvice } from "../../../lib/player-advice/load";
import { getGuildRepository } from "../../../lib/guilds/factory";
import { removeCharacterAction, setPrimaryCharacterAction } from "../../../lib/characters/saved-actions";
import { refreshCharacterAction } from "../../../lib/characters/sync-actions";
import type { ContentVersion } from "../../../lib/types";
import type { PlayerAction } from "../../../lib/player-advice/types";
import { SessionPlanner } from "../../../components/session-planner";

export default async function DashboardPage({ params, searchParams }: { params: Promise<{ version: string }>; searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const { version: raw } = await params; if (!isContentVersion(raw)) notFound(); const version = raw as ContentVersion;
  const { user, characters, primary, advice, latestSync, latestAttempt, progress } = await loadPrimaryAdvice(); const query = await searchParams; const value = (key: string) => { const raw = query?.[key]; return Array.isArray(raw) ? raw[0] : raw; }; let guildCount = 0; try { guildCount = (await getGuildRepository().listForUser(user.id)).length; } catch { /* optional */ }
  return <VersionShell version={version}><main className="mx-auto min-h-[calc(100vh-148px)] max-w-[1240px] px-5 py-12 lg:px-8 lg:py-16"><header className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow mb-3">Player dashboard</div><h1 className="display text-5xl tracking-[-.04em]">Your preparation starts here.</h1><p className="mt-3 text-sm text-[var(--muted)]">Welcome back, {user.displayName}.</p></div><Link href={`/${version}/characters/connect`} className="button-primary">Add character</Link></header>{!primary ? <EmptyDashboard version={version} /> : <><PrimaryIdentity primary={primary} characters={characters} /><RefreshCard primary={primary} latestSync={latestSync} latestAttempt={latestAttempt} /><AdvicePanel version={version} advice={advice} /><SessionPlanner version={version} characterName={primary.characterName} advice={advice} synced={Boolean(latestSync)} duration={value("duration")} preference={value("preference")} /><RecentProgress progress={progress} /><section className="mt-8 grid gap-5 md:grid-cols-2"><GearStatus advice={advice} /><SavedCharacters version={version} characters={characters} /></section><div className="mt-8 grid gap-5 sm:grid-cols-2"><Status label="Guild memberships" value={String(guildCount)} /><div className="panel rounded-2xl p-5"><div className="eyebrow">Next raid</div><p className="mt-2 text-sm text-[var(--muted)]">Your next raid will appear here when available through a connected guild.</p></div></div></>}</main></VersionShell>;
}
function EmptyDashboard({ version }: { version: ContentVersion }) { return <div className="panel mt-10 rounded-2xl p-10"><div className="eyebrow">First step</div><h2 className="display mt-3 text-3xl">Choose a character to make this home yours.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--muted)]">Save a public profile, choose your primary, and keep your preparation in one place.</p><Link href={`/${version}/onboarding`} className="button-primary mt-6 inline-flex">Continue onboarding →</Link></div>; }
function PrimaryIdentity({ primary, characters }: { primary: any; characters: any[] }) { return <section className="mt-10 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border border-[var(--primary)]/50 bg-[var(--surface)] p-7"><div className="eyebrow">Primary character</div><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><h2 className="display text-4xl">{primary.characterName}</h2><p className="mt-2 text-sm text-[var(--muted)]">{primary.className} · level {primary.level} · {primary.realmName}</p><p className="mt-1 text-xs text-[var(--muted)]">{primary.race} · {primary.faction} · {primary.characterRealmType} realm · {primary.contentVersion.toUpperCase()} content</p></div><Link href={`/${primary.contentVersion}/character/${primary.characterRealmType}/${primary.region}/${primary.realmSlug}/${primary.normalizedCharacterName}`} className="button-secondary">Open profile</Link></div><div className="mt-6 flex flex-wrap gap-3">{characters.map((character) => character.isPrimary ? <span className="rounded-full bg-[var(--primary)] px-3 py-1.5 text-xs font-bold text-[var(--background)]" key={character.id}>{character.characterName} · Primary</span> : <form action={setPrimaryCharacterAction} key={character.id}><input type="hidden" name="characterId" value={character.id} /><button className="button-secondary" type="submit">Switch to {character.characterName}</button></form>)}</div></article><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1"><Status label="Saved characters" value={String(characters.length)} /><Status label="Advice status" value={primary.contentVersion === "era" ? "Era reference" : "Coming later"} /></div></section>; }
function RefreshCard({ primary, latestSync, latestAttempt }: { primary: any; latestSync?: any; latestAttempt?: any }) { const message = latestAttempt?.status === "failed" ? (latestAttempt.errorMessage ?? "We couldn’t refresh this character right now. Your previous gear data is still being used.") : latestSync ? `Updated ${relativeTime(latestSync.syncedAt)}.` : "Never refreshed — refresh to load current equipment."; return <section className="panel mt-8 flex flex-wrap items-center justify-between gap-5 rounded-2xl p-6"><div><div className="eyebrow">Character refresh</div><p className="mt-2 text-sm text-[var(--muted)]">{message}</p></div><form action={refreshCharacterAction}><input type="hidden" name="characterId" value={primary.id} /><button className="button-primary" type="submit">Refresh character</button></form></section>; }
function RecentProgress({ progress }: { progress?: any }) { if (!progress) return <section className="panel mt-8 rounded-2xl p-6"><div className="eyebrow">Recent progress</div><p className="mt-2 text-sm text-[var(--muted)]">Refresh your character to establish a gear baseline.</p></section>; if (progress.firstSync) return <section className="panel mt-8 rounded-2xl p-6"><div className="eyebrow">Recent progress</div><p className="mt-2 text-sm text-[var(--muted)]">First refresh established your equipment baseline.</p></section>; return <section className="panel mt-8 rounded-2xl p-6"><div className="eyebrow">Recent progress</div><p className="mt-2 text-sm text-[var(--muted)]">{progress.changedCount ? `${progress.upgrades} gear change${progress.upgrades === 1 ? "" : "s"} since your previous refresh.` : "No gear changes since your previous refresh."}{progress.completedTargets.length > 0 && ` ${progress.completedTargets.length} recommended target${progress.completedTargets.length === 1 ? "" : "s"} completed.`}</p></section>; }
function relativeTime(value: string) { const minutes = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 1 ? "just now" : minutes < 60 ? `${minutes} minute${minutes === 1 ? "" : "s"} ago` : `${Math.round(minutes / 60)} hour${Math.round(minutes / 60) === 1 ? "" : "s"} ago`; }
function AdvicePanel({ version, advice }: { version: ContentVersion; advice: any }) { return <section className="mt-8"><div className="mb-4"><div className="eyebrow">Personal priorities</div><h2 className="display mt-2 text-4xl">What should I do next?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">A small, explainable plan built from your current gear and the curated reference. No drop-rate or DPS promises.</p></div>{!advice?.supported ? <div className="panel rounded-2xl p-7"><p className="text-base text-[var(--muted)]">{advice?.limitations?.[0] ?? "Personal gear recommendations for this specialization are coming later."}</p></div> : <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">{advice.topActions[0] ? <TopActionCard version={version} action={advice.topActions[0]} /> : <div className="panel rounded-2xl p-7"><p className="text-base text-[var(--muted)]">{advice.limitations[0] ?? "Your remaining upgrades are mostly raid, crafted, or conditional targets."}</p></div>}<div className="space-y-4"><div className="eyebrow">Next best options</div>{advice.topActions.slice(1).concat(advice.secondaryActions.slice(0, 2)).map((action: PlayerAction) => <ActionCard key={action.id} version={version} action={action} />)}</div></div>}</section>; }
function TopActionCard({ version, action }: { version: ContentVersion; action: PlayerAction }) { const first = action.targets.find((target) => target.realistic) ?? action.targets[0]; return <article className="rounded-2xl border border-[var(--primary)]/60 bg-[var(--surface)] p-7"><div className="eyebrow">Top action · {action.type}</div><h3 className="display mt-2 text-3xl">{action.title}</h3><p className="mt-5 text-sm leading-6 text-[var(--muted)]">{action.reason}</p><div className="mt-6 rounded-xl border border-[var(--line)] p-4"><div className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted)]">Top target</div><p className="mt-2 text-lg font-semibold">{first?.itemName ?? "Reference opportunity"}</p><p className="mt-1 text-xs text-[var(--muted)]">{first?.slot} · {first?.realistic ? "Realistic target" : "Aspirational target"}</p></div><Link href={`/${version}/dashboard/actions/${action.id}`} className="button-primary mt-6 inline-flex">View upgrades →</Link></article>; }
function ActionCard({ version, action }: { version: ContentVersion; action: PlayerAction }) { return <Link href={`/${version}/dashboard/actions/${action.id}`} className="panel block rounded-xl p-5 focus-ring"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{action.title}</h3><span className="text-xs capitalize text-[var(--primary-light)]">{action.priority}</span></div><p className="mt-2 text-sm text-[var(--muted)]">{action.upgradeCount} realistic upgrade{action.upgradeCount === 1 ? "" : "s"}</p><p className="mt-3 text-xs leading-5 text-[var(--muted)]">{action.reason}</p></Link>; }
function GearStatus({ advice }: { advice: any }) { return <article className="panel rounded-2xl p-6"><div className="eyebrow">Gear status</div><h2 className="display mt-2 text-2xl">A grounded starting point.</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{advice?.supported ? `${advice.summary.evaluatedSlots} of 17 slots evaluated · ${advice.summary.actionableUpgradeCount} actionable opportunities.` : "Personal gear recommendations for this specialization are coming later."}</p></article>; }
function SavedCharacters({ version, characters }: { version: ContentVersion; characters: any[] }) { return <article className="panel rounded-2xl p-6"><div className="eyebrow">Saved characters</div><h2 className="display mt-2 text-2xl">Switch your focus.</h2><div className="mt-5 space-y-3">{characters.map((character) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--line)] p-3" key={character.id}><div><p className="text-sm font-semibold">{character.characterName}</p><p className="text-xs text-[var(--muted)]">{character.realmName} · {character.className}</p></div><div className="flex flex-wrap gap-2">{character.isPrimary ? <span className="eyebrow self-center">Primary</span> : <form action={setPrimaryCharacterAction}><input type="hidden" name="characterId" value={character.id} /><button className="button-secondary" type="submit">Set primary</button></form>}<form action={removeCharacterAction}><input type="hidden" name="characterId" value={character.id} /><button className="button-secondary" type="submit">Remove</button></form></div></div>)}</div><Link href={`/${version}/characters/connect`} className="button-secondary mt-5 inline-flex">Add another character</Link></article>; }
function Status({ label, value }: { label: string; value: string }) { return <div className="panel rounded-2xl p-5"><div className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted)]">{label}</div><div className="display mt-2 text-3xl">{value}</div></div>; }
