import { getCanonicalCuratedProfile } from "../lib/curated-gear/repository.ts";
import { publishReport } from "../lib/curated-gear/publish.ts";
import { normalizedItemMetadata } from "../lib/item-metadata/store.ts";
import { referenceSlots } from "../lib/curated-gear/data.ts";
import type { ReferenceItemEntry } from "../lib/curated-gear/types.ts";
import { arg } from "./curated-common.ts";

const profile = getCanonicalCuratedProfile();
const requestedPhase = arg("phase");
const set = profile.sets.find((entry) => requestedPhase ? entry.id === `era-fury-${requestedPhase === "pre-raid" ? "pre-raid" : requestedPhase}` : entry.id === "era-fury-pre-raid")!;
if (!set) throw new Error("Requested curated set was not found.");
const metadata = normalizedItemMetadata();
const allRows = referenceSlots.flatMap((slot) => (set.slots[slot] ?? []).map((entry, index) => ({ slot, rank: index + 1, entry })));
const inheritedRows = allRows.filter(({ entry }) => entry.origin === "inherited");
const overlayRows = allRows.filter(({ entry }) => entry.origin === "phase-1-addition");
const conflictSlots = new Set(allRows.filter(({ entry }) => entry.origin === "phase-1-addition").map(({ slot }) => slot).filter((slot) => allRows.some((row) => row.slot === slot && row.entry.origin === "inherited")));
const scope = arg("scope") ?? "all";
const rows = scope === "overlay" ? overlayRows : scope === "composition-conflicts" ? allRows.filter(({ slot }) => conflictSlots.has(slot)) : allRows;
const nameFor = (entry: ReferenceItemEntry) => metadata.get(entry.itemId)?.name ?? `Unknown item #${entry.itemId}`;
const sourceFor = (entry: ReferenceItemEntry) => entry.source.instance ?? entry.source.zone ?? entry.source.quest ?? entry.source.profession ?? entry.source.type;
const activityFor = (entry: ReferenceItemEntry) => entry.source.instance ?? entry.source.zone ?? entry.source.type;
const flagsFor = (entry: ReferenceItemEntry) => {
  const flags: string[] = [];
  const source = entry.source;
  const item = metadata.get(entry.itemId);
  if (entry.origin === "phase-1-addition") flags.push("OVERLAY DIRECT REVIEW: new Phase 1 recommendation.");
  if (source.type === "Raid" || entry.raidOrigin) flags.push("RAID SOURCE REVIEW: confirm boss/cache/quest semantics and loot context.");
  if (source.type === "World Drop") flags.push("ACCESSIBILITY REVIEW REQUIRED: rare/expensive world drop; do not assume best realistic target.");
  if (source.type === "Profession" || entry.professionRequirements?.length) flags.push("ACCESSIBILITY REVIEW REQUIRED: profession or crafted acquisition.");
  if (["Main Hand", "Off Hand / Shield"].includes(entry.slot)) flags.push("RACE/WEAPON REVIEW REQUIRED: practical value depends on weapon type, race skill, and paired weapon context.");
  if (item?.weapon || ["Main Hand", "Off Hand / Shield"].includes(entry.slot)) flags.push("WEAPON PAIRING REVIEW REQUIRED: verify hand legality and weapon-skill context.");
  if (["Edgemaster's Handguards", "Devilsaur Gauntlets", "Devilsaur Leggings", "Flameguard Gauntlets"].includes(nameFor(entry))) flags.push("CONTEXT REVIEW REQUIRED: weapon-skill or paired-set dependency.");
  if (entry.faction || entry.factionSources) flags.push("FACTION SOURCE REVIEW REQUIRED: verify faction-specific acquisition display.");
  if (entry.uniqueGroup || item?.uniqueType) flags.push("PAIRING REVIEW REQUIRED: unique/paired-slot interaction.");
  if (!source.type || (!source.instance && !source.zone && !source.quest && !source.profession && source.type !== "World Drop")) flags.push("SOURCE REVIEW REQUIRED: acquisition detail is incomplete.");
  return flags;
};
const reviewStatus = (entry: ReferenceItemEntry, flags: string[]) => entry.origin === "inherited" ? "published-inherited" : entry.reviewDecision === "approved-conditional" ? "approved-conditional" : entry.reviewDecision === "approved" ? "approved" : entry.provenance.verificationStatus === "disputed" ? "disputed" : flags.length ? "review-required" : "reviewed";
const uniqueStatus = (entry: ReferenceItemEntry) => entry.uniqueGroup ?? metadata.get(entry.itemId)?.uniqueType ?? "not unique";
const weaponDetail = (entry: ReferenceItemEntry) => { const weapon = metadata.get(entry.itemId)?.weapon; return weapon ? `${weapon.weaponType ?? "weapon"}; ${weapon.hand}; +${weapon.weaponSkillBonus ?? 0} skill` : "not a weapon"; };
console.log(`FURY ${set.name.toUpperCase()} DATA REVIEW (READ-ONLY)`);
console.log(`Set: ${set.name}`);
console.log(`Scope: ${scope}`);
const publication = publishReport(set);
console.log(`Status: ${set.status ?? "incomplete"}`);
console.log(`Publishable: ${publication.publishable ? "YES" : "NO"}`);
console.log(`Rows in scope: ${rows.length}; Unique items in set: ${new Set(allRows.map(({ entry }) => entry.itemId)).size}; Slots: ${referenceSlots.filter((slot) => (set.slots[slot]?.length ?? 0) > 0).length}/${referenceSlots.length}`);
console.log(`Inherited rows: ${inheritedRows.length}; Overlay rows: ${overlayRows.length}; Composition-conflict slots: ${conflictSlots.size}`);
for (const slot of referenceSlots) {
  const slotRows = rows.filter((candidate) => candidate.slot === slot);
  if (!slotRows.length) continue;
  console.log(`\n## ${slot}`);
  for (const row of slotRows) {
    const { entry } = row;
    const flags = flagsFor(entry);
    const item = metadata.get(entry.itemId);
    console.log(`${row.rank}. ${nameFor(entry)} (#${entry.itemId}) | origin=${entry.origin ?? "unmarked"} | tier=${entry.tier} | activity=${activityFor(entry)} | acquisition=${sourceFor(entry)} | boss/cache/quest=${entry.source.boss ?? entry.source.quest ?? entry.source.npc ?? entry.source.profession ?? "not stated"} | raidOrigin=${entry.raidOrigin ? "YES" : "NO"} | unique=${uniqueStatus(entry)} | weapon=${weaponDetail(entry)} | weaponContext=${entry.weaponContext ?? "none"} | conditionalEffects=${entry.conditionalEffects?.join("; ") ?? "none"} | factionSource=${entry.factionSources ? JSON.stringify(entry.factionSources) : "none"} | faction=${entry.faction ?? "none"} | race=${entry.raceNotes ?? "none"} | notes=${entry.notes ?? "none"} | provenance=${entry.provenanceId ?? "missing"}/${entry.provenance.verificationStatus} | decision=${entry.reviewDecision ?? "unrecorded"} | review=${reviewStatus(entry, flags)}`);
    for (const flag of flags) console.log(`   FLAG: ${flag}`);
  }
}
const flagged = rows.filter(({ entry }) => flagsFor(entry).length);
const overlayFlagged = overlayRows.filter(({ entry }) => reviewStatus(entry, flagsFor(entry)) === "review-required");
const hardBlockers = overlayRows.filter(({ entry }) => !entry.source?.type || !metadata.has(entry.itemId) || !entry.provenanceId || entry.provenance.verificationStatus === "disputed");
console.log("\n## REVIEW TOTALS");
console.log(`Inherited rows requiring no new review: ${inheritedRows.length}`);
console.log(`Overlay rows reviewed: ${overlayRows.length}`);
console.log(`Approved overlay rows: ${overlayRows.filter(({ entry }) => entry.reviewDecision === "approved").length}`);
console.log(`Approved-conditional overlay rows: ${overlayRows.filter(({ entry }) => entry.reviewDecision === "approved-conditional").length}`);
console.log(`Overlay rows review-required: ${overlayFlagged.length}`);
console.log(`Overlay rows disputed: ${overlayRows.filter(({ entry }) => entry.provenance.verificationStatus === "disputed").length}`);
console.log(`Composition conflicts requiring review: ${conflictSlots.size}`);
console.log(`Inherited published rows newly blocked: 0`);
console.log(`Actual data blockers: ${hardBlockers.length}`);
console.log(`Missing source: ${allRows.filter(({ entry }) => !entry.source?.type).length}`);
console.log(`Missing metadata: ${allRows.filter(({ entry }) => !metadata.has(entry.itemId)).length}`);
console.log(`Missing provenance: ${allRows.filter(({ entry }) => !entry.provenanceId || !entry.provenance.source || !entry.provenance.reviewedAt || !entry.provenance.reviewedBy).length}`);
console.log(`All slots represented: ${referenceSlots.every((slot) => (set.slots[slot]?.length ?? 0) > 0) ? "YES" : "NO"}`);
console.log(`Publishable: ${publishReport(set).publishable ? "YES" : "NO"}`);
console.log("\n## HUMAN REVIEW NOTES");
console.log("Inherited flags are informational because those rows are already approved in era-fury-pre-raid-v1. Overlay flags require direct human review; they do not change weights or rankings.");
