import bcrypt from "bcryptjs";
import { withTransaction } from "../lib/guilds/db.ts";

if (process.env.NODE_ENV === "production") throw new Error("E2E seed cannot run with NODE_ENV=production.");
if (!process.env.E2E_DATABASE_URL || process.env.E2E_DATABASE_URL === process.env.DATABASE_URL) throw new Error("E2E_DATABASE_URL must be isolated and must not equal DATABASE_URL.");
process.env.DATABASE_URL = process.env.E2E_DATABASE_URL;
const { default: _unused } = { default: undefined } as any;
const password = process.env.E2E_PASSWORD ?? "e2e-only-password-not-production";
const users = [
  ["owner", "e2e-owner@prepull.test", "owner", true], ["officer", "e2e-officer@prepull.test", "officer", true],
  ["assignedLeader", "e2e-assigned-leader@prepull.test", "raid-leader", true], ["unassignedLeader", "e2e-unassigned-leader@prepull.test", "raid-leader", true],
  ["memberA", "e2e-member-a@prepull.test", "member", true], ["memberB", "e2e-member-b@prepull.test", "member", true],
  ["inactive", "e2e-inactive@prepull.test", "member", true], ["disabled", "e2e-disabled@prepull.test", "member", false],
  ["guildBOwner", "e2e-guild-b-owner@prepull.test", "owner", true], ["guildBOfficer", "e2e-guild-b-officer@prepull.test", "officer", true], ["guildBMember", "e2e-guild-b-member@prepull.test", "member", true]
] as const;
await withTransaction(async (client) => {
  const ids = new Map<string, string>();
  for (const [key, email, _role, active] of users) {
    const row = await client.query("INSERT INTO users(email,password_hash,name,active) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO UPDATE SET password_hash=excluded.password_hash,name=excluded.name,active=excluded.active RETURNING id", [email, await bcrypt.hash(password, 4), `E2E ${key}`, active]); ids.set(key, row.rows[0].id);
  }
  const syntheticUserIds = [...ids.values()];
  // Player fixtures are deliberately reset for synthetic E2E users only. Keep
  // guild fixtures and all non-E2E personal data untouched.
  await client.query("DELETE FROM character_sync_items WHERE sync_id IN (SELECT syncs.id FROM character_syncs syncs JOIN user_characters characters ON characters.id=syncs.user_character_id WHERE characters.user_id=ANY($1::uuid[]))", [syntheticUserIds]);
  await client.query("DELETE FROM character_syncs WHERE user_character_id IN (SELECT id FROM user_characters WHERE user_id=ANY($1::uuid[]))", [syntheticUserIds]);
  await client.query("DELETE FROM user_characters WHERE user_id=ANY($1::uuid[])", [syntheticUserIds]);
  const activePlayerRows = await client.query<{ count: string }>("SELECT count(*)::text AS count FROM user_characters WHERE user_id=ANY($1::uuid[]) AND archived_at IS NULL", [syntheticUserIds]);
  const scopedSyncRows = await client.query<{ count: string }>("SELECT count(*)::text AS count FROM character_syncs syncs JOIN user_characters characters ON characters.id=syncs.user_character_id WHERE characters.user_id=ANY($1::uuid[])", [syntheticUserIds]);
  const orphanSyncRows = await client.query<{ count: string }>("SELECT count(*)::text AS count FROM character_syncs syncs WHERE NOT EXISTS (SELECT 1 FROM user_characters characters WHERE characters.id=syncs.user_character_id)");
  const orphanItemRows = await client.query<{ count: string }>("SELECT count(*)::text AS count FROM character_sync_items items WHERE NOT EXISTS (SELECT 1 FROM character_syncs syncs WHERE syncs.id=items.sync_id)");
  if (activePlayerRows.rows[0].count !== "0" || scopedSyncRows.rows[0].count !== "0" || orphanSyncRows.rows[0].count !== "0" || orphanItemRows.rows[0].count !== "0") throw new Error(`E2E player reset verification failed: active=${activePlayerRows.rows[0].count}, scopedSyncs=${scopedSyncRows.rows[0].count}, orphanSyncs=${orphanSyncRows.rows[0].count}, orphanItems=${orphanItemRows.rows[0].count}`);
  const owner = await client.query<{ count: string }>("SELECT count(*)::text AS count FROM user_characters WHERE user_id=$1 AND archived_at IS NULL", [ids.get("owner")]);
  console.log(JSON.stringify({ playerReset: { syntheticUsers: syntheticUserIds.length, ownerActiveCharacters: Number(owner.rows[0].count), scopedSyncs: Number(scopedSyncRows.rows[0].count), orphanSyncs: Number(orphanSyncRows.rows[0].count), orphanItems: Number(orphanItemRows.rows[0].count) } }));
  const guild = async (name: string, owner: string, version: "era" | "tbc") => {
    const found = await client.query("SELECT id FROM guilds WHERE name=$1 AND owner_user_id=$2 AND archived_at IS NULL", [name, ids.get(owner)]);
    return found.rows[0] ?? (await client.query("INSERT INTO guilds(name,region,realm_slug,realm_name,character_realm_type,content_version,faction,description,owner_user_id) VALUES($1,'eu','firemaw','Firemaw','era',$2,'Horde','Synthetic E2E guild.', $3) RETURNING id", [name, version, ids.get(owner)])).rows[0];
  };
  const guildA = await guild("E2E Guild A", "owner", "era"); const guildB = await guild("E2E Guild B", "guildBOwner", "tbc");
  const caps = JSON.stringify(["import-roster", "manage-roster", "manage-raid", "manage-assignments", "manage-signup-overrides", "manage-permissions"]);
  const addMembership = async (guildId: string, key: string, role: string, active = true, capabilities = "[]") => client.query("INSERT INTO guild_workspace_memberships(guild_id,user_id,role,capabilities,active) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guild_id,user_id) DO UPDATE SET role=excluded.role,capabilities=excluded.capabilities,active=excluded.active", [guildId, ids.get(key), role, capabilities, active]);
  await addMembership(guildA.id, "owner", "owner", true, caps); await addMembership(guildA.id, "officer", "officer", true, caps); await addMembership(guildA.id, "assignedLeader", "raid-leader", true, JSON.stringify(["manage-raid", "manage-assignments"])); await addMembership(guildA.id, "unassignedLeader", "raid-leader"); await addMembership(guildA.id, "memberA", "member"); await addMembership(guildA.id, "memberB", "member"); await addMembership(guildA.id, "inactive", "member", false); await addMembership(guildB.id, "guildBOwner", "owner", true, caps); await addMembership(guildB.id, "guildBOfficer", "officer", true, caps); await addMembership(guildB.id, "guildBMember", "member");
  const members: Record<string, string> = {};
  for (let i = 1; i <= 14; i++) { const key = `c${i}`; const name = `E2E Character ${i}`; const row = await client.query("INSERT INTO guild_members(guild_id,character_id,character_name,class_name,spec,level,race,faction,realm,region,realm_type,content_version,role,readiness,active) VALUES($1,$2,$3,$4,$5,60,'Orc','Horde','Firemaw','eu','era','era',$6,$7,$8) ON CONFLICT(guild_id,character_id) DO UPDATE SET active=excluded.active RETURNING id", [guildA.id, `e2e-${key}`, name, i === 14 ? "Mage" : "Warrior", i === 14 ? "Arcane" : "Fury", i % 3 === 0 ? "Healer" : "DPS", i % 5 === 0 ? "needs-review" : "ready", i !== 13]); members[key] = row.rows[0].id; }
  const bMember = await client.query("INSERT INTO guild_members(guild_id,character_id,character_name,class_name,spec,level,race,faction,realm,region,realm_type,content_version,role,readiness) VALUES($1,'guild-b-character','Guild B Character','Warrior','Fury',60,'Orc','Horde','Firemaw','eu','era','tbc','DPS','ready') ON CONFLICT(guild_id,character_id) DO UPDATE SET character_name=excluded.character_name RETURNING id", [guildB.id]);
  await client.query("INSERT INTO guild_main_alt_relationships(guild_id,main_member_id,alt_member_id) VALUES($1,$2,$3) ON CONFLICT(guild_id,alt_member_id) DO NOTHING", [guildA.id, members.c1, members.c2]);
  await client.query("INSERT INTO guild_member_links(guild_member_id,user_id,status,verification_method) VALUES($1,$2,'approved','officer-verified') ON CONFLICT(guild_member_id,user_id) DO UPDATE SET status='approved'", [members.c1, ids.get("memberA")]);
  await client.query("INSERT INTO guild_member_links(guild_member_id,user_id,status,verification_method) VALUES($1,$2,'pending','officer-verified') ON CONFLICT(guild_member_id,user_id) DO UPDATE SET status='pending'", [members.c3, ids.get("memberB")]);
  const raid = async (name: string, leader: string | null) => { const found = await client.query("SELECT id FROM raid_events WHERE guild_id=$1 AND name=$2", [guildA.id, name]); return found.rows[0]?.id ?? (await client.query("INSERT INTO raid_events(guild_id,name,instance,starts_at,duration_minutes,status,raid_leader_user_id) VALUES($1,$2,'Molten Core',now()+interval '1 day',180,'open',$3) RETURNING id", [guildA.id, name, leader ? ids.get(leader) : null])).rows[0].id; };
  const raidA = await raid("E2E Molten Core", "assignedLeader"); const raidA2 = await raid("E2E Unassigned Raid", "officer"); const foundB = await client.query("SELECT id FROM raid_events WHERE guild_id=$1 AND name='Guild B Raid'", [guildB.id]); const raidB = foundB.rows[0]?.id ?? (await client.query("INSERT INTO raid_events(guild_id,name,instance,starts_at,duration_minutes,status) VALUES($1,'Guild B Raid','Molten Core',now()+interval '2 day',180,'open') RETURNING id", [guildB.id])).rows[0].id;
  for (const [key, status] of [["c1", "accepted"], ["c2", "tentative"], ["c3", "unavailable"], ["c4", "late"]] as const) await client.query("INSERT INTO raid_signups(raid_event_id,guild_member_id,status,member_status,effective_status,updated_by_user_id) VALUES($1,$2,'pending',$3,$3,$4) ON CONFLICT(raid_event_id,guild_member_id) DO UPDATE SET member_status=excluded.member_status,effective_status=excluded.effective_status", [raidA, members[key], status, ids.get("memberA")]);
  await client.query("UPDATE raid_signups SET override_actor_user_id=$1,override_at=now(),override_reason='E2E officer override',effective_status='accepted' WHERE raid_event_id=$2 AND guild_member_id=$3", [ids.get("officer"), raidA, members.c2]);
  for (const [key, state, group, role] of [["c1", "selected", "Group 1", "DPS"], ["c2", "selected", "Group 1", "DPS"], ["c3", "selected", "Group 2", "Healer"], ["c4", "bench", null, ""]] as const) await client.query("INSERT INTO raid_roster_entries(raid_event_id,guild_member_id,roster_state,group_name,role_name) VALUES($1,$2,$3,$4,$5) ON CONFLICT(raid_event_id,guild_member_id) DO UPDATE SET roster_state=excluded.roster_state,group_name=excluded.group_name,role_name=excluded.role_name", [raidA, members[key], state, group, role]);
  const foundSection = await client.query("SELECT id FROM raid_assignments WHERE raid_event_id=$1 AND label='E2E assignments'", [raidA]); const section = foundSection.rows[0]?.id ?? (await client.query("INSERT INTO raid_assignments(raid_event_id,label,detail,category,section,position,section_position) VALUES($1,'E2E assignments','Synthetic section','interrupt','Bosses',0,0) RETURNING id", [raidA])).rows[0].id; await client.query("INSERT INTO raid_assignment_assignees(assignment_id,guild_member_id) VALUES($1,$2),($1,$3) ON CONFLICT DO NOTHING", [section, members.c1, members.c2]); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'raid_event',$3,'raid.assignment-edit',$4)", [ids.get("officer"), guildA.id, raidA, JSON.stringify({ synthetic: true })]);
  console.log(JSON.stringify({ guildA: guildA.id, guildB: guildB.id, raidA, raidA2, raidB, guildBMember: bMember.rows[0].id, ownerEmail: users[0][1], password }));
});
