import type { PlayerAction, PlayerAdvice, PlayerTarget } from "../player-advice/types.ts";
import type { SessionDuration, SessionPlan, SessionPlanStep, SessionPreference, SessionSuitability } from "./types.ts";

const durationValues: SessionDuration[] = ["30m", "60m", "90m", "120m"];
const preferenceValues: SessionPreference[] = ["best-progress", "dungeons", "solo-prep", "raid-prep"];
export const isSessionDuration = (value: string | undefined): value is SessionDuration => durationValues.includes(value as SessionDuration);
export const isSessionPreference = (value: string | undefined): value is SessionPreference => preferenceValues.includes(value as SessionPreference);

const priorityWeight = (priority: PlayerAction["priority"]) => priority === "high" ? 3 : priority === "medium" ? 2 : 1;
const matchesPreference = (action: PlayerAction, preference: SessionPreference) => preference === "dungeons" ? action.type === "dungeon" : preference === "solo-prep" ? ["crafting", "vendor", "quest", "pvp", "other"].includes(action.type) : preference === "raid-prep" ? action.view === "realistic" && action.type !== "raid" : true;
const stepFor = (action: PlayerAction, duration: SessionDuration): SessionPlanStep => {
  const instance = action.type === "dungeon" || action.type === "raid";
  let suitability: SessionSuitability = instance ? (duration === "30m" ? "longer-session" : duration === "60m" ? "possible" : "good-fit") : action.type === "crafting" || action.type === "vendor" || action.type === "quest" ? "preparation" : "good-fit";
  let reason = action.reason;
  if (duration === "30m" && instance) reason = "Worth continuing if you already have a group; this may require a longer session.";
  else if (duration === "90m" && instance) reason = "Strong main activity for a longer play session.";
  else if (duration === "120m" && instance) reason = "You have enough time to focus on one of your larger progression activities.";
  return { actionId: action.id, title: action.title, type: action.type, reason, targets: action.targets.filter((target) => target.realistic), suitability };
};
const targetStep = (target: PlayerTarget): SessionPlanStep => ({ title: target.itemName, type: target.sourceType === "Profession" ? "crafting" : target.sourceType === "Quest" ? "quest" : target.sourceType === "Vendor" ? "vendor" : "other", reason: "Longer-term target from the current curated reference.", targets: [target], suitability: "preparation" });

export function buildSessionPlan({ advice, synced, duration, preference }: { advice?: PlayerAdvice; synced: boolean; duration: SessionDuration; preference: SessionPreference }): SessionPlan {
  const plan: SessionPlan = { characterId: advice?.characterId ?? "", requestedDuration: duration, preference, secondaryActions: [], longerTermTargets: [], limitations: [] };
  if (!synced) { plan.limitations.push("Refresh your character before building a personalized session plan."); return plan; }
  if (!advice?.supported) { plan.limitations.push("Session planning based on gear upgrades isn't available for this specialization yet."); return plan; }
  const actions = [...advice.topActions, ...advice.secondaryActions].filter((action, index, list) => list.findIndex((candidate) => candidate.id === action.id) === index && action.view === "realistic");
  const matching = actions.filter((action) => matchesPreference(action, preference));
  const ranked = [...matching].sort((left, right) => (priorityWeight(right.priority) + Math.min(right.upgradeCount, 3) * 0.25) - (priorityWeight(left.priority) + Math.min(left.upgradeCount, 3) * 0.25));
  const fallback = ranked.length ? ranked : preference === "dungeons" ? [] : actions;
  const steps = fallback.map((action) => stepFor(action, duration));
  plan.primaryAction = steps[0]; plan.secondaryActions = steps.slice(1, 3);
  if (!plan.primaryAction && preference === "dungeons") plan.limitations.push("You don't currently have a strong dungeon upgrade path.");
  if (!plan.primaryAction && !plan.limitations.length) plan.limitations.push("There isn't a strong actionable activity to prioritize right now.");
  plan.longerTermTargets = advice.secondaryTargets.slice(0, 3).map(targetStep);
  return plan;
}

export function sessionPlanText(characterName: string, plan: SessionPlan) {
  const lines = [`PrePull plan — ${characterName}`];
  if (plan.primaryAction) { lines.push(`Main goal: ${plan.primaryAction.title}`); if (plan.primaryAction.targets.length) lines.push("Targets:", ...plan.primaryAction.targets.map((target) => `- ${target.itemName}`)); }
  if (plan.secondaryActions.length) lines.push("Then:", ...plan.secondaryActions.map((step) => `- ${step.title}`));
  if (plan.longerTermTargets.length) lines.push("Longer term:", ...plan.longerTermTargets.map((step) => `- ${step.title}`));
  if (plan.limitations.length && !plan.primaryAction) lines.push(plan.limitations[0]);
  lines.push("Generated by PrePull"); return lines.join("\n");
}
