"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "./auth.ts";
import { getGuildRepository } from "./factory.ts";
import type { CreateGuildInput, CreateRaidInput, GuildMember, RaidAssignment, RaidGroup } from "./types.ts";
import { applyCsvImport } from "./csv-apply.ts";
import { updateGuildSettings, setCapabilityOverride, activateMember, removeMember } from "./settings.ts";
import { changeRole, deactivateMember } from "./security.ts";
import { transferOwnership } from "./workflows.ts";
import { saveMemberSignup, setSignupOverride, clearSignupOverride, saveRosterState, setRosterLock, mutateAssignment } from "./raid-workflows.ts";

const text = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
export async function createGuildAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guild = await repository.createGuild(user.id, { name: text(form, "name"), region: text(form, "region") as CreateGuildInput["region"], realmSlug: text(form, "realmSlug"), realmName: text(form, "realmName"), characterRealmType: text(form, "characterRealmType") as CreateGuildInput["characterRealmType"], contentVersion: text(form, "contentVersion") as CreateGuildInput["contentVersion"], faction: text(form, "faction") as CreateGuildInput["faction"], description: text(form, "description") }); revalidatePath(`/${guild.contentVersion}/guilds`); }
export async function importGuildAction(form: FormData) { const user = await requireUser(); const guild = await getGuildRepository().importGuild(user.id, JSON.parse(text(form, "payload"))); revalidatePath(`/${guild.contentVersion}/guilds`); }
export async function addMemberAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const member: Omit<GuildMember, "id" | "joinedAt"> = { characterId: text(form, "characterId"), characterName: text(form, "characterName"), className: text(form, "className"), spec: text(form, "spec"), level: Number(text(form, "level") || 60), race: text(form, "race"), faction: text(form, "faction") as GuildMember["faction"], realm: text(form, "realm"), region: text(form, "region") as GuildMember["region"], realmType: text(form, "realmType") as GuildMember["realmType"], contentVersion: text(form, "contentVersion") as GuildMember["contentVersion"], role: text(form, "role"), readiness: text(form, "readiness") as GuildMember["readiness"] }; const guild = (await repository.getWorkspace(user.id, guildId)).guild; await repository.addMember(user.id, guildId, member); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function createRaidAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; await repository.createRaid(user.id, guildId, { name: text(form, "name"), instance: text(form, "instance"), startsAt: text(form, "startsAt"), durationMinutes: Number(text(form, "durationMinutes") || 180) } as CreateRaidInput); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function signupAction(form: FormData) { const user = await requireUser(); const guildId = text(form, "guildId"); await saveMemberSignup(user,guildId,text(form,"eventId"),text(form,"characterId"),text(form,"status"),text(form,"preferredRole"),text(form,"alternateRole"),text(form,"note")); revalidatePath(`/era/guilds/${guildId}`); revalidatePath(`/tbc/guilds/${guildId}`); }
export async function selectRosterAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; await repository.selectRoster(user.id, guildId, text(form, "eventId"), form.getAll("characterId").map(String)); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function saveGroupAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; const group: RaidGroup = { id: text(form, "groupId"), name: text(form, "groupName"), memberCharacterIds: form.getAll("memberCharacterId").map(String) }; await repository.saveGroup(user.id, guildId, text(form, "eventId"), group); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function saveAssignmentAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); const assignment: RaidAssignment={id:text(form,"assignmentId"),characterId:text(form,"characterId"),characterIds:form.getAll("assigneeId").map(String),label:text(form,"label"),detail:text(form,"detail"),category:text(form,"category"),section:text(form,"section"),position:Number(text(form,"position")||0)}; await mutateAssignment(user,guildId,text(form,"eventId"),Number(text(form,"assignmentVersion")||1),text(form,"operation") as "create"|"edit"|"delete",assignment); revalidatePath(`/era/guilds/${guildId}`); revalidatePath(`/tbc/guilds/${guildId}`); }
export async function saveSignupOverrideAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await setSignupOverride(user,guildId,text(form,"eventId"),text(form,"memberId"),text(form,"effectiveStatus"),text(form,"reason")); revalidatePath(`/era/guilds/${guildId}`); revalidatePath(`/tbc/guilds/${guildId}`); }
export async function clearSignupOverrideAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await clearSignupOverride(user,guildId,text(form,"eventId"),text(form,"memberId")); revalidatePath(`/era/guilds/${guildId}`); revalidatePath(`/tbc/guilds/${guildId}`); }
export async function saveRosterStateAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); const groups:Record<string,string[]>={}; for(const value of form.getAll("groupEntry").map(String)){const [group,id]=value.split(":");if(group&&id)(groups[group]??=[]).push(id);} const roles:Record<string,string>={}; for(const value of form.getAll("roleEntry").map(String)){const [id,role]=value.split(":");if(id)roles[id]=role??"";} await saveRosterState(user,guildId,text(form,"eventId"),Number(text(form,"rosterVersion")||1),{selected:form.getAll("selectedId").map(String),benched:form.getAll("benchId").map(String),groups,roles}); revalidatePath(`/era/guilds/${guildId}`); revalidatePath(`/tbc/guilds/${guildId}`); }
export async function toggleRosterLockAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await setRosterLock(user,guildId,text(form,"eventId"),Number(text(form,"rosterVersion")||1),text(form,"locked")==="true"); revalidatePath(`/era/guilds/${guildId}`); revalidatePath(`/tbc/guilds/${guildId}`); }
export async function applyCsvImportAction(form: FormData) { const user = await requireUser(); const guildId = text(form,"guildId"); await applyCsvImport(user,guildId,text(form,"csv"),text(form,"policy") as "mark-inactive"|"leave-unchanged"); revalidatePath(`/era/guilds/${guildId}`); revalidatePath(`/tbc/guilds/${guildId}`); }
export async function updateGuildSettingsAction(form: FormData) { const user = await requireUser(); const guildId = text(form,"guildId"); await updateGuildSettings(user,guildId,{name:text(form,"name"),description:text(form,"description"),raidTimezone:text(form,"raidTimezone"),defaultContentVersion:text(form,"defaultContentVersion") as "era"|"tbc",defaultAvailabilityPhase:Number(text(form,"defaultAvailabilityPhase")||6),internalNotes:text(form,"internalNotes")}); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function changeMemberRoleAction(form: FormData) { const user = await requireUser(); const guildId=text(form,"guildId"); await changeRole(user,guildId,text(form,"targetUserId"),text(form,"role") as "owner"|"officer"|"raid-leader"|"member"); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function setCapabilityOverrideAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await setCapabilityOverride(user,guildId,text(form,"targetUserId"),text(form,"capability") as any,text(form,"mode") as "inherit"|"grant"|"revoke"); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function deactivateMemberAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await deactivateMember(user,guildId,text(form,"targetUserId")); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function activateMemberAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await activateMember(user,guildId,text(form,"targetUserId")); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function removeMemberAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await removeMember(user,guildId,text(form,"targetUserId")); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function transferOwnershipAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); await transferOwnership(user,guildId,text(form,"targetUserId"),text(form,"confirmation")); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function decideClaimAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); const { decideClaim }=await import("./workflows.ts"); await decideClaim(user,guildId,text(form,"claimId"),text(form,"decision") as "approved"|"rejected"|"revoked",text(form,"reason")); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
export async function submitClaimAction(form: FormData) { const user=await requireUser(); const guildId=text(form,"guildId"); const { submitClaim }=await import("./workflows.ts"); await submitClaim(user,guildId,text(form,"memberId")); revalidatePath(`/era/guilds/${guildId}/settings`); revalidatePath(`/tbc/guilds/${guildId}/settings`); }
