"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "./auth.ts";
import { getGuildRepository } from "./factory.ts";
import type { CreateGuildInput, CreateRaidInput, GuildMember, RaidAssignment, RaidGroup, SignupStatus } from "./types.ts";

const text = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
export async function createGuildAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guild = await repository.createGuild(user.id, { name: text(form, "name"), region: text(form, "region") as CreateGuildInput["region"], realmSlug: text(form, "realmSlug"), realmName: text(form, "realmName"), characterRealmType: text(form, "characterRealmType") as CreateGuildInput["characterRealmType"], contentVersion: text(form, "contentVersion") as CreateGuildInput["contentVersion"], faction: text(form, "faction") as CreateGuildInput["faction"], description: text(form, "description") }); revalidatePath(`/${guild.contentVersion}/guilds`); }
export async function importGuildAction(form: FormData) { const user = await requireUser(); const guild = await getGuildRepository().importGuild(user.id, JSON.parse(text(form, "payload"))); revalidatePath(`/${guild.contentVersion}/guilds`); }
export async function addMemberAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const member: Omit<GuildMember, "id" | "joinedAt"> = { characterId: text(form, "characterId"), characterName: text(form, "characterName"), className: text(form, "className"), spec: text(form, "spec"), level: Number(text(form, "level") || 60), race: text(form, "race"), faction: text(form, "faction") as GuildMember["faction"], realm: text(form, "realm"), region: text(form, "region") as GuildMember["region"], realmType: text(form, "realmType") as GuildMember["realmType"], contentVersion: text(form, "contentVersion") as GuildMember["contentVersion"], role: text(form, "role"), readiness: text(form, "readiness") as GuildMember["readiness"] }; const guild = (await repository.getWorkspace(user.id, guildId)).guild; await repository.addMember(user.id, guildId, member); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function createRaidAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; await repository.createRaid(user.id, guildId, { name: text(form, "name"), instance: text(form, "instance"), startsAt: text(form, "startsAt"), durationMinutes: Number(text(form, "durationMinutes") || 180) } as CreateRaidInput); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function signupAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; await repository.setSignup(user.id, guildId, text(form, "eventId"), text(form, "characterId"), text(form, "status") as SignupStatus, text(form, "note")); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function selectRosterAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; await repository.selectRoster(user.id, guildId, text(form, "eventId"), form.getAll("characterId").map(String)); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function saveGroupAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; const group: RaidGroup = { id: text(form, "groupId"), name: text(form, "groupName"), memberCharacterIds: form.getAll("memberCharacterId").map(String) }; await repository.saveGroup(user.id, guildId, text(form, "eventId"), group); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
export async function saveAssignmentAction(form: FormData) { const user = await requireUser(); const repository = getGuildRepository(); const guildId = text(form, "guildId"); const guild = (await repository.getWorkspace(user.id, guildId)).guild; const assignment: RaidAssignment = { id: text(form, "assignmentId"), characterId: text(form, "characterId"), label: text(form, "label"), detail: text(form, "detail") }; await repository.saveAssignment(user.id, guildId, text(form, "eventId"), assignment); revalidatePath(`/${guild.contentVersion}/guilds/${guildId}`); }
