import { query, withTransaction } from "./db.ts";
import { GuildDomainError } from "./errors.ts";
import { hasCapability } from "./permissions.ts";
import { previewGuildCsv, csvRowToMember, type CsvPreview } from "./csv.ts";
type Actor={id:string}; type Policy="mark-inactive"|"leave-unchanged";
async function canImport(actor:Actor,guildId:string){const row=(await query("SELECT * FROM guild_workspace_memberships WHERE user_id=$1 AND guild_id=$2 AND active=true",[actor.id,guildId])).rows[0];if(!row)throw new GuildDomainError("FORBIDDEN","Active guild membership is required.");const m={id:row.id,guildId:row.guild_id,userId:row.user_id,role:row.role,capabilities:row.capabilities??[],active:true,createdAt:row.created_at,updatedAt:row.updated_at};if(!hasCapability(m,"import-roster"))throw new GuildDomainError("FORBIDDEN","Roster import permission is required.");}
export type CsvImportSummary={added:number;updated:number;unchanged:number;markedInactive:number;conflicts:number;invalidRows:number;duplicateRows:number;mainAltConflicts:number;linkedCharacterConflicts:number};
export function previewImport(csv:string):CsvPreview{return previewGuildCsv(csv)}
export async function applyCsvImport(actor:Actor,guildId:string,csv:string,policy:Policy):Promise<CsvImportSummary>{await canImport(actor,guildId);const preview=previewGuildCsv(csv);if(preview.issues.length)throw new GuildDomainError("INVALID_IMPORT",`CSV has ${preview.issues.length} validation issue(s).`);return withTransaction(async(client)=>{const guild=(await client.query("SELECT * FROM guilds WHERE id=$1 AND archived_at IS NULL",[guildId])).rows[0];if(!guild)throw new GuildDomainError("NOT_FOUND","Guild was not found.");const existing=(await client.query("SELECT * FROM guild_members WHERE guild_id=$1",[guildId])).rows;const by=new Map(existing.map(row=>[row.character_id,row]));const incoming=new Set<string>();const s:CsvImportSummary={added:0,updated:0,unchanged:0,markedInactive:0,conflicts:0,invalidRows:0,duplicateRows:preview.duplicateNames.length,mainAltConflicts:0,linkedCharacterConflicts:0};for(const row of preview.rows){const member=csvRowToMember(row,{realmType:guild.character_realm_type,contentVersion:guild.content_version});incoming.add(member.characterId);const found=by.get(member.characterId);if(found){const changed=found.character_name!==member.characterName||found.guild_rank!==row.guildRank||found.role!==member.role||found.main_name!==row.mainName;if(!changed)s.unchanged++;else{await client.query("UPDATE guild_members SET character_name=$1,guild_rank=$2,role=$3,main_name=$4,active=true,inactive_at=NULL,updated_at=now() WHERE id=$5",[member.characterName,row.guildRank,member.role,row.mainName,found.id]);s.updated++;}}else{if(row.mainName&&row.mainName===row.name){s.mainAltConflicts++;continue;}await client.query("INSERT INTO guild_members(guild_id,character_id,character_name,class_name,spec,level,race,faction,realm,region,realm_type,content_version,role,readiness,guild_rank,main_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'unknown',$14,$15)",[guildId,member.characterId,member.characterName,member.className,member.spec,member.level,member.race,member.faction,member.realm,member.region,member.realmType,member.contentVersion,member.role,row.guildRank,row.mainName]);s.added++;}}if(policy==="mark-inactive")for(const row of existing)if(!incoming.has(row.character_id)&&row.active){await client.query("UPDATE guild_members SET active=false,inactive_at=now(),updated_at=now() WHERE id=$1",[row.id]);s.markedInactive++;}await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'guild',$2,'roster.import-applied',$3)",[actor.id,guildId,JSON.stringify(s)]);return s;});}
