import type { Faction, Region } from "../types.ts";
import type { GuildMember } from "./types.ts";
export type GuildCsvRow = { name: string; region: Region; realm: string; className: string; level: number; faction: Faction; guildRank: string; mainName: string; preferredRole: string; notes: string };
export type CsvIssue = { row: number; message: string };
export type CsvPreview = { rows: GuildCsvRow[]; issues: CsvIssue[]; duplicateNames: string[] };
const headers = ["name", "region", "realm", "class", "level", "faction", "guildRank", "mainName", "preferredRole", "notes"];
function cells(line: string) { const result: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"' && line[index + 1] === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { result.push(value); value = ""; } else value += char; } result.push(value); return result.map((entry) => entry.trim()); }
export function previewGuildCsv(csv: string): CsvPreview { const lines = csv.replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim()); if (!lines.length) return { rows: [], issues: [{ row: 1, message: "CSV is empty." }], duplicateNames: [] }; const actual = cells(lines[0]); const issues: CsvIssue[] = []; if (actual.length !== headers.length || actual.some((header, index) => header !== headers[index])) issues.push({ row: 1, message: `Expected header: ${headers.join(",")}` }); const rows: GuildCsvRow[] = []; for (let index = 1; index < lines.length; index += 1) { const values = cells(lines[index]); if (values.length !== headers.length) { issues.push({ row: index + 1, message: `Expected ${headers.length} columns, received ${values.length}.` }); continue; } const [name, region, realm, className, level, faction, guildRank, mainName, preferredRole, notes] = values; if (!name || !realm || !className) issues.push({ row: index + 1, message: "Name, realm, and class are required." }); if (!/^(eu|us)$/.test(region)) issues.push({ row: index + 1, message: "Region must be eu or us." }); if (!/^\d+$/.test(level)) issues.push({ row: index + 1, message: "Level must be an integer." }); if (!/^(Alliance|Horde)$/.test(faction)) issues.push({ row: index + 1, message: "Faction must be Alliance or Horde." }); rows.push({ name, region: region as Region, realm, className, level: Number(level), faction: faction as Faction, guildRank, mainName, preferredRole, notes }); } const counts = new Map<string, number>(); for (const row of rows) counts.set(row.name.toLowerCase(), (counts.get(row.name.toLowerCase()) ?? 0) + 1); const duplicateNames = [...counts.entries()].filter(([, count]) => count > 1).map(([name]) => name); return { rows, issues: [...issues, ...duplicateNames.map((name) => ({ row: 0, message: `Duplicate character name: ${name}.` }))], duplicateNames }; }
export function csvRowToMember(row: GuildCsvRow, guild: { realmType: GuildMember["realmType"]; contentVersion: GuildMember["contentVersion"] }): Omit<GuildMember, "id" | "joinedAt"> { return { characterId: `${row.region}:${row.realm.toLowerCase()}:${row.name.toLowerCase()}`, characterName: row.name, className: row.className, spec: "", level: row.level, race: "", faction: row.faction, realm: row.realm, region: row.region, realmType: guild.realmType, contentVersion: guild.contentVersion, role: row.preferredRole || "DPS", readiness: "unknown" }; }
