import { createHash } from "node:crypto";
import { query, withTransaction } from "./db.ts";
import { GuildDomainError } from "./errors.ts";
import { hasCapability } from "./permissions.ts";
import { previewGuildCsv, csvRowToMember, type GuildCsvRow } from "./csv.ts";
import { classifyMainAltRows, normalizedName, safeConflictSummary, validateRelationshipGraph, type MainAltConflict, type MainAltDecision } from "./main-alt.ts";

type Actor = { id: string }; type Policy = "mark-inactive" | "leave-unchanged";
type Decision = { decision: MainAltDecision; targetMemberId?: string };
export type MainAltPreview = { token: string; rosterVersion: number; rows: GuildCsvRow[]; conflicts: MainAltConflict[]; summary: { totalRows:number; newCharacters:number; updatedCharacters:number; unchangedCharacters:number; absentCharacters:number; invalidRows:number; duplicateRows:number; mainAltConflicts:number; linkedCharacterConflicts:number } };

async function importer(client: any, actor: Actor, guildId: string) {
  const row = (await client.query("SELECT m.*,g.roster_version FROM guild_workspace_memberships m JOIN guilds g ON g.id=m.guild_id WHERE m.user_id=$1 AND m.guild_id=$2 AND m.active=true", [actor.id, guildId])).rows[0];
  if (!row) throw new GuildDomainError("FORBIDDEN", "Active guild membership is required.");
  const membership = { id: row.id, guildId, userId: row.user_id, role: row.role, capabilities: row.capabilities ?? [], revokedCapabilities: row.revoked_capabilities ?? [], active: true, createdAt: row.created_at, updatedAt: row.updated_at } as any;
  if (!hasCapability(membership, "import-roster")) throw new GuildDomainError("FORBIDDEN", "Roster import permission is required.");
  return row;
}
function token(csv: string, version: number) { return createHash("sha256").update(`${version}:${csv}`).digest("hex"); }
function rowsForConflicts(rows: GuildCsvRow[]) { return rows.map((row, index) => ({ row: index + 2, name: row.name, mainName: row.mainName })); }

export async function previewMainAltImport(actor: Actor, guildId: string, csv: string): Promise<MainAltPreview> {
  const parsed = previewGuildCsv(csv); const result = await query("SELECT g.roster_version,m.* FROM guilds g LEFT JOIN guild_members m ON m.guild_id=g.id WHERE g.id=$1 AND g.archived_at IS NULL", [guildId]);
  if (!result.rows.length) throw new GuildDomainError("NOT_FOUND", "Guild was not found.");
  await importer({ query: query as any } as any, actor, guildId).catch(async () => { const row=(await query("SELECT * FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 AND active=true",[guildId,actor.id])).rows[0]; if(!row)throw new GuildDomainError("FORBIDDEN","Active guild membership is required."); const membership={id:row.id,guildId,userId:row.user_id,role:row.role,capabilities:row.capabilities??[],revokedCapabilities:row.revoked_capabilities??[],active:true,createdAt:row.created_at,updatedAt:row.updated_at} as any;if(!hasCapability(membership,"import-roster"))throw new GuildDomainError("FORBIDDEN","Roster import permission is required."); });
  const members = result.rows.filter((row: any) => row.id); const relationships = (await query("SELECT alt_member_id,main_member_id FROM guild_main_alt_relationships WHERE guild_id=$1", [guildId])).rows; const mainByAlt = new Map(relationships.map((row: any) => [row.alt_member_id, row.main_member_id]));
  const existing = members.map((row: any) => ({ id: row.id, characterName: row.character_name, active: row.active, mainMemberId: mainByAlt.get(row.id) }));
  const conflicts = classifyMainAltRows(rowsForConflicts(parsed.rows), existing);
  const linked = new Set<string>();
  for (const conflict of conflicts) if (conflict.characterId) { const links=(await query("SELECT DISTINCT user_id FROM guild_member_links WHERE guild_member_id=$1 AND status='approved'",[conflict.characterId])).rows; if(links.length>1){linked.add(conflict.id);conflict.kind="linked-user-conflict";conflict.explanation="Approved user links require officer review; relationship changes do not transfer ownership.";conflict.allowedDecisions=["preserve-existing","apply-imported","leave-unassigned"]; } }
  const byId = new Map(members.map((row:any)=>[row.character_id,row])); let added=0,updated=0,unchanged=0;
  for (const row of parsed.rows) { const id=`${row.region}:${row.realm.toLowerCase()}:${row.name.toLowerCase()}`; const found=byId.get(id); if(!found) added++; else if(found.character_name!==row.name||found.guild_rank!==row.guildRank||found.role!==(row.preferredRole||"DPS"))updated++; else unchanged++; }
  return { token: token(csv, Number(result.rows[0].roster_version)), rosterVersion: Number(result.rows[0].roster_version), rows: parsed.rows, conflicts, summary:{totalRows:parsed.rows.length,newCharacters:added,updatedCharacters:updated,unchangedCharacters:unchanged,absentCharacters:Math.max(0,members.length-parsed.rows.length),invalidRows:parsed.issues.length,duplicateRows:parsed.duplicateNames.length,mainAltConflicts:conflicts.length,linkedCharacterConflicts:linked.size} };
}

function decisionFor(decisions: Record<string, Decision> | undefined, conflict: MainAltConflict) { return decisions?.[conflict.id]; }
function applyDecision(decision: Decision | undefined, conflict: MainAltConflict) { if (!decision) { if (conflict.blocking) throw new GuildDomainError("UNRESOLVED_IMPORT_CONFLICT", `Resolve import conflict: ${conflict.explanation}`); return "preserve-existing" as MainAltDecision; } if (!conflict.allowedDecisions.includes(decision.decision)) throw new GuildDomainError("INVALID_CONFLICT_DECISION", "The selected import conflict decision is not allowed."); return decision.decision; }

export async function applyMainAltImport(actor: Actor, guildId: string, csv: string, policy: Policy, expectedVersion: number, previewToken: string, decisions: Record<string, Decision> = {}) {
  return withTransaction(async (client) => {
    const guild = (await client.query("SELECT * FROM guilds WHERE id=$1 AND archived_at IS NULL FOR UPDATE", [guildId])).rows[0]; if (!guild) throw new GuildDomainError("NOT_FOUND", "Guild was not found.");
    await importer(client, actor, guildId); if (Number(guild.roster_version) !== expectedVersion || token(csv, Number(guild.roster_version)) !== previewToken) throw new GuildDomainError("STALE_IMPORT_PREVIEW", "The guild roster changed after this import was previewed. Generate a new preview before applying it.");
    const parsed=previewGuildCsv(csv); if(parsed.issues.length) throw new GuildDomainError("INVALID_IMPORT", `CSV has ${parsed.issues.length} validation issue(s).`);
    const existing=(await client.query("SELECT * FROM guild_members WHERE guild_id=$1 FOR UPDATE",[guildId])).rows; const byName=new Map<string,any[]>(); for(const member of existing)byName.set(normalizedName(member.character_name),[...(byName.get(normalizedName(member.character_name))??[]),member]);
    const rels=(await client.query("SELECT * FROM guild_main_alt_relationships WHERE guild_id=$1",[guildId])).rows; const currentByAlt=new Map(rels.map((r:any)=>[r.alt_member_id,r.main_member_id])); const conflicts=classifyMainAltRows(rowsForConflicts(parsed.rows),existing.map((m:any)=>({id:m.id,characterName:m.character_name,active:m.active,mainMemberId:currentByAlt.get(m.id)})));
    const conflictByRow=new Map(conflicts.flatMap((conflict)=>conflict.rows.map((row)=>[row,conflict] as const))); const incoming=new Set<string>();
    for(const [index,row] of parsed.rows.entries()){const member=csvRowToMember(row,{realmType:guild.character_realm_type,contentVersion:guild.content_version});incoming.add(member.characterId);const found=existing.find((m:any)=>m.character_id===member.characterId);if(found)await client.query("UPDATE guild_members SET character_name=$1,class_name=$2,level=$3,faction=$4,realm=$5,region=$6,role=$7,guild_rank=$8,active=true,inactive_at=NULL,updated_at=now() WHERE id=$9",[member.characterName,member.className,member.level,member.faction,member.realm,member.region,member.role,row.guildRank,found.id]);else await client.query("INSERT INTO guild_members(guild_id,character_id,character_name,class_name,spec,level,race,faction,realm,region,realm_type,content_version,role,readiness,guild_rank,main_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'unknown',$14,'')",[guildId,member.characterId,member.characterName,member.className,member.spec,member.level,member.race,member.faction,member.realm,member.region,member.realmType,member.contentVersion,member.role,row.guildRank]); const conflict=conflictByRow.get(index+2); if(conflict)applyDecision(decisionFor(decisions,conflict),conflict);}
    const all=(await client.query("SELECT * FROM guild_members WHERE guild_id=$1 FOR UPDATE",[guildId])).rows; const names=new Map(all.map((m:any)=>[normalizedName(m.character_name),m])); const final=rels.map((r:any)=>({mainMemberId:r.main_member_id,altMemberId:r.alt_member_id}));
    try { for(const [index,row] of parsed.rows.entries()){if(!row.mainName)continue;const alt=names.get(normalizedName(row.name));if(!alt)continue;const conflict=conflictByRow.get(index+2);const decision=applyDecision(decisionFor(decisions,conflict as any),conflict as any);if(decision==="preserve-existing")continue;let main=names.get(normalizedName(row.mainName));if(decision==="map-to-existing-character")main=all.find((m:any)=>m.id===decisionFor(decisions,conflict as any)?.targetMemberId);if(!main)throw new GuildDomainError("INVALID_MAIN_REFERENCE","The selected main does not belong to this guild.");const kept=final.filter((r)=>r.altMemberId!==alt.id);if(decision!=="leave-unassigned")kept.push({mainMemberId:main.id,altMemberId:alt.id});try{validateRelationshipGraph(kept,new Set(all.map((m:any)=>m.id)));}catch{throw new GuildDomainError("MAIN_ALT_CYCLE","The import would create an invalid main/alt relationship graph.");}await client.query("DELETE FROM guild_main_alt_relationships WHERE guild_id=$1 AND alt_member_id=$2",[guildId,alt.id]);if(decision!=="leave-unassigned")await client.query("INSERT INTO guild_main_alt_relationships(guild_id,main_member_id,alt_member_id) VALUES($1,$2,$3)",[guildId,main.id,alt.id]);await client.query("UPDATE guild_members SET main_name=$1 WHERE id=$2",[decision==="leave-unassigned"?"":main.character_name,alt.id]);await client.query("INSERT INTO guild_main_alt_history(guild_id,alt_member_id,previous_main_member_id,new_main_member_id,actor_user_id,source,decision,reason) VALUES($1,$2,$3,$4,$5,'CSV import',$6,$7)",[guildId,alt.id,currentByAlt.get(alt.id)??null,decision==="leave-unassigned"?null:main.id,actor.id,decision,"CSV relationship resolution"]);await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'guild_member',$3,$4,$5)",[actor.id,guildId,alt.id,`main-alt.${decision}`,JSON.stringify({characterId:alt.id,previousMainId:currentByAlt.get(alt.id)??null,newMainId:decision==="leave-unassigned"?null:main.id,decision})]);} } catch(error){if(error instanceof GuildDomainError)throw error;throw new GuildDomainError("INVALID_RELATIONSHIP","The relationship resolution could not be applied.");}
    let markedInactive=0;if(policy==="mark-inactive")for(const member of existing)if(!incoming.has(member.character_id)&&member.active){await client.query("UPDATE guild_members SET active=false,inactive_at=now(),updated_at=now() WHERE id=$1",[member.id]);markedInactive++;}
    const version=(await client.query("UPDATE guilds SET roster_version=roster_version+1,last_roster_sync_at=now(),updated_at=now() WHERE id=$1 RETURNING roster_version",[guildId])).rows[0].roster_version;const summary={rows:parsed.rows.length,rosterVersion:version,relationshipDecisions:Object.values(decisions).map((d)=>d.decision)};await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'guild',$2,'roster.import-applied',$3)",[actor.id,guildId,JSON.stringify(summary)]);return { ...summary, markedInactive };
  });
}

export async function setMainAltRelationship(actor:Actor,guildId:string,altMemberId:string,mainMemberId:string|undefined,reason="manual officer change") { return withTransaction(async(client)=>{await importer(client,actor,guildId);const members=(await client.query("SELECT * FROM guild_members WHERE guild_id=$1 FOR UPDATE",[guildId])).rows;const ids=new Set(members.map((m:any)=>m.id));if(!ids.has(altMemberId)|| (mainMemberId&&!ids.has(mainMemberId)))throw new GuildDomainError("CROSS_GUILD_MAIN","Character relationship must use members of this guild.");const rels=(await client.query("SELECT * FROM guild_main_alt_relationships WHERE guild_id=$1",[guildId])).rows;const previous=rels.find((r:any)=>r.alt_member_id===altMemberId)?.main_member_id;const next=rels.filter((r:any)=>r.alt_member_id!==altMemberId).map((r:any)=>({mainMemberId:r.main_member_id,altMemberId:r.alt_member_id}));if(mainMemberId)next.push({mainMemberId,altMemberId});try{validateRelationshipGraph(next,ids);}catch(error:any){if(error.message==="self-main")throw new GuildDomainError("SELF_MAIN","A character cannot be its own main.");throw new GuildDomainError("MAIN_ALT_CYCLE","That relationship would create a main/alt cycle.");}await client.query("DELETE FROM guild_main_alt_relationships WHERE guild_id=$1 AND alt_member_id=$2",[guildId,altMemberId]);if(mainMemberId)await client.query("INSERT INTO guild_main_alt_relationships(guild_id,main_member_id,alt_member_id) VALUES($1,$2,$3)",[guildId,mainMemberId,altMemberId]);await client.query("UPDATE guild_members SET main_name=$1 WHERE id=$2",[mainMemberId?members.find((m:any)=>m.id===mainMemberId).character_name:"",altMemberId]);await client.query("UPDATE guilds SET roster_version=roster_version+1,updated_at=now() WHERE id=$1",[guildId]);await client.query("INSERT INTO guild_main_alt_history(guild_id,alt_member_id,previous_main_member_id,new_main_member_id,actor_user_id,source,decision,reason) VALUES($1,$2,$3,$4,$5,'manual officer change',$6,$7)",[guildId,altMemberId,previous??null,mainMemberId??null,actor.id,mainMemberId?"apply-imported":"leave-unassigned",reason]);await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'guild_member',$3,$4,$5)",[actor.id,guildId,altMemberId,mainMemberId?"main-alt.created":"main-alt.removed",JSON.stringify({previousMainId:previous??null,newMainId:mainMemberId??null,reason})]);return {altMemberId,mainMemberId};}); }
export async function getMainAltRoster(guildId:string) { const members=(await query("SELECT id,character_name,class_name,role,active,realm,region FROM guild_members WHERE guild_id=$1 ORDER BY character_name",[guildId])).rows;const relationships=(await query("SELECT alt_member_id,main_member_id FROM guild_main_alt_relationships WHERE guild_id=$1",[guildId])).rows;const byId=new Map(members.map((m:any)=>[m.id,m]));const alts=new Map(relationships.map((r:any)=>[r.main_member_id,[...(relationships.filter((x:any)=>x.main_member_id===r.main_member_id).map((x:any)=>byId.get(x.alt_member_id)).filter(Boolean))]]));return {members,relationships,groups:members.filter((m:any)=>!relationships.some((r:any)=>r.alt_member_id===m.id)).map((main:any)=>({main,alts:alts.get(main.id)??[]}))}; }
