import { query, withTransaction } from "./db.ts";
import { GuildDomainError } from "./errors.ts";
import { hasCapability } from "./permissions.ts";
import type { EffectiveSignupStatus, GuildCapability, MemberSignupStatus, RaidAssignment } from "./types.ts";

type Actor = { id: string };
const memberStatuses: MemberSignupStatus[] = ["accepted", "tentative", "unavailable", "late"];
const effectiveStatuses: EffectiveSignupStatus[] = [...memberStatuses, "no-response"];
function validMemberStatus(value: string): value is MemberSignupStatus { return memberStatuses.includes(value as MemberSignupStatus); }
function validEffectiveStatus(value: string): value is EffectiveSignupStatus { return effectiveStatuses.includes(value as EffectiveSignupStatus); }
async function membership(actor: Actor, guildId: string, capability: GuildCapability) { const row=(await query("SELECT * FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 AND active=true",[guildId,actor.id])).rows[0]; if(!row) throw new GuildDomainError("FORBIDDEN","Active guild membership is required."); const m={id:row.id,guildId:row.guild_id,userId:row.user_id,role:row.role,capabilities:row.capabilities??[],revokedCapabilities:row.revoked_capabilities??[],active:true,createdAt:row.created_at,updatedAt:row.updated_at}; if(!hasCapability(m,capability)) throw new GuildDomainError("FORBIDDEN","You do not have permission for this raid action."); return m; }
async function raidAccess(client: any, actor: Actor, guildId: string, eventId: string, capability: GuildCapability) { const m=await membership(actor,guildId,capability); const event=(await client.query("SELECT * FROM raid_events WHERE id=$1 AND guild_id=$2 FOR UPDATE",[eventId,guildId])).rows[0]; if(!event) throw new GuildDomainError("CROSS_GUILD_REFERENCE","Raid does not belong to this guild."); if(m.role === "raid-leader" && event.raid_leader_user_id !== actor.id) throw new GuildDomainError("FORBIDDEN","This raid leader is not assigned to the raid."); return {m,event}; }

export async function saveMemberSignup(actor: Actor, guildId: string, eventId: string, _claimedMemberId: string, status: string, preferredRole: string, alternateRole: string, note: string) {
  if(!validMemberStatus(status)) throw new GuildDomainError("CONFLICT","Members may submit accepted, tentative, unavailable, or late.");
  return withTransaction(async(client)=>{ const event=(await client.query("SELECT id FROM raid_events WHERE id=$1 AND guild_id=$2",[eventId,guildId])).rows[0]; if(!event) throw new GuildDomainError("CROSS_GUILD_REFERENCE","Raid does not belong to this guild."); const member=(await client.query("SELECT m.id FROM guild_members m JOIN guild_member_links l ON l.guild_member_id=m.id AND l.user_id=$1 AND l.status='approved' WHERE m.guild_id=$2 AND m.active=true",[actor.id,guildId])).rows[0]; if(!member) throw new GuildDomainError("FORBIDDEN","An approved character claim is required before signing up."); const result=await client.query("INSERT INTO raid_signups(raid_event_id,guild_member_id,status,member_status,effective_status,preferred_role,alternate_role,member_note,note,updated_by_user_id) VALUES($1,$2,'pending',$3,$3,$4,$5,$6,$6,$7) ON CONFLICT(raid_event_id,guild_member_id) DO UPDATE SET member_status=excluded.member_status,effective_status=CASE WHEN raid_signups.override_actor_user_id IS NULL THEN excluded.member_status ELSE raid_signups.effective_status END,preferred_role=excluded.preferred_role,alternate_role=excluded.alternate_role,member_note=excluded.member_note,note=excluded.note,updated_by_user_id=excluded.updated_by_user_id,updated_at=now() RETURNING *",[eventId,member.id,status,preferredRole.trim(),alternateRole.trim(),note.trim(),actor.id]); if(!result.rows[0]) throw new GuildDomainError("CROSS_GUILD_REFERENCE","Signup could not be saved."); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'raid_signup',$3,'signup.changed',$4)",[actor.id,guildId,result.rows[0].id,JSON.stringify({status,preferredRole:preferredRole.trim(),alternateRole:alternateRole.trim()})]); return result.rows[0].id; });
}

export async function setSignupOverride(actor: Actor,guildId:string,eventId:string,memberId:string,effectiveStatus:string,reason:string) { if(!validEffectiveStatus(effectiveStatus)) throw new GuildDomainError("CONFLICT","Invalid effective signup status."); return withTransaction(async(client)=>{ await raidAccess(client,actor,guildId,eventId,"manage-signup-overrides"); const signup=(await client.query("SELECT * FROM raid_signups WHERE raid_event_id=$1 AND guild_member_id=$2 FOR UPDATE",[eventId,memberId])).rows[0]; if(!signup) throw new GuildDomainError("CROSS_GUILD_REFERENCE","Signup does not belong to this raid."); const action=signup.override_actor_user_id?"signup.override-changed":"signup.override-created"; await client.query("UPDATE raid_signups SET effective_status=$1,override_actor_user_id=$2,override_at=now(),override_reason=$3,updated_at=now() WHERE id=$4",[effectiveStatus,actor.id,reason.trim(),signup.id]); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'raid_signup',$3,$4,$5)",[actor.id,guildId,signup.id,action,JSON.stringify({effectiveStatus,reason:reason.trim()})]); }); }
export async function clearSignupOverride(actor: Actor,guildId:string,eventId:string,memberId:string) { return withTransaction(async(client)=>{ await raidAccess(client,actor,guildId,eventId,"manage-signup-overrides"); const signup=(await client.query("SELECT * FROM raid_signups WHERE raid_event_id=$1 AND guild_member_id=$2 FOR UPDATE",[eventId,memberId])).rows[0]; if(!signup) throw new GuildDomainError("CROSS_GUILD_REFERENCE","Signup does not belong to this raid."); await client.query("UPDATE raid_signups SET effective_status=member_status,override_actor_user_id=NULL,override_at=NULL,override_reason='',updated_at=now() WHERE id=$1",[signup.id]); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'raid_signup',$3,'signup.override-cleared','{}')",[actor.id,guildId,signup.id]); }); }

export type RosterStateInput={selected:string[];benched:string[];groups:Record<string,string[]>;roles:Record<string,string>;};
export async function saveRosterState(actor:Actor,guildId:string,eventId:string,expectedVersion:number,state:RosterStateInput){return withTransaction(async(client)=>{const {event}=await raidAccess(client,actor,guildId,eventId,"manage-raid");if(event.version!==expectedVersion)throw new GuildDomainError("CONFLICT",`Stale update. Current roster version is ${event.version}. Reload and review before saving.`);if(event.roster_locked)throw new GuildDomainError("CONFLICT","The raid roster is locked.");const selected=[...new Set(state.selected)],benched=[...new Set(state.benched)];const selectedSet=new Set(selected);if(selected.some(id=>benched.includes(id)))throw new GuildDomainError("CONFLICT","A character cannot be selected and benched at the same time.");const all=[...selected,...benched];const valid=(await client.query("SELECT id,active FROM guild_members WHERE guild_id=$1 AND id=ANY($2::uuid[])",[guildId,all])).rows;if(valid.length!==all.length)throw new GuildDomainError("CROSS_GUILD_REFERENCE","Roster member does not belong to this guild.");if(valid.some((r:any)=>!r.active&&selectedSet.has(r.id)))throw new GuildDomainError("CONFLICT","Inactive members require an explicit supported override before selection.");const groupMembers=new Map<string,string>();for(const [group,ids] of Object.entries(state.groups)){if(ids.length>5)throw new GuildDomainError("CONFLICT",`Group ${group} cannot contain more than five players.`);for(const id of ids){if(!selectedSet.has(id)||groupMembers.has(id))throw new GuildDomainError("CONFLICT","Each selected character may appear in only one group.");groupMembers.set(id,group);}}await client.query("DELETE FROM raid_roster_entries WHERE raid_event_id=$1",[eventId]);for(const [rosterState,ids] of [["selected",selected],["bench",benched]] as const)for(const id of ids)await client.query("INSERT INTO raid_roster_entries(raid_event_id,guild_member_id,roster_state,group_name,role_name) VALUES($1,$2,$3,$4,$5)",[eventId,id,rosterState,groupMembers.get(id)??null,state.roles[id]??""]);const updated=(await client.query("UPDATE raid_events SET version=version+1,updated_at=now() WHERE id=$1 RETURNING version",[eventId])).rows[0].version;await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'raid_event',$3,'raid.roster-changed',$4)",[actor.id,guildId,eventId,JSON.stringify({selected:selected.length,benched:benched.length})]);return updated;});}
export async function setRosterLock(actor:Actor,guildId:string,eventId:string,expectedVersion:number,locked:boolean){return withTransaction(async(client)=>{const {event}=await raidAccess(client,actor,guildId,eventId,"manage-raid");if(event.version!==expectedVersion)throw new GuildDomainError("CONFLICT",`Stale update. Current roster version is ${event.version}.`);const version=(await client.query("UPDATE raid_events SET roster_locked=$1,version=version+1,updated_at=now() WHERE id=$2 RETURNING version",[locked,eventId])).rows[0].version;await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'raid_event',$3,$4,$5)",[actor.id,guildId,eventId,locked?"raid.roster-locked":"raid.roster-unlocked","{}"]);return version;});}

export async function mutateAssignment(actor:Actor,guildId:string,eventId:string,expectedVersion:number,operation:"create"|"edit"|"delete",assignment:RaidAssignment){return withTransaction(async(client)=>{const {event}=await raidAccess(client,actor,guildId,eventId,"manage-assignments");if(event.assignment_version!==expectedVersion)throw new GuildDomainError("CONFLICT",`Stale assignment update. Current version is ${event.assignment_version}. Reload the latest assignments before applying changes.`);let id=assignment.id; if(operation==="create"){id=(await client.query("INSERT INTO raid_assignments(raid_event_id,label,detail,category,section,position) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[eventId,assignment.label.trim(),assignment.detail??"",assignment.category??"general",assignment.section??"raid",assignment.position??0])).rows[0].id;}else if(operation==="edit"){const result=await client.query("UPDATE raid_assignments SET label=$1,detail=$2,category=$3,section=$4,position=$5,updated_at=now() WHERE id=$6 AND raid_event_id=$7 RETURNING id",[assignment.label.trim(),assignment.detail??"",assignment.category??"general",assignment.section??"raid",assignment.position??0,id,eventId]);if(!result.rows[0])throw new GuildDomainError("CROSS_GUILD_REFERENCE","Assignment does not belong to this raid.");}else{const result=await client.query("DELETE FROM raid_assignments WHERE id=$1 AND raid_event_id=$2 RETURNING id",[id,eventId]);if(!result.rows[0])throw new GuildDomainError("CROSS_GUILD_REFERENCE","Assignment does not belong to this raid.");}if(operation!=="delete"){const ids=[...new Set(assignment.characterIds??(assignment.characterId?[assignment.characterId]:[]))];const valid=(await client.query("SELECT id FROM guild_members WHERE guild_id=$1 AND id=ANY($2::uuid[])",[guildId,ids])).rows;if(valid.length!==ids.length)throw new GuildDomainError("CROSS_GUILD_REFERENCE","Assignment assignee does not belong to this guild.");await client.query("DELETE FROM raid_assignment_assignees WHERE assignment_id=$1",[id]);for(const memberId of ids)await client.query("INSERT INTO raid_assignment_assignees(assignment_id,guild_member_id) VALUES($1,$2)",[id,memberId]);}const version=(await client.query("UPDATE raid_events SET assignment_version=assignment_version+1,updated_at=now() WHERE id=$1 RETURNING assignment_version",[eventId])).rows[0].assignment_version;await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'raid_assignment',$3,$4,$5)",[actor.id,guildId,id,`raid.assignment-${operation}`,JSON.stringify({label:assignment.label})]);return version;});}
