import { query, withTransaction } from "./db.ts";
import { GuildDomainError } from "./errors.ts";
import { hasCapability } from "./permissions.ts";
import { mapPostgresError } from "./postgres-errors.ts";
type Actor = { id: string };
async function membership(actor: Actor, guildId: string, capability?: Parameters<typeof hasCapability>[1]) { const row = (await query("SELECT * FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 AND active=true",[guildId,actor.id])).rows[0]; if (!row) throw new GuildDomainError("FORBIDDEN","Active guild membership is required."); const member = { id:row.id,guildId:row.guild_id,userId:row.user_id,role:row.role,capabilities:row.capabilities??[],revokedCapabilities:row.revoked_capabilities??[],active:row.active,createdAt:row.created_at,updatedAt:row.updated_at }; if (capability && !hasCapability(member, capability)) throw new GuildDomainError("FORBIDDEN","You do not have permission for this action."); return member; }
export async function changeRole(actor: Actor,guildId:string,targetUserId:string,role:"owner"|"officer"|"raid-leader"|"member") { await membership(actor,guildId,"manage-permissions"); if (role === "owner") throw new GuildDomainError("FORBIDDEN","Use ownership transfer to assign an owner."); return withTransaction(async (client)=>{ await client.query("SELECT id FROM guilds WHERE id=$1 AND archived_at IS NULL FOR UPDATE",[guildId]); const current=(await client.query("SELECT role FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 AND active=true FOR UPDATE",[guildId,targetUserId])).rows[0]; if (!current) throw new GuildDomainError("CROSS_GUILD_REFERENCE","Target membership is not active in this guild."); if (current.role === "owner") throw new GuildDomainError("CONFLICT","Transfer ownership before demoting the owner."); await client.query("UPDATE guild_workspace_memberships SET role=$1,updated_at=now() WHERE guild_id=$2 AND user_id=$3",[role,guildId,targetUserId]); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'membership',$3,'membership.role-changed',$4)",[actor.id,guildId,targetUserId,JSON.stringify({role})]); }); }
export async function deactivateMember(actor: Actor,guildId:string,targetUserId:string) { await membership(actor,guildId,"manage-permissions"); return withTransaction(async(client)=>{ const guild=(await client.query("SELECT owner_user_id FROM guilds WHERE id=$1 AND archived_at IS NULL FOR UPDATE",[guildId])).rows[0]; if (!guild) throw new GuildDomainError("NOT_FOUND","Guild was not found."); if (guild.owner_user_id === targetUserId) throw new GuildDomainError("CONFLICT","Transfer ownership before deactivating the final owner."); const result=await client.query("UPDATE guild_workspace_memberships SET active=false,updated_at=now() WHERE guild_id=$1 AND user_id=$2 AND active=true",[guildId,targetUserId]); if(!result.rowCount) throw new GuildDomainError("CROSS_GUILD_REFERENCE","Target membership is not active in this guild."); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'membership',$3,'membership.deactivated','{}')",[actor.id,guildId,targetUserId]); }); }
export async function leaveGuild(actor: Actor,guildId:string) { return deactivateMember(actor,guildId,actor.id); }
