import { query, withTransaction } from "./db.ts";
import { GuildDomainError } from "./errors.ts";
import { defaultCapabilities, hasCapability, roleCapabilities } from "./permissions.ts";
import { REGISTERED_GUILD_CAPABILITIES, type GuildCapability, type GuildMembership, type GuildRole, type CharacterClaimStatus } from "./types.ts";

type Actor = { id: string };
type OverrideMode = "inherit" | "grant" | "revoke";
const safeActions = new Set(["guild.updated", "membership.role-changed", "membership.capability-changed", "membership.activated", "membership.deactivated", "membership.removed", "guild.ownership-transferred", "claim.submitted", "claim.approved", "claim.rejected", "claim.revoked", "roster.import-applied", "raid.created", "raid.roster-changed", "raid.group-changed", "raid.assignment-changed", "signup.changed"]);

function membershipFrom(row: any): GuildMembership { return { id: row.id, guildId: row.guild_id, userId: row.user_id, role: row.role, capabilities: row.capabilities ?? [], revokedCapabilities: row.revoked_capabilities ?? [], active: row.active, createdAt: row.created_at, updatedAt: row.updated_at }; }
async function requireCapability(actor: Actor, guildId: string, capability: GuildCapability) { const row = (await query("SELECT * FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 AND active=true", [guildId, actor.id])).rows[0]; if (!row) throw new GuildDomainError("FORBIDDEN", "Active guild membership is required."); const membership = membershipFrom(row); if (!hasCapability(membership, capability)) throw new GuildDomainError("FORBIDDEN", "You do not have permission for this action."); return membership; }

export async function getGuildSettings(actor: Actor, guildId: string) {
  const membership = (await query("SELECT * FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 AND active=true", [guildId, actor.id])).rows[0];
  if (!membership) throw new GuildDomainError("FORBIDDEN", "Active guild membership is required.");
  const guild = (await query("SELECT * FROM guilds WHERE id=$1 AND archived_at IS NULL", [guildId])).rows[0];
  if (!guild) throw new GuildDomainError("NOT_FOUND", "Guild was not found.");
  const roster = (await query("SELECT id,character_name,realm,active FROM guild_members WHERE guild_id=$1 AND active=true ORDER BY character_name", [guildId])).rows;
  const privileged = membership.role === "owner" || membership.role === "officer";
  const members = privileged ? (await query("SELECT m.*,u.name AS user_name,u.email AS user_email FROM guild_workspace_memberships m JOIN users u ON u.id=m.user_id WHERE m.guild_id=$1 ORDER BY m.active DESC,u.name", [guildId])).rows : [];
  const claims = privileged ? (await query("SELECT l.*,u.name AS claimant_name,u.email AS claimant_email,m.character_name,m.realm,m.region,m.active AS character_active FROM guild_member_links l JOIN users u ON u.id=l.user_id JOIN guild_members m ON m.id=l.guild_member_id WHERE m.guild_id=$1 ORDER BY l.updated_at DESC", [guildId])).rows : [];
  const audit = privileged ? (await query("SELECT a.id,a.created_at,a.action,a.entity_type,a.summary,u.name AS actor_name FROM audit_events a LEFT JOIN users u ON u.id=a.actor_user_id WHERE a.guild_id=$1 AND a.action = ANY($2::text[]) ORDER BY a.created_at DESC LIMIT 100", [guildId, [...safeActions]])).rows : [];
  return { guild, viewer: membershipFrom(membership), roster, members, claims, audit, privileged };
}

export async function updateGuildSettings(actor: Actor, guildId: string, input: { name: string; description: string; raidTimezone: string; defaultContentVersion: "era" | "tbc"; defaultAvailabilityPhase: number; internalNotes: string }) {
  await requireCapability(actor, guildId, "manage-settings");
  if (!input.name.trim() || !Number.isInteger(input.defaultAvailabilityPhase) || input.defaultAvailabilityPhase < 1 || input.defaultAvailabilityPhase > 6) throw new GuildDomainError("CONFLICT", "Guild settings are invalid.");
  return withTransaction(async (client) => { const current = (await client.query("SELECT id FROM guilds WHERE id=$1 AND archived_at IS NULL FOR UPDATE", [guildId])).rows[0]; if (!current) throw new GuildDomainError("NOT_FOUND", "Guild was not found."); await client.query("UPDATE guilds SET name=$1,description=$2,raid_timezone=$3,default_content_version=$4,default_availability_phase=$5,internal_notes=$6,updated_at=now() WHERE id=$7", [input.name.trim(), input.description.trim(), input.raidTimezone.trim() || "UTC", input.defaultContentVersion, input.defaultAvailabilityPhase, input.internalNotes.trim(), guildId]); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'guild',$2,'guild.updated',$3)", [actor.id, guildId, JSON.stringify({ fields: ["name", "description", "raidTimezone", "defaultContentVersion", "defaultAvailabilityPhase", "internalNotes"] })]); });
}

export async function setCapabilityOverride(actor: Actor, guildId: string, targetUserId: string, capability: GuildCapability, mode: OverrideMode) {
  await requireCapability(actor, guildId, "manage-permissions");
  if (!REGISTERED_GUILD_CAPABILITIES.includes(capability)) throw new GuildDomainError("CONFLICT", "Unsupported capability.");
  return withTransaction(async (client) => { const guild = (await client.query("SELECT owner_user_id FROM guilds WHERE id=$1 AND archived_at IS NULL FOR UPDATE", [guildId])).rows[0]; const target = (await client.query("SELECT * FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 AND active=true FOR UPDATE", [guildId, targetUserId])).rows[0]; if (!guild || !target) throw new GuildDomainError("CROSS_GUILD_REFERENCE", "Target membership is not active in this guild."); if (target.role === "owner" && mode === "revoke" && ["manage-settings", "manage-permissions"].includes(capability)) throw new GuildDomainError("CONFLICT", "Owner administration permissions cannot be revoked."); const grants = new Set<GuildCapability>(target.capabilities ?? []); const revokes = new Set<GuildCapability>(target.revoked_capabilities ?? []); grants.delete(capability); revokes.delete(capability); if (mode === "grant") grants.add(capability); if (mode === "revoke") revokes.add(capability); await client.query("UPDATE guild_workspace_memberships SET capabilities=$1,revoked_capabilities=$2,updated_at=now() WHERE guild_id=$3 AND user_id=$4", [JSON.stringify([...grants]), JSON.stringify([...revokes]), guildId, targetUserId]); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'membership',$3,'membership.capability-changed',$4)", [actor.id, guildId, target.id, JSON.stringify({ capability, mode })]); });
}

export async function activateMember(actor: Actor, guildId: string, targetUserId: string) { await requireCapability(actor, guildId, "manage-permissions"); return withTransaction(async (client) => { const result = await client.query("UPDATE guild_workspace_memberships SET active=true,updated_at=now() WHERE guild_id=$1 AND user_id=$2 AND active=false RETURNING id", [guildId, targetUserId]); if (!result.rows[0]) throw new GuildDomainError("CROSS_GUILD_REFERENCE", "Target membership is not inactive in this guild."); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'membership',$3,'membership.activated','{}')", [actor.id, guildId, result.rows[0].id]); }); }
export async function removeMember(actor: Actor, guildId: string, targetUserId: string) { await requireCapability(actor, guildId, "manage-permissions"); return withTransaction(async (client) => { const guild = (await client.query("SELECT owner_user_id FROM guilds WHERE id=$1 AND archived_at IS NULL FOR UPDATE", [guildId])).rows[0]; if (!guild) throw new GuildDomainError("NOT_FOUND", "Guild was not found."); if (guild.owner_user_id === targetUserId) throw new GuildDomainError("CONFLICT", "Transfer ownership before removing the final owner."); const target = (await client.query("DELETE FROM guild_workspace_memberships WHERE guild_id=$1 AND user_id=$2 RETURNING id", [guildId, targetUserId])).rows[0]; if (!target) throw new GuildDomainError("CROSS_GUILD_REFERENCE", "Target membership does not belong to this guild."); await client.query("INSERT INTO audit_events(actor_user_id,guild_id,entity_type,entity_id,action,summary) VALUES($1,$2,'membership',$3,'membership.removed','{}')", [actor.id, guildId, target.id]); }); }

export function capabilityState(membership: any, capability: GuildCapability) { const defaults = roleCapabilities(membership.role as GuildRole); if (membership.revoked_capabilities?.includes(capability)) return "explicitly revoked"; if (membership.capabilities?.includes(capability)) return "explicitly granted"; return defaults.includes(capability) ? "inherited" : "not granted"; }
export function filterClaims(claims: any[], status: CharacterClaimStatus | "all") { return status === "all" ? claims : claims.filter((claim) => claim.status === status); }
