import type { CharacterRealmType, ContentVersion, Faction, Region } from "../types.ts";

export type GuildRole = "owner" | "officer" | "raid-leader" | "member";
export type GuildCapability = "manage-settings" | "manage-permissions" | "import-roster" | "manage-roster" | "manage-notes" | "create-raid" | "manage-raid" | "manage-assignments" | "manage-signup-overrides";
export const REGISTERED_GUILD_CAPABILITIES: readonly GuildCapability[] = ["manage-settings", "manage-permissions", "import-roster", "manage-roster", "manage-notes", "create-raid", "manage-raid", "manage-assignments", "manage-signup-overrides"];
export type GuildMembership = { id: string; guildId: string; userId: string; role: GuildRole; capabilities: GuildCapability[]; revokedCapabilities?: GuildCapability[]; active: boolean; createdAt: string; updatedAt: string };
export type CharacterClaimStatus = "pending" | "approved" | "rejected" | "revoked";
export type CharacterClaim = { id: string; guildId: string; memberId: string; userId: string; status: CharacterClaimStatus; verifiedByUserId?: string; verificationMethod?: "officer-verified" | "battlenet-verified"; createdAt: string; updatedAt: string };
export type SignupStatus = "pending" | "confirmed" | "declined" | "waitlist";
export type MemberSignupStatus = "accepted" | "tentative" | "unavailable" | "late";
export type EffectiveSignupStatus = MemberSignupStatus | "no-response";
export type RaidSignup = { characterId: string; status: SignupStatus; memberSubmittedStatus?: MemberSignupStatus; effectiveStatus?: EffectiveSignupStatus; preferredRole?: string; alternateRole?: string; note?: string; overrideActorUserId?: string; overrideAt?: string; overrideReason?: string; updatedAt: string };
export type GuildMember = { id: string; characterId: string; characterName: string; className: string; spec: string; level: number; race: string; faction: Faction; realm: string; region: Region; realmType: CharacterRealmType; contentVersion: ContentVersion; role: string; readiness: "ready" | "needs-review" | "unknown"; gearSetId?: string; joinedAt: string };
export type RaidGroup = { id: string; name: string; memberCharacterIds: string[] };
export type RaidAssignment = { id: string; characterId: string; characterIds?: string[]; label: string; detail?: string; category?: string; section?: string; position?: number };
export type RaidEvent = { id: string; guildId: string; name: string; instance: string; startsAt: string; durationMinutes: number; status: "draft" | "open" | "locked" | "complete"; version?: number; assignmentVersion?: number; rosterLocked?: boolean; signups: RaidSignup[]; selectedCharacterIds: string[]; groups: RaidGroup[]; assignments: RaidAssignment[]; createdAt: string; updatedAt: string };
export type SignupPreference = "accepted" | "tentative" | "unavailable" | "late";
export type Guild = { id: string; name: string; region: Region; realmSlug: string; realmName: string; characterRealmType: CharacterRealmType; contentVersion: ContentVersion; defaultContentVersion?: ContentVersion; faction: Faction; description: string; ownerUserId: string; importProvider: "manual" | "blizzard" | "json"; externalGuildId?: string; lastRosterSyncAt?: string; raidTimezone?: string; defaultAvailabilityPhase?: number; internalNotes?: string; createdAt: string; updatedAt: string; memberIds: string[]; raidEventIds: string[] };
export type GuildWorkspace = { guild: Guild; roster: GuildMember[]; events: RaidEvent[] };
export type CreateGuildInput = Pick<Guild, "name" | "region" | "realmSlug" | "realmName" | "characterRealmType" | "contentVersion" | "faction" | "description">;
export type CreateRaidInput = Pick<RaidEvent, "name" | "instance" | "startsAt" | "durationMinutes">;
