import { query, withTransaction } from "../guilds/db.ts";
import type { EquippedItem, NormalizedCharacter } from "../types.ts";
import type { CharacterSync } from "./sync-types.ts";

type Row = Record<string, any>;
const iso = (value: any) => value?.toISOString?.() ?? value;
const itemFromRow = (row: Row): EquippedItem => ({ itemId: row.item_id ?? 0, name: row.item_name, slot: row.slot, itemLevel: row.item_level ?? undefined, quality: row.quality, icon: row.icon, stats: row.stats ?? {}, enchantments: row.enchantments ?? [], weapon: row.weapon ?? undefined, setId: row.set_id ?? undefined, specialEffectId: row.special_effect_id ?? undefined, uniqueGroup: row.unique_group ?? undefined, source: row.source ?? undefined, missing: row.item_id == null });
const fromRows = (row: Row, items: Row[]): CharacterSync => ({ id: row.id, userCharacterId: row.user_character_id, syncedAt: iso(row.synced_at), status: row.status, level: row.level ?? undefined, className: row.class_name ?? undefined, spec: row.spec ?? undefined, race: row.race ?? undefined, faction: row.faction ?? undefined, professions: row.professions ?? [], talents: row.talents ?? [], contentVersion: row.content_version, characterRealmType: row.character_realm_type, provider: row.provider, errorCode: row.error_code ?? undefined, errorMessage: row.error_message ?? undefined, equipment: items.map(itemFromRow) });
const syncSelect = "SELECT id,user_character_id,synced_at,level,class_name,spec,race,faction,professions,talents,content_version,character_realm_type,provider,status,error_code,error_message FROM character_syncs";

export class CharacterSyncRepository {
  async getLatestSuccessful(userCharacterId: string) { return this.getOne(`${syncSelect} WHERE user_character_id=$1 AND status='success' ORDER BY synced_at DESC LIMIT 1`, userCharacterId); }
  async getPreviousSuccessful(userCharacterId: string) { return this.getOne(`${syncSelect} WHERE user_character_id=$1 AND status='success' ORDER BY synced_at DESC OFFSET 1 LIMIT 1`, userCharacterId); }
  async getLatestAttempt(userCharacterId: string) { return this.getOne(`${syncSelect} WHERE user_character_id=$1 ORDER BY synced_at DESC LIMIT 1`, userCharacterId); }
  async getHistory(userCharacterId: string, limit = 5) { const result = await query<Row>(`${syncSelect} WHERE user_character_id=$1 ORDER BY synced_at DESC LIMIT $2`, [userCharacterId, Math.max(1, Math.min(limit, 10))]); return Promise.all(result.rows.map((row) => this.withItems(row))); }
  async recordSuccess(userCharacterId: string, character: NormalizedCharacter) { return withTransaction(async (client) => { const sync = await client.query<Row>(`INSERT INTO character_syncs(user_character_id,level,class_name,spec,race,faction,professions,talents,content_version,character_realm_type,provider,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'success') RETURNING *`, [userCharacterId, character.level, character.class, character.spec, character.race, character.faction, JSON.stringify(character.professions), JSON.stringify(character.talents ?? []), character.contentVersion, character.realmType, character.dataMeta?.provider ?? "unknown"]); await this.insertItems(client, sync.rows[0].id, character.equipment); await client.query(`UPDATE user_characters SET class_name=$2,level=$3,race=$4,faction=$5,last_synced_at=$6,updated_at=now() WHERE id=$1 AND archived_at IS NULL`, [userCharacterId, character.class, character.level, character.race, character.faction, sync.rows[0].synced_at]); return fromRows(sync.rows[0], character.equipment.map((item) => ({ ...item, item_id: item.itemId, item_name: item.name, item_level: item.itemLevel, quality: item.quality, icon: item.icon, stats: item.stats, enchantments: item.enchantments ?? [], weapon: item.weapon, set_id: item.setId, special_effect_id: item.specialEffectId, unique_group: item.uniqueGroup, source: item.source, slot: item.slot }))); }); }
  async recordFailure(userCharacterId: string, details: { provider: string; contentVersion: string; characterRealmType: string; code?: string; message: string }) { const result = await query<Row>(`INSERT INTO character_syncs(user_character_id,content_version,character_realm_type,provider,status,error_code,error_message) VALUES($1,$2,$3,$4,'failed',$5,$6) RETURNING *`, [userCharacterId, details.contentVersion, details.characterRealmType, details.provider, details.code ?? "RefreshFailed", details.message]); return fromRows(result.rows[0], []); }
  private async getOne(sql: string, userCharacterId: string) { const result = await query<Row>(sql, [userCharacterId]); return result.rows[0] ? this.withItems(result.rows[0]) : undefined; }
  private async withItems(row: Row) { const items = await query<Row>(`SELECT slot,item_id,item_name,item_level,quality,icon,stats,enchantments,weapon,set_id,special_effect_id,unique_group,source FROM character_sync_items WHERE sync_id=$1 ORDER BY slot`, [row.id]); return fromRows(row, items.rows); }
  private async insertItems(client: any, syncId: string, items: EquippedItem[]) { for (const item of items) await client.query(`INSERT INTO character_sync_items(sync_id,slot,item_id,item_name,item_level,quality,icon,stats,enchantments,weapon,set_id,special_effect_id,unique_group,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`, [syncId, item.slot, item.itemId || null, item.name, item.itemLevel ?? null, item.quality, item.icon, JSON.stringify(item.stats), JSON.stringify(item.enchantments ?? []), item.weapon ? JSON.stringify(item.weapon) : null, item.setId ?? null, item.specialEffectId ?? null, item.uniqueGroup ?? null, item.source ? JSON.stringify(item.source) : null]); }
}
export const characterSyncRepository = new CharacterSyncRepository();

export const characterFromSync = (identity: { id: string; name: string; region: any; realmName: string; contentVersion: any; characterRealmType: any }, sync: CharacterSync) => ({ id: identity.id, name: identity.name, region: identity.region, realm: identity.realmName, contentVersion: identity.contentVersion, realmType: identity.characterRealmType, level: sync.level ?? 0, race: sync.race ?? "Unavailable", class: sync.className ?? "Unavailable", spec: sync.spec ?? "Unavailable", faction: sync.faction ?? "Alliance", professions: sync.professions, talents: sync.talents, equipment: sync.equipment, dataMeta: { provider: sync.provider as any, isLive: sync.provider === "blizzard", lastUpdated: sync.syncedAt } });
