import Link from "next/link";
import { notFound } from "next/navigation";
import { VersionShell } from "../../../components/version-shell";
import { isContentVersion } from "../../../lib/game-data";
import { requireAuthenticatedUser } from "../../../lib/auth";
import { savedCharacterRepository } from "../../../lib/characters/saved-repository";
import { setPrimaryCharacterAction } from "../../../lib/characters/saved-actions";
import type { ContentVersion } from "../../../lib/types";

export default async function OnboardingPage({ params }: { params: Promise<{ version: string }> }) { const { version: raw } = await params; if (!isContentVersion(raw)) notFound(); const version = raw as ContentVersion; const user = await requireAuthenticatedUser(); const characters = await savedCharacterRepository.listSavedCharacters(user.id); const primary = characters.find((character) => character.isPrimary); return <VersionShell version={version}><main className="mx-auto min-h-[calc(100vh-148px)] max-w-[980px] px-5 py-12 lg:px-8 lg:py-16"><div className="max-w-2xl"><div className="eyebrow mb-3">Welcome to PrePull</div><h1 className="display text-5xl tracking-[-.04em]">Build your player home.</h1><p className="mt-4 text-sm leading-7 text-[var(--muted)]">A short path to the characters, guilds and preparation that matter to you.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3"><Step number="01" title="Add your first character" done={characters.length > 0} /><Step number="02" title="Choose your primary character" done={Boolean(primary)} /><Step number="03" title="Visit your dashboard" done={Boolean(primary)} /></div>{characters.length === 0 ? <div className="panel mt-8 rounded-2xl p-8"><h2 className="display text-3xl">Start with a character</h2><p className="mt-3 max-w-lg text-sm leading-6 text-[var(--muted)]">Save a public profile to make PrePull feel like your own preparation companion.</p><Link href={`/${version}/characters/connect`} className="button-primary mt-6 inline-flex">Find a character</Link></div> : <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><div className="eyebrow">Your characters</div><h2 className="display mt-2 text-3xl">Choose your primary.</h2></div><Link href={`/${version}/characters/connect`} className="button-secondary">Add character</Link></div><div className="grid gap-4 sm:grid-cols-2">{characters.map((character) => <article className="panel rounded-2xl p-5" key={character.id}><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">{character.characterName}</h3><p className="mt-1 text-xs text-[var(--muted)]">{character.className} · {character.realmName} · {character.characterRealmType}</p></div>{character.isPrimary && <span className="eyebrow">Primary</span>}</div>{!character.isPrimary && <form action={setPrimaryCharacterAction} className="mt-5"><input type="hidden" name="characterId" value={character.id} /><button className="button-secondary" type="submit">Make primary</button></form>}</article>)}</div>{primary && <Link href={`/${version}/dashboard`} className="button-primary mt-6 inline-flex">Visit your dashboard →</Link>}</section>}</main></VersionShell>; }
function Step({ number, title, done }: { number: string; title: string; done: boolean }) { return <div className={`rounded-xl border p-5 ${done ? "border-[var(--primary)]/50 bg-[var(--surface)]" : "border-[var(--line)] bg-[var(--surface)]/50"}`}><div className="text-xs font-bold tracking-widest text-[var(--primary-light)]">{done ? "✓" : number}</div><p className="mt-4 text-sm font-semibold">{title}</p></div>; }
