import Link from "next/link";
import { notFound } from "next/navigation";
import { VersionShell } from "../../../../../components/version-shell";
import { isContentVersion } from "../../../../../lib/game-data";
import { loadPrimaryAdvice } from "../../../../../lib/player-advice/load";
import { findPlayerAction } from "../../../../../lib/player-advice/service";
import type { ContentVersion } from "../../../../../lib/types";
import type { PlayerTarget } from "../../../../../lib/player-advice/types";
import { protectedRouteCallback } from "../../../../../lib/auth-callback";

export default async function PlayerActionPage({ params }: { params: Promise<{ version: string; actionId: string }> }) { const { version: raw, actionId } = await params; if (!isContentVersion(raw)) notFound(); const version = raw as ContentVersion; const { primary, advice } = await loadPrimaryAdvice(protectedRouteCallback(version, `/dashboard/actions/${actionId}`)); const action = advice ? findPlayerAction(advice, actionId) : undefined; if (!primary || !advice?.supported || !action) notFound(); return <VersionShell version={version}><main className="mx-auto min-h-[calc(100vh-148px)] max-w-[1000px] px-5 py-12 lg:px-8 lg:py-16"><Link href={`/${version}/dashboard`} className="text-xs text-[var(--muted)] hover:text-[var(--primary-light)]">← Back to dashboard</Link><div className="mt-10"><div className="eyebrow">What should I do next? · {action.type}</div><h1 className="display mt-3 text-5xl tracking-[-.04em]">{action.title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[var(--muted)]">{action.reason}</p><div className="mt-5 flex flex-wrap gap-3"><span className="rounded-full border border-[var(--primary)]/50 px-3 py-1.5 text-xs font-bold uppercase tracking-widest text-[var(--primary-light)]">{action.priority} priority</span><span className="rounded-full border border-[var(--line)] px-3 py-1.5 text-xs text-[var(--muted)]">{action.upgradeCount} realistic upgrade{action.upgradeCount === 1 ? "" : "s"}</span></div></div><section className="mt-10 space-y-4"><h2 className="display text-3xl">Recommended targets</h2>{action.targets.map((target) => <TargetCard key={`${target.slot}-${target.itemId}`} target={target} />)}</section><p className="mt-8 text-xs leading-5 text-[var(--muted)]">PrePull uses curated reference priorities. It does not estimate drop rates, farming time, or exact DPS gain.</p></main></VersionShell>; }
function TargetCard({ target }: { target: PlayerTarget }) { return <article className={`panel rounded-2xl p-6 ${target.aspirational ? "border-dashed" : ""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="eyebrow">{target.realistic ? "Realistic target" : "Aspirational target"}</span><h3 className="display mt-2 text-2xl">{target.itemName}</h3></div><span className="rounded-full border border-[var(--line)] px-3 py-1.5 text-xs capitalize text-[var(--muted)]">{target.tier}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><Fact label="Slot" value={target.slot} /><Fact label="Source" value={target.sourceLabel} /><Fact label="Phase" value={target.phase ? `Phase ${target.phase}` : "Current reference"} /></dl>{target.currentItemName && <p className="mt-5 text-sm text-[var(--muted)]">Current context: <span className="text-[var(--text)]">{target.currentItemName}</span></p>}{target.conditionalNote && <p className="mt-4 rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] p-3 text-xs leading-5 text-[var(--muted)]">Conditional context: {target.conditionalNote}</p>}<p className="mt-4 text-xs text-[var(--muted)]">This target is presented as a reference opportunity, not a promise that the item will drop.</p></article>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted)]">{label}</dt><dd className="mt-1 text-[var(--text)]">{value}</dd></div>; }
