import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";
import type { ContentVersion } from "../../lib/types";
import type { Guide, GuideBlock } from "../../lib/guides/types";
import { guideHref, publishedGuides, raidGuide } from "../../lib/guides/registry";
import { guideContent } from "../../lib/guides/content";
import { resolveGuideGear } from "../../lib/guides/gear";
import { wowheadLink, isTrustedArmoryIcon } from "../../lib/armory/wowhead";
import { Header } from "../header";
import { Footer } from "../footer";
import { WowheadTooltips } from "../wowhead-tooltips";
import { GuideDiscovery } from "./guide-discovery";
import { GuideTalentBuilds } from "./guide-talent-builds";
import { guideTalentBuild } from "../../lib/talents/registry";

const linkStyle = "focus-ring inline-flex min-h-11 items-center py-2 text-[var(--accent-hover)] underline underline-offset-4";
export function GuideShell({ version, children }: { version: ContentVersion; children: ReactNode }) {
  return <div data-content-version={version} className="app-shell"><a href="#guide-main" className="focus-ring sr-only focus:not-sr-only focus:absolute focus:z-50 focus:bg-[var(--surface)] focus:p-4">Skip to guide content</a><Header version={version} signedIn={false} versionSwitchPath="/guides" /><main id="guide-main" className="guide-main mx-auto max-w-[1240px] px-5 py-10 lg:px-8">{children}</main><Footer version={version} /></div>;
}
export function GuideBreadcrumbs({ version, guide, index }: { version: ContentVersion; guide?: Guide; index?: string }) {
  const crumbs = [{ title: "Guides", href: `/${version}/guides` }];
  const classGuide = guide?.type === "spec" ? guide : index?.split("/").length === 2 ? publishedGuides(version).find(entry => entry.type === "spec" && entry.slug.startsWith(`${index}/`)) : undefined;
  if (guide?.type === "spec" || index?.startsWith("classes")) {
    crumbs.push({ title: "Classes", href: `/${version}/guides/classes` });
    if (classGuide?.type === "spec") crumbs.push({ title: classGuide.className, href: `/${version}/guides/${classGuide.slug.split("/").slice(0, -1).join("/")}` });
  } else if (guide || index === "raids") crumbs.push({ title: "Raids", href: `/${version}/guides/raids` });
  if (guide?.type === "boss") { const raid = raidGuide(version, guide.raidId); if (raid) crumbs.push({ title: raid.title, href: guideHref(raid) }); }
  if (guide) crumbs.push({ title: guide.title, href: guideHref(guide) });
  return <nav aria-label="Breadcrumbs"><ol className="flex flex-wrap items-center gap-x-3 text-sm">{crumbs.map((crumb, i) => <li key={crumb.href} className="min-w-0 break-words">{i > 0 && <span aria-hidden="true" className="mr-3">/</span>}{i === crumbs.length - 1 ? <span aria-current="page">{crumb.title}</span> : <Link className={linkStyle} href={crumb.href}>{crumb.title}</Link>}</li>)}</ol></nav>;
}
export function GuideIndex({ version, index = "" }: { version: ContentVersion; index?: string }) {
  const guides = publishedGuides(version).filter(guide => index.startsWith("classes") ? guide.type === "spec" : index === "raids" ? guide.type === "raid" : true);
  const title = index === "raids" ? "Raid & Boss Guides" : index === "classes/warrior" ? "Warrior guides" : index === "classes" ? "Class & Spec Guides" : "Guides";
  return <GuideShell version={version}><GuideBreadcrumbs version={version} index={index} /><header className="mt-8 max-w-3xl"><p className="eyebrow">{version === "era" ? "Classic Era" : "The Burning Crusade"}</p><h1 className="display mt-3 text-5xl sm:text-6xl">{title}</h1><p className="mt-5 text-lg text-[var(--text-muted)]">{version === "era" ? "Know your role. Prepare your character. Walk into the raid with a plan." : "TBC guides are coming later. No TBC class, raid or boss guides are published yet."}</p></header>{version === "era" && <><nav aria-label="Guide categories" className="mt-6 flex flex-wrap gap-3"><Link className="button-secondary focus-ring" href={`/${version}/guides/classes`}>Class & Spec Guides</Link><Link className="button-secondary focus-ring" href={`/${version}/guides/raids`}>Raid & Boss Guides</Link></nav><GuideDiscovery guides={guides} /></>}</GuideShell>;
}
function WowheadEntry({ version, type, id, name }: { version: ContentVersion; type: "item" | "spell"; id: number; name: string }) {
  return <a className={linkStyle} href={wowheadLink(version, version === "era" ? "era" : "anniversary", type, id)} data-wowhead={`domain=${version === "era" ? "classic" : "tbc"}&${type}=${id}`} data-wh-rename-link="false" target="_blank" rel="noopener noreferrer">{name}<span className="sr-only"> on Wowhead (opens in a new tab)</span></a>;
}
function Block({ block, guide }: { block: GuideBlock; guide: Guide }) {
  if (block.kind === "talent-build") { const choices = [block.buildId, ...(block.alternativeBuildIds ?? [])].map(guideTalentBuild).filter(data => data !== undefined); return choices.length ? <GuideTalentBuilds choices={choices} /> : null; }
  if (block.kind === "paragraph") return <p>{block.text}</p>;
  if (block.kind === "list") return <ul className="list-disc space-y-3 pl-5">{block.items.map(item => <li key={item}>{item}</li>)}</ul>;
  if (block.kind === "callout") return <aside className="rounded-xl border-l-4 border-[var(--accent)] bg-[var(--accent-soft)] p-4"><strong>{block.label}</strong><p className="mt-2">{block.text}</p></aside>;
  if (block.kind === "links") return <ul>{block.guideIds.map(id => { const target = publishedGuides(guide.contentVersion).find(entry => entry.id === id); return target ? <li key={id}><Link className={linkStyle} href={guideHref(target)}>{target.title} guide</Link></li> : null; })}</ul>;
  if (block.kind === "wowhead") return <ul className="space-y-3">{block.entries.map(entry => <li key={`${entry.type}-${entry.id}`}><WowheadEntry version={guide.contentVersion} {...entry} /><p className="text-sm text-[var(--text-muted)]">{entry.note}</p></li>)}</ul>;
  if (block.kind === "bosses") return <ol data-testid="boss-cards" className="grid gap-4 sm:grid-cols-2">{publishedGuides(guide.contentVersion).filter(entry => entry.type === "boss" && entry.raidId === block.raidId).map((boss, index) => <li key={boss.id} className="panel min-w-0 rounded-2xl p-5"><h3 className="display text-2xl">{index + 1}. {boss.title}</h3><p className="mt-2 text-sm">{guideContent[boss.id].summary}</p><p className="mt-3 text-xs text-[var(--text-muted)]">{guideContent[boss.id].tags?.join(" · ")}</p><Link className={linkStyle} data-encounter-id={boss.type === "boss" ? boss.encounterId : undefined} href={guideHref(boss)}>View {boss.title} guide</Link></li>)}</ol>;
  return <div className="space-y-7">{resolveGuideGear(block.specKey, block.phases).map(({ set, slots }) => <div key={set.id} data-guide-gear-set={set.id}><h3 className="display text-2xl">{set.phase === 0 ? "Pre-Raid" : `Phase ${set.phase}`}</h3><p className="mt-2 text-sm text-[var(--text-muted)]">{set.description}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{slots.map(({ slot, items }) => <details key={slot} className="min-w-0 rounded-xl border border-[var(--border)] p-4"><summary className="focus-ring cursor-pointer font-semibold">{slot} · {items.length} targets / alternatives</summary><ul className="mt-3 space-y-4">{items.map(({ item, reference }) => <li key={item.itemId} className="armory-slot" data-quality={item.quality} data-guide-item-id={item.itemId}>{isTrustedArmoryIcon(item.icon) && <Image unoptimized src={item.icon} alt="" width={32} height={32} loading="lazy" />}<span className="armory-item-name"><WowheadEntry version={guide.contentVersion} type="item" id={item.itemId} name={item.name} /></span><p className="text-xs">{item.quality} · {reference.tier}</p><p className="mt-1 text-sm">{[reference.source.type, reference.source.instance || reference.source.zone, reference.source.boss || reference.source.quest || reference.source.npc || reference.source.profession || reference.source.reputation].filter(Boolean).join(" · ")}</p>{[reference.notes, reference.weaponContext, reference.raceNotes, reference.faction && `${reference.faction} only`, reference.requiresProfession && `Requires ${reference.requiresProfession}`, ...(reference.factionSources ? Object.entries(reference.factionSources).map(([faction, source]) => `${faction}: ${source}`) : [])].filter(Boolean).map(note => <p key={note} className="mt-2 text-xs text-[var(--text-muted)]">{note}</p>)}</li>)}</ul></details>)}</div></div>)}</div>;
}
export function GuideArticle({ guide }: { guide: Guide }) {
  const content = guideContent[guide.id];
  const siblings = guide.type === "boss" ? publishedGuides(guide.contentVersion).filter(entry => entry.type === "boss" && entry.raidId === guide.raidId) : [];
  const index = siblings.findIndex(entry => entry.id === guide.id);
  const toc = <nav aria-label="On this page"><ul>{content.sections.map(section => <li key={section.id}><a className={`${linkStyle} text-sm`} href={`#${section.id}`}>{section.title}</a></li>)}<li><a className={`${linkStyle} text-sm`} href="#sources">Sources</a></li></ul></nav>;
  return <GuideShell version={guide.contentVersion}><WowheadTooltips refreshKey={guide.id} /><GuideBreadcrumbs version={guide.contentVersion} guide={guide} /><header className="my-8 max-w-3xl"><p className="eyebrow">Classic Era · {guide.type} guide</p><h1 className="display mt-3 break-words text-4xl sm:text-6xl">{guide.title}</h1><p className="mt-4 text-lg text-[var(--text-muted)]">{content.summary}</p><p className="mt-4 text-sm">Last reviewed: <time dateTime={guide.updatedAt}>{guide.updatedAt}</time></p></header>{content.quick && <section aria-labelledby="quick-summary" className="panel mb-8 rounded-2xl p-5"><h2 id="quick-summary" className="display text-2xl">Raid-night summary</h2><dl className="mt-4 grid gap-4 md:grid-cols-3">{[["Before pull", content.quick.before], ["During fight", content.quick.during], ["Watch for", content.quick.watch]].map(([label, value]) => <div key={label}><dt className="font-semibold text-[var(--accent-hover)]">{label}</dt><dd className="mt-2 text-sm leading-6">{value}</dd></div>)}</dl></section>}<div className="grid items-start gap-8 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="guide-toc"><details className="rounded-xl border border-[var(--border)] p-4 lg:hidden"><summary className="focus-ring cursor-pointer font-semibold">On this page</summary>{toc}</details><div className="hidden lg:block">{toc}</div></aside><article className="min-w-0 space-y-9">{content.sections.map(section => <section className="guide-section" key={section.id} id={section.id} aria-labelledby={`${section.id}-heading`}><h2 id={`${section.id}-heading`} className="display mb-4 text-3xl">{section.title}</h2><div className="space-y-4 leading-7">{section.blocks.map((block, i) => <Block key={i} block={block} guide={guide} />)}</div></section>)}<section id="sources" className="guide-section border-t border-[var(--border)] pt-6"><h2 className="display text-2xl">Sources / reviewed against</h2><p className="mt-3 text-sm text-[var(--text-muted)]">Reviewed for {guide.contentVersion === "era" ? "Classic Era" : "The Burning Crusade"} on {guide.updatedAt}. This is an editorial review date, not automatic live verification.</p><ul className="mt-3">{content.sources.map(source => <li key={source.url} className="text-sm"><a className={linkStyle} href={source.url} target="_blank" rel="noopener noreferrer">{source.title} — {source.publisher}<span className="sr-only"> (opens in a new tab)</span></a><span className="block text-xs text-[var(--text-muted)]">Accessed {source.accessedAt}</span></li>)}</ul></section>{siblings.length > 0 && <nav aria-label="Boss navigation" className="flex flex-wrap justify-between gap-4 border-t border-[var(--border)] pt-4">{index > 0 && <Link className={linkStyle} href={guideHref(siblings[index - 1])}>Previous: {siblings[index - 1].title}</Link>}{index < siblings.length - 1 && <Link className={linkStyle} href={guideHref(siblings[index + 1])}>Next: {siblings[index + 1].title}</Link>}</nav>}</article></div></GuideShell>;
}
